### ISSUE TITLE
h2o_pysparkling_2.4 - for Spark 2.4.x

### ISSUE THREAD

**Issue by dvanasseldonk** [h2oai/sparkling-water#1008]
is 
h2o_pysparkling_2.4 - for Spark 2.4.x
currently available on pip?

I am having issues installing it

**Comment by jakubhava** [comment]
No at the time of writing this, next release will be also for Spark 2.4

**Comment by davewdb** [comment]
Is there a target date for the spark 2.4 release?

**Comment by jakubhava** [comment]
It will be out at the start of the new year :)
