### ISSUE TITLE
[Bug] probability calibration does not work in Sparkling Water Dataframe API

### ISSUE THREAD

**Issue by goldminer09** [h2oai/sparkling-water#1108]
Although when calibration is enabled, EasyPredictModelWrapper returns a `BinomialModelPrediction` object which contains both raw probs and calibrated probs, the  
implicit conversion defined here https://github.com/h2oai/sparkling-water/blob/9968342baa6b00eca2daba628f239a47d08c2ce9/ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OMOJOModel.scala#L81-L83 transforms the `BinomialModelPrediction` object to a `BinomialPrediction`, which only contains raw probs (p0, and p1) and calibrated probabilities are NOT returned.  Both raw and calibrated probabilities should be returned to the user.

**Comment by jakubhava** [comment]
Hi @goldminer09, thanks, this is a good point!

Could you give it a try and implement the fix? Thanks!

**Comment by laurendiperna** [comment]
@goldminer09 I made your github issue into a [JIRA](https://0xdata.atlassian.net/browse/SW-1249) Ticket so we can start tracking it. Please feel free to update the ticket if needed [here](https://0xdata.atlassian.net/browse/SW-1249). Thanks!

**Comment by jakubhava** [comment]
Closing this issue as we have JIRA. Currently testing the solution, if all good, will go to the next release. Please use the JIRA to track the progress
