### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by bugejakurt** [h2oai/sparkling-water#12]
When will support for Windows be available please?

**Comment by mmalohlava** [comment]
Still open issue - https://0xdata.atlassian.net/browse/PUBDEV-282

**Comment by bugejakurt** [comment]
Thanks, hope development would start soon.

**Comment by MadMan0708** [comment]
The windows batch scripts are already incorporated into master. You can find them here https://github.com/h2oai/sparkling-water/tree/master/bin. These scripts take exactly same parameters and use the same environmental variables as their Unix equivalents. 
* To start sparkling-shell please use sparkling-shell.cmd
* To run custom examples, please use run-example.cmd

If you have any problems using these scripts, please let us know! 
Thank you

**Comment by mmalohlava** [comment]
@MadMan0708 put support for Windows into master, tested during H2OWorld, please provide feedback in different issue.
