### ISSUE TITLE
XGBoost in H2OGridSearch

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#1200]
I'm trying to use XGBoost algorithm within H2OGridSearch plugged in Spark ML pipeline but getting following error:

`classifier = H2OGridSearch(algo=pysparkling.ml.H2OXGBoost(), hyperParameters=params)`

`...
Py4JJavaError: An error occurred while calling o198.setAlgo.
: java.lang.IllegalArgumentException: Grid Search is not supported for the specified algorithm 'H2OXGBoost_15108b19ed18'. Supported algorithms are gbm, glm, deeplearning
...`

_Using PySparkling /2.4.10/ & H2O /3.24.0.2/ on YARN-cluster mode._

**Comment by jakubhava** [comment]
@dataspekulant thanks for the report!, this is a simple bug, we are doing release tomorrow, will include the fix there

**Comment by jakubhava** [comment]
Fixed with this PR https://github.com/h2oai/sparkling-water/pull/1201, will be in tomorrow's release
