### ISSUE TITLE
model_id parameter not available in H2OXGBoost pipeline wrapper

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#1203]
Trying to define **model_id** parameter in H2OXGBoost pipeline wrapper but getting following error:

`classifier = H2OXGBoost(model_id="test", ntrees=200, eta=0.05)`

`AttributeError: 'H2OXGBoost' object has no attribute 'model_id'`

Attribute is available within h2o.estimators.H2OXGBoostEstimator.
Is it possible to add it also to pysparkling.ml.H2OXGBoost?

_Using PySparkling /2.4.10/ & H2O /3.24.0.2/ on YARN-cluster mode._

**Comment by jakubhava** [comment]
https://0xdata.atlassian.net/browse/SW-1323

**Comment by mn-mikke** [comment]
Hi @dataspekulant,
`H2OXGBoost`, `H2OGLM`, `H2OGBM` and `H2ODeepLearning` algorithms will be enriched with the 'modeId' parameter in the next minor release of Sparkling Water (2.4.13).
