### ISSUE TITLE
Lost scoreContributions

### ISSUE THREAD

**Issue by joscani** [h2oai/sparkling-water#1229]
Hi. I'm using sparkling-water inside spark and when I load a previously saved gbmModel I can't find scoreContributions method which is present in original model.

```
val gbmModel = new GBM(gbmParams).trainModel.get

// gbmModel.scoreContributions works

val destinationURI = URI.create("file:///midir/migbm.zip")

ModelSerializationSupport.exportH2OModel(gbmModel, destinationURI)

val nuevo_modelo : Model[,_,_] = ModelSerializationSupport.loadH2OModel(destinationURI)
//nuevo_modelo.scoreContributions is not present
```
I can predict using my loaded model but I can't get scoreContribution . 
is there anyway to cast model type to hex.tree.gbmModel?

Thanks in advance.

**Comment by jakubhava** [comment]
@joscani you need to specify type of the loaded model, such as 

`val nuevo_modelo : Model[,_,_] = ModelSerializationSupport.loadH2OModel[hex.tree.gbmModel](destinationURI)`

**Comment by joscani** [comment]
Thanks. It was so simply. And thanks for H2O and sparkling water. I think sparkling -water is the most easy way to get a good model in production.

**Comment by joscani** [comment]
I try with 

``` 
import _root_.hex._
val nuevo_modelo : Model[_,_,_] = ModelSerializationSupport.loadH2OModel[tree.gbm.GBMModel](destinationURI)
``` 
But scoreContributions is not available.

```
val nuevo_modelo : Model[_,_,_] = ModelSerializationSupport.loadH2OModel[tree.gbm.GBMModel](destinationURI)
nuevo_modelo: hex.Model[_, _, _] =
Model Metrics Type: Binomial
 Description: N/A
 model id: GBM_model_1559379058804_1
 frame id: train.hex
 MSE: 0.49450788
 RMSE: 0.70321256
 AUC: 0.69820213
 pr_auc: 0.7074569
```

**Comment by joscani** [comment]
I finally get scoreContributions using this
```
val loadedModel: GBMModel = ModelSerializationSupport.loadH2OModel(destinationURI)
```
