### ISSUE TITLE
Consider adding support for Spark pipelines in `rsparkling`

### ISSUE THREAD

**Issue by javierluraschi** [h2oai/sparkling-water#1243]
`sparklyr` supports [Spark pipelines in R](https://blog.rstudio.com/2018/05/14/sparklyr-0-8/) but there is additional work to make them available in `rsparkling`, which would enable users to build H2O pipelines in Spark from R and them move them to production without requiring R at all.

See also: https://databricks.com/session/productionizing-h2o-models-with-apache-spark

**Comment by navdeep-G** [comment]
@javierluraschi Do you have a working example of doing this today with `rsparkling`? What is the "additional work" in this case?

**Comment by jakubhava** [comment]
just fyi: Right now we don't expose our custom pipeline stages in Rsparkling, it's on the road map though

**Comment by jakubhava** [comment]
JIRA issue to track this issue https://0xdata.atlassian.net/browse/SW-1897

**Comment by jakubhava** [comment]
I'm closing this ticket, please use the JIRA to track progress on the issue
