### ISSUE TITLE
h2o-pysparkling-2-4 2.4.12 incompatible with Spark 2.4

### ISSUE THREAD

**Issue by argenisleon** [h2oai/sparkling-water#1244]
- Sparkling Water/PySparkling/RSparkling version
2.4.12
- Hadoop Version & Distribution
2.7
- Are you using Windows/Linux/MAC?
Linux

I am using h2o-pysparkling-2-4 2.4.12 as requirement for https://github.com/ironmussa/optimus. But it complains about the pyspark version: 

ERROR: h2o-pysparkling-2-4 2.4.12 has requirement pyspark<=2.4.0,>=2.4.0, but you'll have pyspark 2.4.1 which is incompatible.
https://travis-ci.org/ironmussa/Optimus/jobs/543180987#L1970

I had tested with version 2.4.10, 2.4.11 and 2.4.12 without success. Is not the 2.4.x versions the correct on for Spark 2.4.x?

**Comment by jakubhava** [comment]
Hi @argenisleon thanks, we know about it and we are planning to bump supported Spark version this release. Thanks for pointing that out

**Comment by jakubhava** [comment]
@argenisleon this will be done in the next release, please use this JIRA to track the issue https://0xdata.atlassian.net/browse/SW-1327. Note that Spark 2.4.2 is not supported and that is on purpose as this particular version breaks compatibility between other minor versions in Spark 2.4.x
