### ISSUE TITLE
RSparkling installation from source is broken

### ISSUE THREAD

**Issue by baank** [h2oai/sparkling-water#1266]
Installation from source:
devtools::install_github("h2oai/sparkling-water", ref="master", subdir="r/src")

Produces the following error message:
```
* installing *source* package ‘h2o’ ...
** R
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (h2o)
✔  checking for file ‘/mnt/tmp/RtmpFVlJIs/remotes9b477e47b712/h2oai-sparkling-water-a612cee/r/src/DESCRIPTION’ ...
─  preparing ‘rsparkling’:
E  checking DESCRIPTION meta-information ...
   Malformed package version.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error in (function (command = NULL, args = character(), error_on_status = TRUE,  : 
  System command error
```
Due to the following commit from @jakubhava :
https://github.com/h2oai/sparkling-water/commit/678e7ed2d7b5345e611a96bf02ca89718c27d476#diff-455fe0e750f4e51b108e12ec3ba46ca1

Specifically replacing 0.2.25 with SUBST_PROJECT_VERSION in the DESCRIPTION file.

**Comment by jakubhava** [comment]
@baank yes, that is correct. It won't be no longer possible to install RSparkling from our github. You will need to install RSparkling from our S3 locations. The last releases does not contain R repo so far as this is recent change and not in the release yet, but the nightly builds will contain it from the next build. Nighties are built every night so you get the same results as with installing with source but with advantage the release package being tested first.

To use latest official RSparkling, please download sparkling water distribution from our main page and follow the install instructions.

**Comment by jakubhava** [comment]
Also please note that from the next release RSparkling is tight directly to specific Sparkling Water as will be explained on the documentation.

After this change is finalized and released, you can install RSparkling as:
1) From official release
`install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/rel-MAJOR_VERSION/MINOR_VERSION/R")`

So for example, to install RSparkling for Sparkling Water 2.4.13, you would do:
`install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.4/13/R")`

2) If you want to install Rsparkling for nightly build

`install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/rel-MAJOR_VERSION/nightly/MINOR_VERSION/R")`

For example, 
`install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.4/nightly/145/R")` will install Rsparkling for nightly builds on top of Spark 2.4
`

**Comment by jakubhava** [comment]
Nightlies have been built. To install latest RSparkling, please do:

For Spark 2.4
`install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.4/nightly/113/R")`

You can find the latest build number (in this case 133) by reading http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.4/nightly/latest.html.

If you need to install RSparkling for different Spark version, just change rel-2.4 to rel-2.3 for example
