### ISSUE TITLE
Method close doesn´t work for H2OContext

### ISSUE THREAD

**Issue by sergiocalde94** [h2oai/sparkling-water#1272]
Hi!

I´m trying to close the H2OContext but it doesn´t work. I defined it with this:

```
val spark: SparkSession = SparkSession
      .builder()
      .appName(AppName)
      .getOrCreate()

val hc: H2OContext = H2OContext.getOrCreate(spark)
```

and I try to close with `hc.stop(stopSparkContext = true)` but it throws an error:

```Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.close()V
        at org.apache.spark.h2o.RestAnnouncementProvider.shutdown(AnnouncementService.scala:156)
        at org.apache.spark.h2o.AnnouncementServiceFactory$AnnouncementServiceImpl$$anonfun$shutdown$1.apply(AnnouncementService.scala:67)
        at org.apache.spark.h2o.AnnouncementServiceFactory$AnnouncementServiceImpl$$anonfun$shutdown$1.apply(AnnouncementService.scala:67)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at org.apache.spark.h2o.AnnouncementServiceFactory$AnnouncementServiceImpl.shutdown(AnnouncementService.scala:67)
        at org.apache.spark.h2o.H2OContext.stop(H2OContext.scala:309)
```

The code is running in a spark application and launched with spark-submit, Using your doc (http://docs.h2o.ai/h2o/latest-stable/h2o-docs/faq/sparkling-water.html) I tried to use `new H2OContext().start()` but it else throws an error `constructor not accesible`.

I also navigate on sparkling water examples but I didn´t get my goal :(

**Comment by jakubhava** [comment]
Hello, 
 the correct way how to create H2OContext is `val hc: H2OContext = H2OContext.getOrCreate(spark)`, the documentation you found is part of H2O and is not updated. Up-to-date Sparkling Water  is available at http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/index.html

Can you please share your Sparkling Water version which you're trying?

**Comment by sergiocalde94** [comment]
I´m using that method but then it throws the error, it tells that method close doesn´t exists.

I´m trying it with sparkling water 2.3.28 with spark 2.3.0 and it throws the error: `Exception in thread "main" java.lang.NoSuchMethodError: org.apache.http.impl.client.DefaultHttpClient.close()`

**Comment by jakubhava** [comment]
I believe this will be related to https://github.com/h2oai/sparkling-water/issues/1235. Can you please try the nightly build as suggested on the other issue?

**Comment by jakubhava** [comment]
Related to https://github.com/h2oai/sparkling-water/issues/1235 -> Closing this issue as we have a fix. If you have any other issues with using sparkling-water-package_2.11 maven artifact, please let us know
