### ISSUE TITLE
Any chance on adding Factorization Machines to H2O in a near future?

### ISSUE THREAD

**Issue by radek1st** [h2oai/sparkling-water#128]
for example an H2O Spark version for libFFM?

https://www.csie.ntu.edu.tw/~cjlin/libffm/

**Comment by mdymczyk** [comment]
@radek1st we don't implement algorithms in Sparkling Water, just expose H2O algorithms. You can try asking this question on h2oai/h2o-3 Gitter or file a jira

**Comment by mmalohlava** [comment]
FYI: Jira is already there: https://0xdata.atlassian.net/browse/PUBDEV-2714

**Comment by radek1st** [comment]
@mmalohlava thanks
