### ISSUE TITLE
Error: Sparkling Water version is not set

### ISSUE THREAD

**Issue by rsuhada** [h2oai/sparkling-water#129]
I've followed the installation instructions and insalled sparklyr (spark 1.6.2, local), rsparkling and the h2o package. Running:

    library(sparklyr)
    library(rsparkling)
    library(dplyr)
    sc <- spark_connect(master = "local", version = "1.6.2")

Gives:
```
Error in spark_dependencies(spark_version = spark_version, scala_version = scala_version) : 
  Sparkling Water version is not set. Please choose a correct version
```

Loaded packages:
```
dplyr_0.5.0      rsparkling_0.1.0 sparklyr_0.4    
```

Thank you very much!

**Comment by jangorecki** [comment]
Hi @rsuhada
The error message was recently improved and you would get the following message now:
```
Sparkling Water version is not set. Please choose a correct version using options, for example: options(rsparkling.sparklingwater.version = '1.6.7')
```
If you will set `options(rsparkling.sparklingwater.version = '1.6.7')` before calling `spark_connect` you should successfully attach sparkling water java packages to your spark instance. Feel free to reopen if that wouldn't help.
