### ISSUE TITLE
Sparkling Water doesn't run on Databricks cluster

### ISSUE THREAD

**Issue by Gvuillier** [h2oai/sparkling-water#1293]
Hi,

Following this post [https://www.h2o.ai/blog/h2os-automl-in-spark/](url) I tried to experiment using pysparkling H2OAutoML on a Databricks python notebook.

After loading a dataframe and performing some transformations, I used the following code:

```
from pysparkling import *
from pysparkling.ml import H2OAutoML

h2oConf = H2OConf(spark).set("spark.ui.enabled", "true")
hc = H2OContext.getOrCreate(spark, conf=h2oConf)

algoStage = H2OAutoML(maxRuntimeSecs=60,
                       seed=1,
                       labelCol="label_col")

model = algoStage.fit(df)
```

However, after 3 Spark jobs performed, the fitting keeps running indefinitely, regardless of the timeout I set and without any activity on the cluster.

I have no idea why this happens, I suspect it has something to do with the settings used when creating the h2o context. I also get the same issue when trying to convert the dataframe to an H2O frame.

I'm using:
-Spark 2.4.0
-h2o_pysparkling_2.4
On a Databricks cluster in standard execution mode and autoscaling on

**Comment by jakubhava** [comment]
Sparkling Water currently does not support auto-scaling ( on the road map though). Can you please disable it and try again?

**Comment by Gvuillier** [comment]
Hi Jakub,

Yes that was the issue, thanks!

I was also wondering if there was a way to get additional information on the fitted models.  H2OAutoML.fit() creates a leaderboard and returns a MOJOModel object for production, but I would like to extract the actual h2o model to apply model.varimp() and observe feature importances. Would that be feasible?

Thanks

**Comment by jakubhava** [comment]
On the fitted model from the pipeline wrapper ( such as `H2OAutoML` ) there is method called `getModelDetails()` which returns details of the fitted model in JSON. We are planning to improve the structure of this in the future so it's not just a plain JSON.

However, if you need to access the h2o model directly, in that case you can't use wrappers for Spark pipelines but H2O algos directly

**Comment by jakubhava** [comment]
Closing. If you have other issues, please let us know! Thanks
