### ISSUE TITLE
Not able initiate H2OContext on databricks , pysparkling

### ISSUE THREAD

**Issue by bharatbargujar** [h2oai/sparkling-water#1357]
Hi Team,

I am trying create H2OContext in python note book on databricks cluster. Following is my environment specs:

Databricks runtime environment: 5.3
Spark = 2.4
Python =  3.5
colorama >= 0.3.8
h2o-pysparkling-2.4

I am writing following code
`
from pysparkling import *

from pyspark.sql import SparkSession

import h2o

spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()

h2oConf = H2OConf(spark).set("spark.ui.enabled", "false")

hc = H2OContext.getOrCreate(spark, conf=h2oConf)`

I am getting following error:

org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 1.0 failed 4 times, most recent failure: Lost task 2.3 in stage 1.0 (TID 40, 10.139.64.7, executor 2): java.io.InvalidClassException: org.apache.spark.h2o.backends.internal.InternalBackendUtils$; local class incompatible: stream classdesc serialVersionUID = -279081412540759760, local class serialVersionUID = -4513453206774459154

Py4JJavaError                             Traceback (most recent call last)
<command-1276558733665018> in <module>()
      4 spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
      5 h2oConf = H2OConf(spark).set("spark.ui.enabled", "false")
----> 6 hc = H2OContext.getOrCreate(spark, conf=h2oConf)

/databricks/python/lib/python3.5/site-packages/pysparkling/context.py in getOrCreate(spark, conf, verbose, pre_create_hook, h2o_connect_hook, **kwargs)
    159 
    160         # Create backing Java H2OContext
--> 161         jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
    162         h2o_context._jhc = jhc
    163         h2o_context._conf = selected_conf

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

Please help in resolving this.

BR,
Bharat

**Comment by bharatbargujar** [comment]
Hi Team,

I have restarted the cluster and now I am getting following different error:

`java.util.ServiceConfigurationError: water.api.Schema: Provider water.automl.api.schemas3.AutoMLBuildSpecV99$AutoMLStoppingCriteriaV99 could not be instantiated
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1276558733665018> in <module>()
      4 spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
      5 h2oConf = H2OConf(spark).set("spark.ui.enabled", "false")
----> 6 hc = H2OContext.getOrCreate(spark, conf=h2oConf)

/databricks/python/lib/python3.5/site-packages/pysparkling/context.py in getOrCreate(spark, conf, verbose, pre_create_hook, h2o_connect_hook, **kwargs)
    159 
    160         # Create backing Java H2OContext
--> 161         jhc = jvm.org.apache.spark.h2o.JavaH2OContext.getOrCreate(jspark_session, selected_conf._jconf)
    162         h2o_context._jhc = jhc
    163         h2o_context._conf = selected_conf

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:
`

**Comment by jakubhava** [comment]
Do you have any additional Sparkling Water libraries, version attached to the cluster?

**Comment by jakubhava** [comment]
We had seem this issue in Databricks which was caused by multiple Sparkling Water libraries, of different versions, attached to the same cluster. We always need to make sure that we use the same versions of Sparkling Water artifacts ( Sparkling Water/PySparkling).

Next Sparkling Water release 3.26.3 contains detection mechanism for this and throws an exception if we discover that artifacts from different sparkling water versions attached to the same cluster

**Comment by alwils** [comment]
@jakubhava I'm having the exact same issue. I followed the DataBricks instructions [here ](https://docs.databricks.com/applications/machine-learning/third-party/index.html#h2o-sparkling-water-python) exactly, using a cluster with DataBricks 6.1 ML Beta Runtime and one Standard_NC6s_v3 (beta) worker.

I only have one installed library on the cluster (h2o_pysparkling_2.4).

Thanks,

**Comment by alwils** [comment]
I just switched to DataBricks Runtime 5.5 LTS (includes Apache Spark 2.4.3, GPU, Scala 2.11) and it works now.

**Comment by ramakrv** [comment]
Hi I am getting the same error.. below are my databricks cluster specs
**42.00 GB | 12 Cores | DBR 6.2 ML | Spark 2.4.4 | Scala 2.11.**

I am trying to run h2ocontext, and i getting below failure. 
_h2oConf = H2OConf(spark).set("spark.ui.enabled", "false")
h2o_context = H2OContext.getOrCreate(spark, conf=h2oConf)_

**Error**

> Job aborted due to stage failure: Task 1 in stage 10.0 failed 4 times, most recent failure: Lost task 1.3 in stage 10.0 (TID 361, 10.139.64.6, executor 25): ExecutorLostFailure (executor 25 exited caused by one of the running tasks) Reason: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.


Kindly need some help on this.

**Comment by jakubhava** [comment]
Databricks `ML` machine types are not supported at this moment

**Comment by ramakrv** [comment]
Thank You. is there a way to update the h2o version to specific version.

**Cluster Specs: 42.00 GB | 12 Cores | DBR 6.2 | Spark 2.4.4 | Scala 2.11**

_**

> Current H2o Version: 3.22.0.3
> Desired h2o version: 3.22.1.2

**_

i have a model trained in the later version and need to use it in the databricks cluster.
