### ISSUE TITLE
Save/Load  H2O Models in spark

### ISSUE THREAD

**Issue by lembrd** [h2oai/sparkling-water#14]
Hi all,
I can't find any way to load generated model into spark environment. 
How we can evaluate our models?

**Comment by mmalohlava** [comment]
Hi Mikhail,

right now we can serialize and deserialize models directly via H2O - look at https://github.com/h2oai/h2o-3/blob/master/h2o-core/src/main/java/water/api/ModelsHandler.java#L181-L208

The code export/import model to/from a given location. You can use similar code from Sparkling Water.

**Comment by Shoxee1214** [comment]
Can you please provide scala code for this?

**Comment by mmalohlava** [comment]
At least Java code:

```java
List<Key> importedKeys = new ObjectTreeBinarySerializer().load(FileUtils.getURI(mimport.dir));
Model model = (Model) importedKeys.get(0).get();
```

**Comment by Tian-Su** [comment]
Hi @mmalohlava,
We tried the Scala code here: 
https://github.com/h2oai/sparkling-water/blob/a0ed1741cfba6fd22496d0ab0d9ef06c8e2b6a92/core/src/main/scala/water/app/SparklingWaterApp.scala#L138-L151

The exportH2OModel seems working. I can see files created in the folder.
But when I tried to load the model, I got this error:
scala> val loadModel = loadH2OModel(new URI("hdfs:///sbx/coaf/delorean/prospector/data/tian/model"))
java.lang.ClassCastException: hex.tree.gbm.GBMModel cannot be cast to scala.runtime.Nothing$

Would you know how to solve the problem?

**Comment by MadMan0708** [comment]
Hi, as @Tian-Su said, the `ModelSerializationSupport` trait contains methods `exportH2OModel` and `loadH2OModel`. These methods are preferred way how to export/load models.

If you need any more help, please feel free to reopen this issue or start new one.

Kuba

**Comment by BenRR** [comment]
Does `ModelSerializationSupport` support hdfs?

**Comment by mmalohlava** [comment]
@BenRR yes
