### ISSUE TITLE
sparkling water external backend hangs on spark to h2o transfer

### ISSUE THREAD

**Issue by ssoftcheck** [h2oai/sparkling-water#1445]
When transferring spark dataframe to h2o frame on external backend, the python (or scala) interpreter hangs. The data loads into H2o though, it is visible through flow ui but describe hangs there. This problem does not occur in internal backend.

```
import pysparkling
import h2o

conf = pysparkling.H2OConf(spark)
# external auto
# conf.set_external_cluster_mode()
# conf.use_auto_cluster_start()
# conf.set_cluster_size(50) 
# conf.set_mapper_xmx('5g')
# conf.set_yarn_queue('x')
# external manual
conf.set_external_cluster_mode()
conf.use_manual_cluster_start()
conf.set_h2o_cluster('xxx', 54321)
conf.set_cluster_size(50)
conf.set_cloud_name('h2o')

hc = pysparkling.H2OContext.getOrCreate(spark, conf)

add_df = sqlContext.sql('select a,b,c ....')
add_df_hc = hc.as_h2o_frame(add_df, 'extra_cols') # HANGS HERE, data not usable from other h2o connections either, e.g. get frame hangs.
```
sparkling water 3.26.0
spark 2.3
hadoop 2.7
yarn client
hadoop manual external backend
hadoop jar $H2O_EXTENDED_JAR -Dmapreduce.job.queuename=x -jobname h2o -nodes 50 -mapperXmx 6g

**Comment by jakubhava** [comment]
Thank you for report @ssoftcheck. Can you please send us YARN logs as well for both the Spark and H2O applications? The application IDS are printed out after the `getOrCreate(spark, conf)` call

**Comment by ssoftcheck** [comment]
[logs.zip](https://github.com/h2oai/sparkling-water/files/3510080/logs.zip)

**Comment by jakubhava** [comment]
@ssoftcheck thanks for the logs, I was looking in them and could not find anything interesting.

Few questions: 
 - Is the behaviour reproducible?
 - Can you reproduce on small number of external H2O nodes, such as 1?
 - What shape does your data have?
- What environment are you running in? CDH/HDP ?

Thanks, Kuba

**Comment by ssoftcheck** [comment]
- Is the behaviour reproducible?
  - Yes, in fact I wasn't sure if i had the correct log saved so started a new session and got the same result
- Can you reproduce on small number of external H2O nodes, such as 1?
  - Yes, still occurs with 1 node
- What shape does your data have?
  - about 1.2M x 19000, H2O stores it at 6 GB 
- What environment are you running in? CDH/HDP ?
  - HDP

**Comment by jakubhava** [comment]
Ok, thanks. Could you please sent us also the configuration you apply to your Sparkling Water & External H2O & ideally minimal reproducible code as well? Thanks

**Comment by mmoselerhcfs** [comment]
We are having the exact same problem, it hangs repeatedly with an external backend using R/sparklyr application to communicate with H2O on the as_h2o_frame call.  There is nothing in the logs that indicate an error/issue and I still see in the debug log that the client is still connected on four H2O server nodes.

**Comment by mmoselerhcfs** [comment]
It looks like this may be a regression in SW 3.26.2-2.4/H2O 3.26.0.2.  So far in our testing, reverting back to SW 2.4.13/H2O 3.24.0.5 seems to be working fine with the exact same configuration and code.

**Comment by jakubhava** [comment]
@mmoselerhcfs could you please send us yarn logs from the working version & the latest version? I would like to see if there are any differences. Thanks

**Comment by ssoftcheck** [comment]
> 
> 
> Ok, thanks. Could you please sent us also the configuration you apply to your Sparkling Water & External H2O & ideally minimal reproducible code as well? Thanks

I can't remember if these values are exactly what i used with my yarn logs as i have been experimenting, and it has not worked on many configurations regarding executor counts and sizes
```
SPARKLING_SUBMIT_ARGS='
--conf spark.executor.instances=5
--conf spark.executor.memory=2g
--conf spark.driver.memory=5g
--conf spark.driver.maxResultSize=4g
--conf spark.dynamicAllocation.enabled=false
--conf spark.sql.autoBroadcastJoinThreshold=-1 
--conf spark.sql.execution.arrow.enabled=true 
--conf spark.scheduler.minRegisteredResourcesRatio=1 
--queue cad
--master yarn
--deploy-mode client'

hadoop jar $H2O_EXTENDED_JAR -Dmapreduce.job.queuename=x -jobname h2o -nodes 50 -mapperXmx 6g
pysparkling $SPARKLING_SUBMIT_ARGS
```

**Comment by jakubhava** [comment]
Hi @ssoftcheck we are about to do release this week -> 3.28.0.3. Would it be possible for you to give that release a try? Thanks, Kuba

**Comment by jakubhava** [comment]
Sparkling Water 3.28.0.3 is released which fixes the clouding issues.

    Spark 2.4: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.28.0.3-1-2.4/index.html
    Spark 2.3: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.3/3.28.0.3-1-2.3/index.html
    Spark 2.2: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.2/3.28.0.3-1-2.2/index.html
    Spark 2.1: http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.1/3.28.0.3-1-2.1/index.html

Could you please please give that the release a try? If the issue persist, please feel free to reopen this issue.
