### ISSUE TITLE
I can't understand that Create Spark context which will drive computation

### ISSUE THREAD

**Issue by JonLeeCSDN** [h2oai/sparkling-water#1456]
I did the exercises based on the examples on this website(https://github.com/h2oai/sparkling-water/blob/master/examples/src/main/scala/org/apache/spark/examples/h2o/DeepLearningDemo.scala).
maven:
`    <dependency>
        <groupId>ai.h2o</groupId>
        <artifactId>sparkling-water-examples_2.11</artifactId>
        <version>3.26.2-2.4</version>
    </dependency>`
however,in our code configure will compilation error,i am codeing by IntelliJ IDEA 2019.1
i dont understand mean of this conf.
`// Create Spark context which will drive computation
    val conf = configure("Sparkling Water: Prostate demo")
    val sc = new SparkContext(conf)`
running result：
Error:(14, 16) not found: value configure
    val conf = configure("Sparkling Water: Prostate demo")

**Comment by jakubhava** [comment]
@JonLeeCSDN can I suggest using sparkling-water-package_2.11:3.26.2-2.4 as a maven dependency? This package has all sparkling water & h2o dependencies included and the ones which often conflict with other environments are shaded.

Regarding your error -> the method configure is available in `water.support.SparkContextSupport` object. you need to import it first

**Comment by jakubhava** [comment]
Closing the issue. Please re-open if you still have any troubles.
