### ISSUE TITLE
Classification Prediction Column (no obvious mapping of classes)

### ISSUE THREAD

**Issue by S-C-H** [h2oai/sparkling-water#1474]
The Prediction Column for the Classification algorithm returns the probabilities for each of the classes. How can I determine which class the numbers (which go upwards from 0) belong to? Do I need to map each to a 0 to n classes index? And is their a guarantee that this will be the correct index in the prediction array given these will need to be passed as a string to be recognized as a classification problem?

```
automlEstimator =H2OAutoML(featuresCols=train_cols, labelCol="label", maxModels=1, keepCrossValidationModels=False, splitRatio=0.9)
model = automlEstimator.fit(train_out)
predictions = model.transform(test_out)
```
![image](https://user-images.githubusercontent.com/54514960/63819733-8aa92c00-c99a-11e9-82af-df31c9410982.png)

**Comment by jakubhava** [comment]
We are iterating towards improving this. For start, this PR which will be in next major release prepares the code for additional changes https://github.com/h2oai/sparkling-water/pull/1508/files

**Comment by jakubhava** [comment]
JIRA to track this issue https://0xdata.atlassian.net/browse/SW-1897

**Comment by jakubhava** [comment]
@S-C-H Just wanted to let you know that from the next major release 3.28.1.1, you can run
```
automlEstimator = H2OAutoML(featuresCols=train_cols, labelCol="label", maxModels=1, splitRatio=0.9, withDetailedPredictionCol=True)
model = automlEstimator.fit(train_out)
```

The important part is the `withDetailedPredictionCol=True`. Without this, the prediction column contains directly the predicted label only. With this option, we generate also additional column in the final dataset with the name `detailed_prediction` which contains also map from label to predicted probabilities.

**Comment by jakubhava** [comment]
You can see the PR here https://github.com/h2oai/sparkling-water/pull/1816
