### ISSUE TITLE
h2o-pysparkling-2.4 | Error when initializing a H2oContext

### ISSUE THREAD

**Issue by Rize1391** [h2oai/sparkling-water#1490]
Hello Team,

I am trying to run h2o-pysparkling-2.4 on a Azure Databricks environment.
The cluster config is
Runtime version - 5.5 LTS or 5.3 (includes Apache Spark 2.4.3, Scala 2.11)
Python version - 3
Standard_D32s_v3 - 10 workers
Standard_DS13_v2 - 1 Driver
colorama = 0.3.8 package installed

Note: There are no other pysparkling libraries installed.

and ran the below code,

from pysparkling import *
from pyspark.sql import SparkSession
import h2o
spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
h2oConf = H2OConf(spark).set("spark.ui.enabled", "false")
hc = H2OContext.getOrCreate(spark, conf=h2oConf)

Until last night it was working fine, but as of now when I am trying to create the H2o cloud I am getting an error of either,

**'NoneType' object has no attribute 'group'**

or

**cannot import name 'Context'**

I fixed a few library settings and now facing the below error

**java.lang.RuntimeException: Cloud size 1 under 5**

I have tried all types of solutions but to no avail.
Any help would be greatly appreciated.
Thanks!

**Comment by jakubhava** [comment]
@Rize1391 can you please share screenshot of the attached libraries? Can you please also give us the exact version of Pysparkling you are using? You can run

```
import pysparkling
pysparkling.__version__
```

**Comment by Rize1391** [comment]
@jakubhava 
![Libraries](https://user-images.githubusercontent.com/20426123/63934986-2c537a80-ca7a-11e9-947d-821ea4347a60.PNG)

Added the screenshot of the libraries.

pysparkling version - '3.26.3-2.4'

**Comment by jakubhava** [comment]
Can you remove the `h2o` package ? It is already bundled inside PySparkling of the correct version. Could you also share with us the full stacktrace of the error? 

Thanks, Kuba

**Comment by Rize1391** [comment]
@jakubhava 
Uninstalling H2o helped, and I am able to setup a H2o cluster.
Just a quick qs, I have a 10 node cluster, why has H2o created a 5 node clsuter?


Connecting to H2O server at http://10.156.139.4:54323 ... successful.
--------------------------  ---------------------------------------------------
H2O cluster uptime:         19 secs
H2O cluster timezone:       Etc/UTC
H2O data parsing timezone:  UTC
H2O cluster version:        3.26.0.3
H2O cluster version age:    5 days
H2O cluster name:           sparkling-water-root_app-20190829105124-0000
H2O cluster total nodes:    5
H2O cluster free memory:    422.1 Gb
H2O cluster total cores:    160
H2O cluster allowed cores:  160
H2O cluster status:         accepting new members, healthy
H2O connection url:         http://10.156.139.4:54323
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         XGBoost, Algos, Amazon S3, AutoML, Core V3, Core V4
Python version:             3.5.2 final
--------------------------  ---------------------------------------------------

Sparkling Water Context:
 * Sparkling Water Version: 3.26.3-2.4
 * H2O name: sparkling-water-root_app-20190829105124-0000
 * cluster size: 5
 * list of used nodes:
  (executorId, host, port)
  ------------------------
  (2,10.156.139.8,54321)
  (4,10.156.139.5,54321)
  (3,10.156.139.9,54321)
  (1,10.156.139.10,54321)
  (0,10.156.139.11,54321)
  ------------------------

  Open H2O Flow in browser: http://10.156.139.4:54323 (CMD + click in Mac OSX)

**Comment by jakubhava** [comment]
Do you have auto-scaling enabled? Sparkling Water does not support auto scaling at this moment

**Comment by Rize1391** [comment]
Oh no, auto scaling is not enabled, as I had seen earlier posts that autoscaling is part of the long term roadmap.

**Comment by jakubhava** [comment]
The answer for this is that Sparkling Water wasn't able to discover all the executors at the beginning, found only 5. This means that at some point, when additional executor is added, H2O won't be running on it
