### ISSUE TITLE
[SW v.3.26.2-2.4] unable to start a cluster

### ISSUE THREAD

**Issue by MrHadgehog** [h2oai/sparkling-water#1491]
I've tried to start sparkling water inside of existing spark session but recevied the error `java.lang.NoClassDefFoundError: scala/tools/nsc/interpreter/InteractiveReader`
`Caused by: java.lang.ClassNotFoundException: scala.tools.nsc.interpreter.InteractiveReader`

- Sparkling Water: 3.26.2-2.4 (using via sbt)
- Hadoop Version & Distribution: 2.7.1 with winutils
- Scala version 2.11.12
- local start mode
- Win 10 x64

**spark config**
spark option spark.driver.maxResultSize = 1g
spark option spark.executor.memory = 4g
spark option spark.executor.extraJavaOptions = -Xsm4g
spark option spark.driver.memory = 4g
spark option driver-java-options = -Xsm4g

**scala compiler server options**
JVM options: `-server -Xms6g -Xmx8g -Xss8g`
JVM maximum heap size: 8192MB

**Programm config**
VM options: `-Xms4g -Xmx6g -Xss4g`
Program arguments: `spark.executor.extraJavaOptions='-Xss4g' --driver-java-options '-Xss4g'`
JRE: Java 8 sdk (1.8.0_211) (Oracle)

**Minimal code**
`import org.apache.spark.h2o._`
`val h2oContext = H2OContext.getOrCreate(Test.context)`
`import h2oContext._`

[local-1567080201198.zip](https://github.com/h2oai/sparkling-water/files/3555569/local-1567080201198.zip)

**Comment by jakubhava** [comment]
Thanks for the report @MrHadgehog .

Just quick question, for which Scala version is your Spark build? 2.10, 2.11 or 2.12 ?

Thanks, Kuba

**Comment by MrHadgehog** [comment]
Spark is prebuild for Scala 2.11 and hadoop 2.7 and later

**Comment by jakubhava** [comment]
@MrHadgehog Could you please share your sbt build?

**Comment by MrHadgehog** [comment]
@jakubhava Hi, sure, check the attachment please.
I've just tested the new version 3.28.0.2-1-2.4 as well and facing the same issue. Ping me if you need new logs. Thank you for your help!
[sbt_build.txt](https://github.com/h2oai/sparkling-water/files/4128645/sbt_build.txt)

**Comment by jakubhava** [comment]
Thank you! I can't see Scala listed in your dependencies list, could you please add it there?

**Comment by jakubhava** [comment]
Hi @MrHadgehog I'm assuming this issue was fixed with the latest suggestion. Please feel free to reopen the issue if needed. Thanks.

**Comment by MrHadgehog** [comment]
Hi @jakubhava, thank u for your help, unfortunatelly this solution cannot be tested because we have upgraded to scala 2.12, spark 2.4.4 and hadoop 3.1.1 and I suppose that we cannot use Sparkling Water with this setup anymore. However if u have any ideas how we can build Sparkling Water from the sources for our setup, please, ping me

**Comment by jakubhava** [comment]
Yes, we plan to publish artifacts for default Scala version used in the given Spark. I think next major will switch to Scala 2.12 by default.

 But You can try changing the https://github.com/h2oai/sparkling-water/blob/a95f3b8ff4b72d021e9b8c3309e44cd870e7107e/gradle.properties#L10 and here https://github.com/h2oai/sparkling-water/blob/a95f3b8ff4b72d021e9b8c3309e44cd870e7107e/build.gradle#L88 and then run `./gradlew dist` to build your code.

It's still on my TODO list to see if we build correctly under scala 2.12 or if there are any failures.

**Comment by jakubhava** [comment]
One update, this will still not work as we need to re-organize some code around. You can check the JIRA here https://0xdata.atlassian.net/browse/SW-1846 for progress
