### ISSUE TITLE
Sparkling Water AutoML validation frame and leaderboard frame

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [h2oai/sparkling-water#1615]
Hi, I am new to H2O.
In h2o-3 AutoML [docs](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/automl.html), I can set validation and leaderboard frame.
Can I do it in Sparkling water AutoML?
I can not find it in the [documentation](http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/sw_automl.html).

My env is:
1. Spark 2.4.4 Local mode
2. sparking water 3.26.0.10

Thank you.

**Comment by jakubhava** [comment]
@novan-p-simanjuntak Currently it is not possible on our AutoML wrapper, please create a JIRA at https://0xdata.atlassian.net/secure/RapidBoard.jspa?rapidView=15&projectKey=SW&quickFilter=206
