### ISSUE TITLE
External Backend - Auto mode - version mismatch

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#1617]
Hi,

In **Sparkling Water** I'm trying to use **Auto mode** within **External Backend** on **YARN**.
To obtain **extended H2O driver** I've used **get-extended-h2o.sh** script with value **cdh5.13** as a parameter.

Afterwards I'm getting following error:
`The external H2O cluster ... is of version 3.24.0.2 but Sparkling Water is using version of H2O 3.26.0.8. Please make sure to use the corresponding extended H2O JAR.`

I've tried to download extended H2O driver manually from URL: 
`https://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.4/10/extended/h2odriver-3.24.0.2-cdh5.13-extended.jar` by modifying version number from 3.24.0.2 to 3.24.0.8, but it looks, that this particular file of extended driver is not available.

Will there be newer release of extended drivers for cdh5.13 or how should I proceed?
Thank you,

**Comment by jakubhava** [comment]
@dataspekulant thanks for report.

Quick question -> how did you obtain the sparkling water distribution? Can you pls share the URL? Thanks!

**Comment by dataspekulant** [comment]
Sure. I've downloaded it via:
`https://pypi.org/project/h2o-pysparkling-2.4/`

**Comment by jakubhava** [comment]
Can I suggest download sparkling water from https://www.h2o.ai/download/#sparkling-water ? Here you download the full distribution package. PyPi is intended as artifacts which are easy to get for internal backend at this moment

**Comment by dataspekulant** [comment]
OK, I've installed Sparkling water directly from https://www.h2o.ai/download/#sparkling-water instead from PyPi.
Still getting same kind of error: `The external H2O cluster ... is of version 3.24.0.2 but Sparkling Water is using version of H2O 3.26.0.10. Please make sure to use the corresponding extended H2O JAR.`

**Comment by dataspekulant** [comment]
Thank you. Now after running **get-extended-h2o.sh** it has downloaded the correct version of extended H2O driver.
