### ISSUE TITLE
KMeansModel.KMeansParameter does not has a member '_estimate_k'

### ISSUE THREAD

**Issue by YMorisawa** [h2oai/sparkling-water#162]
Platform : MapR 5.1
Package : Sparkling-water-1.6.8.zip
Language : Scala 2.10

Hi. I'm using a sparkling water with scala.
I tried KMeans and met an error.

--
$spark-shell --master yarn-client --jars "sparkling-water-1.6.8/assembly/build/libs/sparkling-water-assembly-1.6.8-all.jar"
scala>import _root_.hex.kmeans.KMeansModel.KMeansParameter
scala>val param = new KMeansParameter
scala>param._estimate_k
error:value _estimate_k is not a member of hex.kmeans.KMeansModel.KMeansParameters
--
Any other parameters are OK e.g. _k, _max_iterations,etc 

Maybe, the '_estimate_k' is defined in the below code.
https://github.com/h2oai/h2o-3/blob/b0801ec5bdadb9e1ff55f995c572e4906bb27cf5/h2o-algos/src/main/java/hex/kmeans/KMeansModel.java

How can I use '_estimate_k'?

**Comment by mdymczyk** [comment]
@YMorisawa Sparkling Water 1.6.x is using an older H2O version, which doesn't support this parameter yet that's why it's not there.

You can try our latest Sparkling Water 2.x branch, otherwise you'd have to wait for the next 1.6.x release.
