### ISSUE TITLE
H2O Flow cannot plot data that has more than 20 columns

### ISSUE THREAD

**Issue by YMorisawa** [h2oai/sparkling-water#163]
Platform : MapR 5.1
Package : http://h2o-release.s3.amazonaws.com/h2o/rel-tutte/1/h2o-3.10.2.1-mapr5.1.zip

Hi. I'm sorry for writing here , but I cannot find the issue page of H2O flow.
I met a trouble with H2O Flow, Web UI.

When I use a following plot function, if I select a  21th or later column, occurs an error.
----
plot (g) -> g(
  g.point(
    g.position "column1","column21"
  )
g.from inspect "data", getFrame frame
)

Error evaluating cell
Error rendering vis.
Vector [column21] does not exist in frame [data]
----
I tried various combinations and found that 1st to 20th columns could be plotted, but 21th ~ columns could not.
Is there any solution to this problem?

**Comment by mdymczyk** [comment]
@YMorisawa how many columns does the frame you are working with contain? Could you share a sample dataset?

**Comment by YMorisawa** [comment]
@mdymczyk Thank you for replying. The data contains 39 columns and the sample is very simple;

**test.csv**
 column1,column2,...column39
 1,2,3,...39

**Comment by mdymczyk** [comment]
@YMorisawa right, the plot function in Flow does not take column names, you can only use one of our predefined values: label, type, Missing, Zeroes, +Inf, -Inf, min, max, mean, sigmna, cardinality, Actions.

For example:

```
plot (g) -> g(
  g.point(
  g.position "label","Missing"
)
  g.from inspect "columns", getFrame "Key_Frame__test.hex"
)
```

Would graph a plot based using `Key_Frame__test.hex` Frame, where the X axis would plot all the labels (column names `column1,column2,...,column39`) and the Y axis would show how many missing values are in each column.
