### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by tianangthang7** [h2oai/sparkling-water#1666]
Hi! I can not run an example of Sparkling water. Plz help me.

/sparkling-water-3.26.10-2.4$ bash spark-submit --packages ai.h2o:sparkling-water-package_2.11:3.26.10-2.4 --class org.apache.spark.examples.h2o.CraigslistJobTitlesStreamingApp /dev/null
Ivy Default Cache set to: /home/d3m-risk/.ivy2/cache
The jars for the packages stored in: /home/d3m-risk/.ivy2/jars
:: loading settings :: url = jar:file:/opt/spark-2.4.3/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
ai.h2o#sparkling-water-package_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-4458dd0b-4890-4dea-8aca-0756b35222fa;1.0
	confs: [default]
	found ai.h2o#sparkling-water-package_2.11;3.26.10-2.4 in central
:: resolution report :: resolve 242ms :: artifacts dl 8ms
	:: modules in use:
	ai.h2o#sparkling-water-package_2.11;3.26.10-2.4 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   1   |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-4458dd0b-4890-4dea-8aca-0756b35222fa
	confs: [default]
	0 artifacts copied, 1 already retrieved (0kB/6ms)
19/12/05 15:23:53 WARN Utils: Your hostname, d3m-ws resolves to a loopback address: 127.0.1.1; using 103.245.252.14 instead (on interface eno1)
19/12/05 15:23:53 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
19/12/05 15:23:53 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/12/05 15:23:54 WARN SparkSubmit$$anon$2: Failed to load org.apache.spark.examples.h2o.CraigslistJobTitlesStreamingApp.
java.lang.ClassNotFoundException: org.apache.spark.examples.h2o.CraigslistJobTitlesStreamingApp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:238)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:810)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/12/05 15:23:54 INFO ShutdownHookManager: Shutdown hook called
19/12/05 15:23:54 INFO ShutdownHookManager: Deleting directory /tmp/spark-3b8ea4ef-6f4b-474e-8241-524ee7ed4a72

**Comment by jakubhava** [comment]
Sparkling Water examples have been removed from the production JAR file in this change https://github.com/h2oai/sparkling-water/commit/cf7e459d8c4cfe1fb977405a02efa1016fe22bde#diff-609fa1e2d29e223429c73b12a3466252

If you want to run examples, please download the examples jar from maven central https://mvnrepository.com/artifact/ai.h2o/sparkling-water-examples_2.11/3.26.10-2.4 and specify this jar as the application JAR to your Spark job
