### ISSUE TITLE
Error running rsparkling in RStudio

### ISSUE THREAD

**Issue by renegademonkey** [h2oai/sparkling-water#169]
Hi there,

I'm trying to set up and test a local  instance of sparklingwater in RStudio (using sparklyr), and while I can initialize and run H2o, I get an error when I try to run as_h2o_frame() (see below). I'm on ubuntu running:

R 3.2.3 
H2o 3.10.2.2
sparklyr 0.5.1 (with spark 2.0.2 / hadoop 2.7 / scala 2.11.6)
rsparkling 0.1.0

Many thanks for any help you can provide!

Rafael

----------------------------------

Error: java.lang.ClassNotFoundException: org.apache.spark.h2o.H2OContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:77)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)) . . .
	at java.lang.Thread.run(Thread.java:745)

**Comment by mdymczyk** [comment]
@renegademonkey how did you setup your environment? Did you follow http://spark.rstudio.com/h2o.html ?

**Comment by renegademonkey** [comment]
Hi there,

thanks for the quick response!

i've tried several different install types, including the one you linked to. The only difference is i installed the the latest rsparkling with > install.packages("h2o", type="source", repos=(c("https://h2o-release.s3.amazonaws.com/h2o/rel-tutte/2/R"))).

**Comment by ledell** [comment]
@renegademonkey That's the cause of the issue.  Currently, we don't support any version of H2O.  This requirement is stated in in "Install h2o" section of the [rsparkling homepage](http://spark.rstudio.com/h2o.html),:

"Today (Sept. 2016, the initial github release of rsparkling) you must use h2o R package version 3.10.0.6 (H2O “Turing” release, build 6) and Spark 1.6, since that version of H2O is embedded in rsparkling. This will be more flexible in the future."

**Comment by renegademonkey** [comment]
Thanks @ledell - that will explain it, I totally missed that. Any idea when there might be support for spark 2.0? Does the development version of rsparkling support it? That version of spark is currently running on our cluster, and we can't really roll it back.

**Comment by mmalohlava** [comment]
@renegademonkey you can try: 
  - SW 2.0.3 with Spark 2.0 and H2O version  3.10.1.2 (https://h2o-release.s3.amazonaws.com/h2o/rel-turnbull/2/index.html)

R package:
```
install.packages("h2o", type="source", repos=(c("https://h2o-release.s3.amazonaws.com/h2o/rel-turnbull/2/R")))
```

**Comment by renegademonkey** [comment]
@mmalohlava - excellent. will try this - many thanks!

Rafael
