### ISSUE TITLE
h2o algorithms in pyspark pipeline

### ISSUE THREAD

**Issue by adbak** [h2oai/sparkling-water#1695]
Hi, thanks for a great repo!

I have `h2o-pysparkling-2.4==3.26.10` installed and want to enrich pyspark pipeline (including StringIndexer, VectorAssembler) with algorithms from h2o. But when I type `from pysparkling.ml import` ontly few of them are available (H2OXGBoost, H2OAutoML and so on). I wanted to end the pipeline with `H2OStackedEnsembleEstimator` from h2o.estimators. Is it possible? And if not, will it ever be?

**Comment by jakubhava** [comment]
Hi @adbak, we currently do not have stack ensemble exposed in our pipeline API but we are aiming at full feature parity with H2O

**Comment by adbak** [comment]
Ok, thank you for the clarification! So for now the only way to do this is to have a pyspark pipeline without a model and training `H2OStackedEnsembleEstimator` on the output of this pipeline (transformed to h2o frame)? While querying the model we need to reconstruct the whole path and first run the pipeline and then run the model. Is it an acceptable way to do this? Should I be worried about overhead due to creating spark session and h2o context?

**Comment by jakubhava** [comment]
> Ok, thank you @jakubhava for the clarification! So for now the only way to do this is to have a pyspark pipeline without a model and training H2OStackedEnsembleEstimator on the output of this pipeline (transformed to h2o frame)?

Yup, this mixed approach is fine. What I would do is to create a pipeline to prepare your data you need to pass to `H2OStackedEnsembleEstimator`, apply `H2OStackedEnsembleEstimator` and produce a mojo model which can be used for scoring without the need of starting H2OContext/H2O ( MOJO is our descriptor of a model independent of H2O runtime) so in this case you don't need to worry about starting H2O Context at the time of predictions.

> Should I be worried about overhead due to creating spark session and h2o context?

For predictions, you don't even need to running H2O clusters and H2OContext as you can score on our MOJO

**Comment by jakubhava** [comment]
Feel free to create a JIRA for supporting StackEnsables pipeline step at https://0xdata.atlassian.net/browse/SW
