### ISSUE TITLE
H2O Connection Error: Unexpected HTTP error

### ISSUE THREAD

**Issue by ramakrv** [h2oai/sparkling-water#1706]
I am trying to train H2O GBM algorithm on Databricks Cluster. H2O session is created, able to load data in to h2O, split the data , but when i am trying to train the model. I got the below error repeatedly

**Databricks specs: TestingCluster, 42.00 GB | 12 Cores | DBR 6.2 | Spark 2.4.4 | Scala 2.11**

> from pysparkling import *
> from pyspark.sql import SparkSession
> import h2o
> spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
> h2oConf = H2OConf(spark).set("spark.ui.enabled", "false")
> hc = H2OContext.getOrCreate(spark, conf=h2oConf)

> table_h2o = h2o.import_file(path = "dbfs:///tables/Somedata.csv", destination_frame = "table_h2o.hex",sep="\t")

> train_df,valid_df, test_df = table_h2o.split_frame(ratios=[0.8,0.1])
> 
> gbm = H2OGradientBoostingEstimator(ntrees = 1024, max_depth = 8,  stopping_metric = "misclassification", learn_rate = 0.02,                                                         
>                      learn_rate_annealing = 0.995,                                               
>                      sample_rate = 0.83,                                                       
>                      col_sample_rate = 0.86, 
>                      score_tree_interval = 8, nfolds =16,seed = 123)
> gbm.train(predictors, response, training_frame=train_df,validation_frame  = valid_df)
> h2o.save_model(gbm, path="dbfs:///tables/", force=True)

**_gbm Model Build progress: |█████████
H2OConnectionError: Unexpected HTTP error: HTTPConnectionPool(host='10.139.64.5', port=54321): Max retries exceeded with url: /3/Jobs/$0300ffffffff$_ad6e0e9e06cc863fde0358b6448a48d1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85d79e2a20>: Failed to establish a new connection: [Errno 111] Connection refused'))_**

Any help on this is appreciated. Thank You

**Comment by ramakrv** [comment]
@jakubhava Hi , Need some help from you regarding issue mentioned above

**Comment by jakubhava** [comment]
@ramakrv Can you please share your version, logs, environment, etc? Thanks
