### ISSUE TITLE
Automatic External Backend - multiple instances

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#1728]
I have **multiple applications** where each of them is creating its own H2O Sparkling Water **External Backend in Automatic mode**.
The problem is when two applications are trying to create its own backend in nearly same time.
Backend of first application is created successfully, however backend of the second application fails in its initialization phase. Is this some kind of know limitation or bug?
_Running PySparkling (3.26.8-2.4) on YARN._

**Comment by mn-mikke** [comment]
Hi @dataspekulant,
this should work. Do you have enough of free resources on your cluster when you're creating `H2OContext` in the second application? Can you share error messages or YARN logs eventually?

**Comment by jakubhava** [comment]
@dataspekulant are you creating both H2OContext from same Spark app? At this time only one H2OContext can exist per Spark app

**Comment by dataspekulant** [comment]
I have tried to run both H2OContext from same Spark app. Thank you for confirmation, that currently this is not possible. Therefore I've split it into two separate Spark applications.
