### ISSUE TITLE
scoring job does not appear in H2O Flow ?

### ISSUE THREAD

**Issue by quertenmont** [h2oai/sparkling-water#173]
Hello,

I notice that nothing appear in the "getJobs" Flow cells when I perform a scoring job...
I find this a bit weird, as it doesn't allow me to get a feeling on the expected running time for my scoring jobs in sparkling water.
Is this normal?

I am working with sparkling-water-core_2.11 version  2.0.2

Thanks in advance,
Loic

**Comment by mdymczyk** [comment]
Hey @quertenmont! Could you prep a small example so we could try to recreate the problem ourselves?

**Comment by quertenmont** [comment]
I don't think I really need to prepare something, it's very basic,
if you train a model on a H2OFrame, you see in H2O Flow UI that there is a training job running.
Once the model is trained, you can use it to make prediction on another H2OFrame (get the prediction columns).  For that phase, nothing appears in H2O Flow UI.
That's a pity, because this stage can also be time consuming if the H2O Frame to evaluate is large.

Cheers,
Loic

**Comment by mmalohlava** [comment]
Hi @quertenmont,

thank you for report! It is a bug - if you try to make a prediction from Python, you will see predict job in the list of jobs.

![image](https://cloud.githubusercontent.com/assets/597582/22263427/47155348-e229-11e6-944f-c2e75ae5561d.png)

However, H2O Flow UI is slightly behind the REST API and still using predict without reporting job.

**Comment by mmalohlava** [comment]
This is jira to track this issue: https://0xdata.atlassian.net/browse/PUBDEV-3956

**Comment by jakubhava** [comment]
Hi @quertenmont, please use the link to Jira to track the issue. I'm closing this issue for now. Thanks for reporting!
