### ISSUE TITLE
Sparkling water Scala 2.12 Support.

### ISSUE THREAD

**Issue by BhushG** [h2oai/sparkling-water#1733]
When will Sparkling water for Scala 2.12 and Spark 2.4 release?

**Comment by mn-mikke** [comment]
https://0xdata.atlassian.net/browse/SW-1846

**Comment by jakubhava** [comment]
Sparkling Water will support Scala 2.12 with Spark 3.0 where Scala 2.12 is default Scala. We will create a documentation for users who want to build older versions of Spark with Scala 2.12 but we won't provide artifacts for Scala 2.12 for older versions
