### ISSUE TITLE
String columns in spark dataframe to enum columns in h2o

### ISSUE THREAD

**Issue by alexHeu** [h2oai/sparkling-water#1742]
Hi,

I have a train and test pyspark dataframe and would like to convert them to h2o to be able to distributed training via pysparkling.
I convert the dataframes as follows:

train_hf = hc.as_h2o_frame(Df_Train, framename="train_hf")
test_hf = hc.as_h2o_frame(Df_Test, framename="test_hf")

Everything works well except the string columns that are treated as strings and not enum within the h2o frames.
What is the best way to convert the string columns to enums? Is there a way to pass the column types during the conversion from spark to h2o?

Thanks in advance
Alex

**Comment by mn-mikke** [comment]
Hi @alexHeu,
you can convert `.asfactor()` to convert given columns to categoricals. [Here](https://github.com/h2oai/sparkling-water/blob/master/py/tests/unit/with_runtime_clientless_sparkling/test_GBM.py#L60) is an example.

**Comment by alexHeu** [comment]
Hi @mn-mikke 
Thanks, that worked well including model training.

How is the behavior if I convert the trained model into a MOJO, create a pysparkling H20MojoModel from it and pass new data as spark dataframes (model.transform(new_data)). 
Is the MOJO correctly converting the spark string cols to the corresponding factors within the model?

Thanks for your help.
Alex

**Comment by mn-mikke** [comment]
`H2OMojoModel` in Python or Scala internally utilizes [`EasyPredictModelWrapper`](https://github.com/h2oai/h2o-3/blob/6dfaeeacf58aa3f3662d54b4a07963779384cb11/h2o-genmodel/src/main/java/hex/genmodel/easy/EasyPredictModelWrapper.java) that makes predictions based on features encoded as strings to be also able to process input from command line. You would need this wrapper if you need to write your own prediction web service. In other words, you don't have to be worried about that. You just need to be sure that names of the feature columns are the same as during the training phase.

We have a plan to make the conversion to categoricals during `.as_h2o_frame()` automatic in future.

**Comment by jakubhava** [comment]
JIRA for reference https://0xdata.atlassian.net/browse/SW-1779

**Comment by jakubhava** [comment]
I'm closing this ticket, please use the JIRA to track progress on the issue
