### ISSUE TITLE
Running Sparkling Water in Kubernetes with Python

### ISSUE THREAD

**Issue by kimcie** [h2oai/sparkling-water#1751]
According to the documentation (https://github.com/h2oai/sparkling-water/blob/master/doc/src/site/sphinx/deployment/kubernetes.rst) to start sparkling water using python on top of Kubernetes one should use scala sparklng water image. This is probably a bug in a documentation. I tried to use python type image, but also without success.I wonder whether it is even possible to use python image to run sparkling water on Kubernetes. Can you provide more details in documentation, how to run sparkling water on Kubernetes using python?

**Comment by jakubhava** [comment]
Thank you for pointing out the bugs in the documentation - JIRA to track the issue https://0xdata.atlassian.net/browse/SW-1896.

> I wonder whether it is even possible to use python image to run sparkling water on Kubernetes
Yes, it is possible, what particular bug have you hit?

**Comment by kimcie** [comment]
As I mentioned I build Docker image for python, put it to registry and set spark.kubernetes.container.image to point to this image. Then I tried to Start Sparkling Water with 3 worker nodes like in documentation. It failed to start driver node with error that there is issue importing   pysparkling. 

I inspected the Dockerfile for python and it seems that the pysparkling is just copied as zip file, but not installed.
```
task createPythonDockerfile(type: Dockerfile) {
    destFile = outputFilePython
    from "spark-py:${sparkVersion}"
    copyFile("h2o_pysparkling_${sparkMajorVersion}-${version}.zip", "/opt/spark/pyspark/python/lib/h2o_pysparkling_${sparkMajorVersion}-${version}.zip")
}
```
The python script used in spark-submit command : 
```
from pysparkling import *
import h2o
from pyspark.sql import SparkSession, SQLContext
from pyspark.conf import SparkConf
import os
import socket


# create a spark session
spark = SparkSession.builder.config(conf=conf).getOrCreate()
spark.sparkContext.setLogLevel("DEBUG")

hc = H2OContext.getOrCreate(spark)
```

**Comment by jakubhava** [comment]
Hi @kimcie, 
 I was able to reproduce the issue. As the outcome, I have created a 2 changes which will be in the next release -> improved documentation & also have fixed the docker images.

PR for improving the documentation: https://github.com/h2oai/sparkling-water/pull/1819/files
PR for fixing the images: https://github.com/h2oai/sparkling-water/pull/1820/files

When 3.28.0.4 release is out, please check http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.28.0.4-1-2.4/doc/deployment/kubernetes.html (the link will start working after we release this version).
