### ISSUE TITLE
Possible Bug as of 1/28/2020

### ISSUE THREAD

**Issue by BrandonRCopeland** [h2oai/sparkling-water#1757]
Hey folks, my code that's been in production for several months is now breaking when I call h2o_context(sc). I'm wondering if there is a new bug that go introduced somehow. Can you check this out? Again, this code is unchanged and was running successfully in production until Tuesday 1/28/20 when it started crashing at the h2o_context(sc) call. Nothing has change.  Cluster version, spark version, R version, etc. are all the same ad it was running fine before.

![image](https://user-images.githubusercontent.com/44583531/73471294-fd4d7780-433d-11ea-89ae-e958b022bb9f.png)

**Comment by mn-mikke** [comment]
@BrandonRCopeland Can you try to reinstall RSparkling library?

```install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.28.0.1-1-2.4/R")```

http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/rsparkling.html

**Comment by BrandonRCopeland** [comment]
That didn't work.  :(

This has been running in production just fine for over a month and then it randomly started failing.

**Comment by BrandonRCopeland** [comment]
It looks like it's an h2o error:

Error : package or namespace load failed for ‘h2o’ in get(method, envir = home):
 lazy-load database '/databricks/spark/R/lib/h2o/R/h2o.rdb' is corrupt

**Comment by mn-mikke** [comment]
What version of sparklyr do you use?

Also can you upgrade h2o repo to the corresponding version? install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-yu/1/R")

**Comment by BrandonRCopeland** [comment]
Let me try.  I'm using the most recent CRAN version of Sparklyr via install.packages("sparklyr").

I trying to update my sparkling water to 3.28.0.1-1-2.4 and am adding the distribution to my cluster via the maven coordinates.  I'll see if that works.

I'm following the documentation here: https://s3.amazonaws.com/h2o-release/sparkling-water/spark-2.4/3.28.0.1-1-2.4/index.html

**Comment by BrandonRCopeland** [comment]
Back in business!  Solution: Migrate to RSparkling version 3.28.0.1-1-2.4.  Instead of uploading JAR file to cluster, use Maven coordinates: ai.h2o:sparkling-water-package_2.11:3.28.0.1-1-2.4.

And here's my updated code:
![image](https://user-images.githubusercontent.com/44583531/73478989-edd52b00-434b-11ea-9c9c-86a29686f66d.png)

Thanks so much for the help @mn-mikke!!!

**Comment by jakubhava** [comment]
@BrandonRCopeland just fyi: With new versions of RSparkling it is not necessary to explicitly upload the Sparkling Water Jar or fetch it from maven. It is already included inside the R package

**Comment by BrandonRCopeland** [comment]
@jakubhava - okay, so then with the above code, I won't need to upload the JAR or the maven?  Just literally boot up my cluster and run the above code?

**Comment by jakubhava** [comment]
Yup, exactly -> please see http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/pysparkling.html

**Comment by BrandonRCopeland** [comment]
@jakubhava - great. Thanks!
