### ISSUE TITLE
h2o loadmodel() functions removed starting 1/28/2020 Databricks

### ISSUE THREAD

**Issue by kaleb-thompson** [h2oai/sparkling-water#1758]
%r
install.packages("sparklyr")
library(sparklyr)

%r
install.packages("h2o", type = "source", repos = "https://h2o-release.s3.amazonaws.com/h2o/rel-yu/1/R")

%r
install.packages("rsparkling", type = "source", repos = "http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.28.0.1-1-2.4/R")

%r
library(rsparkling)

%r
sc <- spark_connect(method="databricks", version = "2.4.0")

%r
h2o_context(sc)

%r

layer1model <- file.path("/dbfs/mnt/hmescrng/hmemodels")
model1 <- file.path(layer1model,"layer1_trained_model")
trained_model1 <- h2o.loadModel(model1)

**Error in h2o.loadModel(model1) : could not find function "h2o.loadModel" Error in h2o.loadModel(model1) : could not find function "h2o.loadModel"
Error in h2o.loadModel(model1) : could not find function "h2o.loadModel"**

**Comment by jakubhava** [comment]
@EffeX12 did you run `library(h2o)` ? If yes and still does not work, can you please report this issue on H2O project?

**Comment by kaleb-thompson** [comment]
> @EffeX12 did you run `library(h2o)` ? If yes and still does not work, can you please report this issue on H2O project?

yes I did. It still doesn't work. Where do I need to post this? I'm new to all this.

**Comment by kaleb-thompson** [comment]
Getting this error now actually: 

Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = page, : Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = page,  : 
  

ERROR MESSAGE:

Found version 3.22.0.3, but running version 3.28.0.1

For more information visit:
  http://jira.h2o.ai/browse/TN-14


Error in .h2o.doSafeREST(h2oRestApiVersion = h2oRestApiVersion, urlSuffix = page,  : 
  

ERROR MESSAGE:

Found version 3.22.0.3, but running version 3.28.0.1

For more information visit:
  http://jira.h2o.ai/browse/TN-14

**Comment by jakubhava** [comment]
https://github.com/h2oai/h2o-3

**Comment by kaleb-thompson** [comment]
> @EffeX12 did you run `library(h2o)` ? If yes and still does not work, can you please report this issue on H2O project?

You were right. I missed that. Thank you very much!
