### ISSUE TITLE
Reopening Issue: Not able to start external backend on YARN : java.io.IOException: Cannot run program "hadoop": error=2, No such file or directory #1759

### ISSUE THREAD

**Issue by BhushG** [h2oai/sparkling-water#1767]
Reopening the issue. It is not resolved yet: https://github.com/h2oai/sparkling-water/issues/1759

Hadoop is already in PATH. That's why I can execute hadoop commands from anywhere. I don't need to specify full path to hadoop. But when I'm executing a spark job to execute command such as "hadoop fs -ls /" then it is not able to find hadoop. In this case, running command through a spark job, I've to specify full path eg. "/home/bhushan/usr/local/hadoop/bin/hadoop dfs -ls /", only then it is able to execute that command.

Even though Hadoop is in PATH. Spark job is not able to detect it.

**Comment by jakubhava** [comment]
Please re-open the original issue and let's keep the communication there
