### ISSUE TITLE
Connect Sparklingwater to DCOS Mesos Spark cluster ?

### ISSUE THREAD

**Issue by crystalfuns** [h2oai/sparkling-water#179]

**Comment by doctapp** [comment]
+1 for mesos support

**Comment by mdymczyk** [comment]
I'm not really sure what kind of support would we need to provide specifically for YARN? Haven't tested it myself but think it should work out of the box?

**Comment by doctapp** [comment]
I think the ExternalH2OBackend [launches an H2O cluster on yarn](https://github.com/h2oai/sparkling-water/blob/fd4e74954558bd2d928615bf836ab722bb84b021/core/src/main/scala/org/apache/spark/h2o/backends/external/ExternalH2OBackend.scala#L67) and we need the same for Mesos.

**Comment by mmalohlava** [comment]
@doctapp if you have time to sketch something we will be happy to help!

**Comment by jakubhava** [comment]
@doctapp closing this issue for know. As Michal said, feel free to contribute via PR
