### ISSUE TITLE
Quantile Regression

### ISSUE THREAD

**Issue by alexHeu** [h2oai/sparkling-water#1809]
Hi,

is it possible to perform Quantile Regression with H2OGBM? I'm seeing the distribution parameter but no way to set quantile_alpha.

Thanks in advance,
Alex

**Comment by jakubhava** [comment]
@alexHeu Yup, that is a good catch, right now we do not expose quantile alpha parameter in Sparkling Water. I have created a JIRA issue to track the issue and the fix itself. It will be in the next release of Sparkling Water 3.28.0.4. PR can be seen here https://github.com/h2oai/sparkling-water/pull/1813
