### ISSUE TITLE
AttributeError: 'H2OContext' object has no attribute 'start'

### ISSUE THREAD

**Issue by phroiland** [h2oai/sparkling-water#186]
C02S81V1G8WM:Downloads me$ $SPARK_HOME/bin/spark-submit --jars $SPARKLING_HOME/assembly/build/libs/$FAT_JAR --master local[*] --driver-memory 2g --driver-java-options "$SCRIPT_H2O_SYS_OPS" --driver-class-path $SPARKLING_HOME/assembly/build/libs/$FAT_JAR --py-files $PY_EGG_FILE --conf spark.driver.extraJavaOptions="-XX:MaxPermSize=384m" ChicagoCrimeDemo.py
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
17/02/10 12:43:21 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "/Users/me/Downloads/ChicagoCrimeDemo.py", line 93, in <module>
    h2oContext = H2OContext(sc).start()
AttributeError: 'H2OContext' object has no attribute 'start'

**Comment by mmalohlava** [comment]
@phroiland It should be `H2OContext.getOrCreate(sc)`

**Comment by phroiland** [comment]
Now I get this:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=384m; support was removed in 8.0
17/02/10 12:49:41 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/02/10 12:49:43 WARN SparkContext: Use an existing SparkContext, some configuration may not take effect.
17/02/10 12:49:43 WARN InternalH2OBackend: Increasing 'spark.locality.wait' to value 30000
17/02/10 12:49:43 WARN InternalH2OBackend: Due to non-deterministic behavior of Spark broadcast-based joins
We recommend to disable them by
configuring `spark.sql.autoBroadcastJoinThreshold` variable to value `-1`:
sqlContext.sql("SET spark.sql.autoBroadcastJoinThreshold=-1")
[Stage 0:>                                                         (0 + 0) / 11]17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 5:
[rdd_0_5]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 2:
[rdd_0_2]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 3:
[rdd_0_3]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 1:
[rdd_0_1]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 6:
[rdd_0_6]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 0:
[rdd_0_0]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 7:
[rdd_0_7]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 4:
[rdd_0_4]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 9:
[rdd_0_9]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 10:
[rdd_0_10]
17/02/10 12:49:43 WARN Executor: 1 block locks were not released by TID = 8:
[rdd_0_8]
----- H2O started  -----                                                        
Build git branch: rel-tverberg
Build git hash: cb4e1d8f5265e8d66c1e88bec133e38f2732c58b
Build git describe: jenkins-rel-tverberg-2
Build project version: 3.10.3.2 (latest version: 3.10.3.4)
Build age: 10 days
Built by: 'jenkins'
Built on: '2017-01-31 12:30:22'
Processed H2O arguments: [-name, sparkling-water-johnfroiland_910297971, -ga_opt_out, -log_level, INFO, -baseport, 54321, -ip, 10.0.0.12, -log_dir, /Users/johnfroiland/Downloads/h2ologs]
Java availableProcessors: 8
Java heap totalMemory: 401.5 MB
Java heap maxMemory: 1.78 GB
Java version: Java 1.8.0_121 (from Oracle Corporation)
JVM launch parameters: [-Xmx2g, -XX:MaxPermSize=384m]
OS version: Mac OS X 10.12.3 (x86_64)
Machine physical memory: 16.00 GB
X-h2o-cluster-id: 1486748983111
User name: 'johnfroiland'
Opted out of sending usage metrics.
IPv6 stack selected: false
Network address/interface is not reachable in 150ms: /fe80:0:0:0:c028:bc11:bbf1:cde6%utun0/name:utun0 (utun0)
Network address/interface is not reachable in 150ms: /fe80:0:0:0:9422:2aff:fe47:f696%awdl0/name:awdl0 (awdl0)
Network address/interface is not reachable in 150ms: /2601:14d:8102:e700:c14c:52ec:b757:e4b/name:en0 (en0)
Network address/interface is not reachable in 150ms: /2601:14d:8102:e700:3599:1c5f:e1a8:424f/name:en0 (en0)
Network address/interface is not reachable in 150ms: /2601:14d:8102:e700:10e9:76c7:70c5:352f/name:en0 (en0)
Network address/interface is not reachable in 150ms: /fe80:0:0:0:4ef:bddd:caf6:1cca%en0/name:en0 (en0)
Network address/interface is not reachable in 150ms: /10.0.0.12/name:en0 (en0)
Possible IP Address: lo0 (lo0), fe80:0:0:0:0:0:0:1%lo0
Possible IP Address: lo0 (lo0), 0:0:0:0:0:0:0:1
Possible IP Address: lo0 (lo0), 127.0.0.1
IP address not found on this machine
17/02/10 12:49:45 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerStageCompleted(org.apache.spark.scheduler.StageInfo@3144077d)
17/02/10 12:49:45 ERROR LiveListenerBus: SparkListenerBus has already stopped! Dropping event SparkListenerJobEnd(1,1486748985842,JobFailed(org.apache.spark.SparkException: Job 1 cancelled because SparkContext was shut down))
Traceback (most recent call last):
  File "/Users/johnfroiland/Downloads/ChicagoCrimeDemo.py", line 93, in <module>
    h2oContext = H2OContext.getOrCreate(sc)
  File "/opt/spark/sparkling-water-2.0.4/py/build/dist/h2o_pysparkling_2.0-2.0.4-py2.7.egg/pysparkling/context.py", line 115, in getOrCreate

**Comment by mdymczyk** [comment]
@phroiland you're specifying the ip address `-ip 10.0.0.12` but it seems not to be reachable according to the log `Network address/interface is not reachable in 150ms: /10.0.0.12/name:en0 (en0)`.

**Comment by phroiland** [comment]
I'm not specifying any ip address. This is an H2O problem. I had go down from Spark 2.1 to 2.0 to even get this far. The book I'm referencing is copyright 2017 using Sparkling Water 1.6, and it's already out of date.

**Comment by mdymczyk** [comment]
@phroiland it still looks like either your machine is configured in a way that returns `10.0.0.12` as hostname, which is indeed one of the up interfaces, but seems to be unreachable.

**Comment by jakubhava** [comment]
Closing this issue as there hasn't been any response from @phroiland .The issue really seems like related to the network environment as it's even spark who is reporting the network issue

**Comment by mvervuurt** [comment]
The solution that helped me fix this problem was setting the environment variable export SPARK_LOCAL_IP='127.0.0.1'.
