### ISSUE TITLE
Sparkling-water via spark packages doesn't work with Spark 1.6.1

### ISSUE THREAD

**Issue by kuol** [h2oai/sparkling-water#189]
Hi, I'm on Hortonworks HDP 2.4 with Scala 2.10 and Spark 1.6.1. According to the README here, I should be able to use sparkling-water via spark packages by using

`spark-shell --packages ai.h2o:sparkling-water-core_2.10:1.6.8,ai.h2o:sparkling-water-examples_2.10:1.6.8`

However it seems two dependencies: `com.google.guava#guava;16.0.1!guava.jar(bundle)` and `com.google.code.findbugs#jsr305;3.0.0!jsr305.jar` are not found. Here's what I get in the terminal:

```:: problems summary ::
:::: WARNINGS
        [NOT FOUND  ] com.google.guava#guava;16.0.1!guava.jar(bundle) (1ms)
==== local-m2-cache: tried

  file:/root/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar

    [NOT FOUND  ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (1ms)

==== local-m2-cache: tried

  file:/root/.m2/repository/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar

    ::::::::::::::::::::::::::::::::::::::::::::::

    ::              FAILED DOWNLOADS            ::

    :: ^ see resolution messages for details  ^ ::

    ::::::::::::::::::::::::::::::::::::::::::::::

    :: com.google.guava#guava;16.0.1!guava.jar(bundle)

    :: com.google.code.findbugs#jsr305;3.0.0!jsr305.jar

    ::::::::::::::::::::::::::::::::::::::::::::::
```

I'm very new to this, any help is appreciated.

**Comment by jakubhava** [comment]
Please try cleaning your ivy and maven cache

**Comment by kuol** [comment]
@jakubhava Thank you! It is indeed how we made it work.

**Comment by jakubhava** [comment]
Awesome, good news!
