### ISSUE TITLE
2.0.5 not published to Maven Central

### ISSUE THREAD

**Issue by doctapp** [h2oai/sparkling-water#190]
Latest is 2.0.5 in github, but 2.0.4 is the latest published on Maven.
Thanks

**Comment by mmalohlava** [comment]
The artifacts should be available inMaven Central in a few minutes.

**Comment by doctapp** [comment]
Thanks for the quick reply, but I still don't see it on [Maven Central/ai.h2o](https://mvnrepository.com/artifact/ai.h2o/sparkling-water-core_2.11).
Did the location change?

**Comment by jakubhava** [comment]
Sparkling Water 2.0.5 is already available in Maven, closing this issue.

**Comment by mmalohlava** [comment]
Link to 2.0.5 (Scala 2.11): https://mvnrepository.com/artifact/ai.h2o/sparkling-water-core_2.11/2.0.5

**Comment by doctapp** [comment]
Thanks!
