### ISSUE TITLE
Typo in H2OTreeParams causing java.lang.NoSuchFieldException: max_rows

### ISSUE THREAD

**Issue by doctapp** [h2oai/sparkling-water#192]
Line https://github.com/h2oai/sparkling-water/blob/rel-2.0/ml/src/main/scala/org/apache/spark/ml/h2o/models/H2OGBM.scala#L112

should be:
 `  final val minRows = doubleParam("minRows") // Not doubleParam("maxRows")`

**Comment by doctapp** [comment]
Same for
`  final val nbinsCat = intParam("nbinsCats") // Not "nbinsCat"`

And this doesn't exist
`  final val initialScoreInterval = intParam("initialScoreInterval")`

**Comment by mdymczyk** [comment]
Thanks! This is already being fixed in PR #118 which also refactors the whole thing a bit.

**Comment by doctapp** [comment]
Thanks!
