### ISSUE TITLE
Q: How to preserve dataframe columns alongside predictions?

### ISSUE THREAD

**Issue by doctapp** [h2oai/sparkling-water#194]
I've trained a GBM model using the ML bindings. The problem is there's only a "predict" column when predicting. How can we preserve the original dataframe columns? I don't have any context to join back the predictions (I shouldn't need to join btw).
Thanks

**Comment by mmalohlava** [comment]
Hi @doctapp,

in H2O we guarantee order of rows - so if you have a frame with rows [A, B, C], then prediction frame will follow the same order [PA, PB, PC].

**Comment by mmalohlava** [comment]
If you have `H2OFrame DATA` and prediction frame `P` you can write
```scala
val dataFrame: H2OFrame = ...
val predFrame: H2OFrame = ...

dataAndPredFrame = dataFrame.add(predFrame)
```

**Comment by doctapp** [comment]
Thanks for the tip, but that's internal to the ML bindings... I guess that
would require hacking H2OModel.transform right?

**Comment by mmalohlava** [comment]
@doctapp are you using Scala API? in such case it is another expression after model predict call.
```scala
val predFrame = gbmModel.predict(dataFrame)
dataAndPredFrame = dataFrame.add(predFrame)
```

If you are using R/Python interface you need to use `cbind` to join both tables together.

**Comment by doctapp** [comment]
Worked! What I did was changes H2OModel.scala to make it consistent with
other ML packages:

  override def transform(dataset: Dataset[_]): DataFrame = {
    val frame: H2OFrame = h2oContext.asH2OFrame(dataset.toDF())
    val prediction = model.score(frame)
    // Preserve original dataset by appending predictions

h2oContext.asDataFrame(frame.add(prediction))(sqlContext).withColumnRenamed("predict",
"prediction")
  }

Thanks

**Comment by mmalohlava** [comment]
👍 nice!

**Comment by mmalohlava** [comment]
We can do that as optional parameter for ML package...
