### ISSUE TITLE
Cannot convert Spark DF into H2OFrame due to missing extended API endpoint

### ISSUE THREAD

**Issue by potasz** [h2oai/sparkling-water#1959]
Hi,

I have updated to the latest SparklingWater version 3.28.1.1-1-2.4 and H2OContext#asH2OFrame() started to fail due to missing /3/InitializeFrame endpoint on the remote H2O cluster.

The application runs on Yarn with a remote H2O cluster. In version 3.26 I could get the extended H2O driver that included this endpoint. I can see that in 3.28 it was removed but I cannot see how should the code be migrated.

The documentation still says to use  H2OContext#asH2OFrame() (http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/spark_h2o_conversions.html#converting-a-dataframe-into-an-h2oframe)

What is the new way to convert a Spark DF into H2O frame? Or how to get the extended H2O driver for version 3.28.1.1

Thank you.

The exception I get is:

`Exception in thread "main" ai.h2o.sparkling.backend.external.RestApiCommunicationException: External H2O node 10.200.128.30:54321 responded with
Status code: 404 : Not Found
Server error: {"__meta":{"schema_version":3,"schema_name":"H2OErrorV3","schema_type":"H2OError"},"timestamp":1584546486390,"error_url":"POST /3/InitializeFrame","msg":"\n\nERROR
MESSAGE:\n\nPOST /3/InitializeFrame not found\n\n","dev_msg":"\n\nERROR MESSAGE:\n\nPOST /3/InitializeFrame not found\n\n","http_status":404,"values":{},"exception_type":"water.e
xceptions.H2ONotFoundArgumentException","exception_msg":"\n\nERROR MESSAGE:\n\nPOST /3/InitializeFrame not found\n\n","stacktrace":["water.exceptions.H2ONotFoundArgumentException
: POST /3/InitializeFrame not found","    water.api.RequestServer.response404(RequestServer.java:743)","    water.api.RequestServer.serve(RequestServer.java:467)","    water.api.
RequestServer.doGeneric(RequestServer.java:301)","    water.api.RequestServer.doPost(RequestServer.java:227)","    javax.servlet.http.HttpServlet.service(HttpServlet.java:727)","
    javax.servlet.http.HttpServlet.service(HttpServlet.java:820)","    org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)","    org.eclipse.jetty.servlet.Serv
letHandler.doHandle(ServletHandler.java:501)","    org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)","    org.eclipse.jetty.servlet.ServletHandl
er.doScope(ServletHandler.java:427)","    org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)","    org.eclipse.jetty.server.handler.ScopedHandler.h
andle(ScopedHandler.java:135)","    org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)","    org.eclipse.jetty.server.handler.HandlerWrapper.ha
ndle(HandlerWrapper.java:116)","    water.webserver.jetty8.Jetty8ServerAdapter$LoginHandler.handle(Jetty8ServerAdapter.java:119)","    org.eclipse.jetty.server.handler.HandlerCol
lection.handle(HandlerCollection.java:154)","    org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)","    org.eclipse.jetty.server.Server.handle(Serv
er.java:366)","    org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)","    org.eclipse.jetty.server.BlockingHttpConnection.handleRequ
est(BlockingHttpConnection.java:53)","    org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:984)","    org.eclipse.jetty.server.AbstractHttpConn
ection$RequestHandler.content(AbstractHttpConnection.java:1045)","    org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)","    org.eclipse.jetty.http.HttpParser.par
seAvailable(HttpParser.java:236)","    org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)","    org.eclipse.jetty.server.bio.SocketConnector$C
onnectorEndPoint.run(SocketConnector.java:264)","    org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)","    org.eclipse.jetty.util.thread.QueuedTh
readPool$3.run(QueuedThreadPool.java:543)","    java.lang.Thread.run(Thread.java:748)"]}
        at ai.h2o.sparkling.backend.external.RestCommunication$class.checkResponseCode(RestCommunication.scala:240)
        at ai.h2o.sparkling.frame.H2OFrame$.checkResponseCode(H2OFrame.scala:79)
        at ai.h2o.sparkling.backend.external.RestCommunication$class.readURLContent(RestCommunication.scala:219)
        at ai.h2o.sparkling.frame.H2OFrame$.readURLContent(H2OFrame.scala:79)
        at ai.h2o.sparkling.backend.external.RestCommunication$class.request(RestCommunication.scala:115)
        at ai.h2o.sparkling.frame.H2OFrame$.request(H2OFrame.scala:79)
        at ai.h2o.sparkling.backend.external.RestCommunication$class.update(RestCommunication.scala:73)
        at ai.h2o.sparkling.frame.H2OFrame$.update(H2OFrame.scala:79)
        at ai.h2o.sparkling.frame.H2OFrame$.initializeFrame(H2OFrame.scala:131)
        at ai.h2o.sparkling.backend.external.ExternalBackendConverter$.convert(ExternalBackendConverter.scala:55)
        at ai.h2o.sparkling.backend.converters.SparkDataFrameConverter$.toH2OFrameKeyString(SparkDataFrameConverter.scala:108)
        at ai.h2o.sparkling.backend.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:76)
        at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:234)
        at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:234)
        at org.apache.spark.h2o.utils.H2OContextUtils$class.withConversionDebugPrints(H2OContextUtils.scala:78)
        at org.apache.spark.h2o.H2OContext.withConversionDebugPrints(H2OContext.scala:64)
        at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:234)`

**Comment by mn-mikke** [comment]
Hi @potasz ,
to fix your problem you need to run H2O 3.28.1.1. The extended H2O driver jar was splitted into the jars. In manual mode, now you will need to specify a regular H2O driver jar and a jar with extensions. For more details, see [documentation](http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/deployment/backends.html#manual-mode-of-external-backend-on-hadoop).

For more breaking changes, please see the [migration guide](http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/migration_guide.html#from-3-28-0-to-3-28-1).

Let me know if you hit any problem.

**Comment by potasz** [comment]
Thank you @mn-mikke for the quick answer. I was sure I missed something obvious but couldn't spot this in the doc. Thank you for the pointer.  Hopefully this will work.

**Comment by potasz** [comment]
Hi. I have managed to make it work. The key was indeed to the add the SparklingWater extended jar to the `hadoop` command for the H2O cluster. It was just a bit confusing because earlier it was `h2o_driver_extended.jar` so it was clear it needs to be used for the H2O server. Now there are `sw-assembly` and `sw-assembly-extended` jars. The first is needed for the client and the second for the H2O backend. 

Maybe the the extended JAR should be named differently? Something like `sw_extended_backend.jar` similarly to the `-sw_ext_backend` hadoop option?

Nevertheless, thank you for your help. I guess this ticket can be closed.

**Comment by jakubhava** [comment]
The reason why we name the jar as `sw-extensions` is that it really just contains extensions to regular h2o driver jar. We do not ship extended jar anymore in case of Sparkling Water.

Thank you for the report!
