### ISSUE TITLE
Does h2o flow support chinese dataset?

### ISSUE THREAD

**Issue by taoshi006** [h2oai/sparkling-water#199]
I want to know dose h2o flow support chinese charset  utf8 or  gb2312 gbk?

**Comment by mmalohlava** [comment]
I would say yes, however, @micahstubbs should confirm.

**Comment by micahstubbs** [comment]
@taoshi006 is there a dataset that you can share for each of these charsets?  I'd like to test and find out.

**Comment by taoshi006** [comment]
sure.
[test.zip](https://github.com/h2oai/sparkling-water/files/826344/test.zip)

**Comment by taoshi006** [comment]
thank you for your reply.

**Comment by taoshi006** [comment]
![image](https://cloud.githubusercontent.com/assets/14683560/23685763/dee6f540-03e0-11e7-8263-ba704c6b5930.png)
when i use this dataset with charset utf8 , the h2o flow show chinese garbled.

**Comment by taoshi006** [comment]
![image](https://cloud.githubusercontent.com/assets/14683560/23685928/a22feb7e-03e1-11e7-8929-a834a99a7287.png)

**Comment by vpatryshev** [comment]
My suggestion is to always use utf8 at least with the backend operations.

Thanks,
-Vlad

**Comment by taoshi006** [comment]
my sparkling-water version is  sparkling-water-1.6.8

**Comment by taoshi006** [comment]
@micahstubbs  could you tell me ,the result you tested?

**Comment by micahstubbs** [comment]
@lo5 can you take a look at this one?

**Comment by jakubhava** [comment]
@lo5 @micahstubbs @taoshi006 I created JIRA https://0xdata.atlassian.net/browse/PUBDEV-4320 which can be used to track the state of the issue.
