### ISSUE TITLE
java.lang.IllegalArgumentException: Operation not allowed on string vector.

### ISSUE THREAD

**Issue by rahuljain788** [h2oai/sparkling-water#202]
// Split table
val keys = Array[String]("train.hex", "valid.hex")
val ratios = Array[Double](0.8)
val frs = H2OFrameSupport.split(table, keys, ratios)
val (train, valid) = (frs(0), frs(1))
table.delete()

// Build a model
val dlModel = buildDLModel(train, valid)

executing last line gives "java.lang.IllegalArgumentException: Operation not allowed on string vector." not sure what happened wrong

**Comment by mmalohlava** [comment]
Hi,

you need to convert String columns explicitly to categorical columns.
you can use: 
```
fr.replace(fr.find("target"), fr.vec("target").toCategoricalVec).remove()
water.DKV.put(fr)
```

or alias
```
fr.colToEnum(Array("target"))
```
