### ISSUE TITLE
How to export mojo in spark scala

### ISSUE THREAD

**Issue by joscani** [h2oai/sparkling-water#2042]
Hi @jakubhava  again. 
I have mi model training in EMR cluster with 
```scala
val estimator = new H2OXGBoost().
      setLabelCol("target_residencial").
      setNtrees(3).
      setMaxDepth(3)
val model = estimator.fit(trainingDF)
```  
But I don't know how to export model to mojo . I'm trying
```scala
val destination = "file:///home/jcanadar/rosetta_train_models/modelos/jj.zip"
model.write.overwrite().save(destination)
```

But I get `Caused by: java.io.IOException: Mkdirs failed to create file:` error. I'm a bit desperate, All things run correctly with old hex.tree.xgboost._  H2O algorithms, but I know you plan to deprecate this in sparkling-water, and maybe for good reasons. 
I need to pass to my engineer a fully functional scala script to train model and save mojo. They will write a complete gradle project to deploy train an prediction model in our production environment as well than other gradle project only for prediction using mojo, based in my old code https://github.com/joscani/predict_binary_h2o 
Thanks for your fantastic work.

**Comment by jakubhava** [comment]
Hi @joscani,
 `write.overwrite().save` are Spark methods and this simply means that Spark does not have permissions to save the files. Can you check the permissions?

**Comment by joscani** [comment]
Thanks @jakubhava , I'll talk with the sysadmin of our EMR, and try to write model in s3 directly.

**Comment by joscani** [comment]
@jakubhava  I finally export mojo model using s3 like that.

```scala
val destination = "s3a://mybucket/mymodel"
model.write.overwrite().save(destination)
```

Any way, how can I get gainlift table in the new api ?

**Comment by jakubhava** [comment]
@joscani that is currently not exposed. Can you please create JIRA on our system https://0xdata.atlassian.net/secure/Dashboard.jspa?
