### ISSUE TITLE
Install fails with PySpark + Spark 2

### ISSUE THREAD

**Issue by rgbkrk** [h2oai/sparkling-water#206]
```
$ pip install h2o_pysparkling_2.0
Collecting h2o_pysparkling_2.0
  Using cached h2o_pysparkling_2.0-2.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/tmp/pip-build-eZom_o/h2o-pysparkling-2.0/setup.py", line 13, in <module>
        with open(path.join(here, 'build', 'version.txt'), encoding='utf-8') as f:
      File "/usr/lib/python2.7/codecs.py", line 878, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: '/data/tmp/pip-build-eZom_o/h2o-pysparkling-2.0/build/version.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /data/tmp/pip-build-eZom_o/h2o-pysparkling-2.0/
```

**Comment by mmalohlava** [comment]
@rgbkrk thanks for report, this will be fixed in the release next week. However, in meantime you can always use binary version from h2o.ai/download page.

**Comment by rgbkrk** [comment]
Thanks!

**Comment by szxunchao** [comment]
@mmalohlava Hi, I was wondering if this issue is solved. I tried h2o-pysparkling-2.1 and encounter exactly the same problem.

**Comment by jakehockey10** [comment]
Oh darn it.  I was about to update my HDInsight cluster to 2.1 so I could get this fixed.  This isn't good...

**Comment by jakehockey10** [comment]
I'm trying to use this in a Spark cluster up in Azure via HDInsight.  I'm running into the same issue: https://github.com/h2oai/sparkling-water/issues/229

**Comment by jakehockey10** [comment]
@mmalohlava when you suggest using a binary version of `sparkling-water`, do I still need to match the version of Spark I'm using?  In other words, do I use the 2.0 binary version?  Does this binary version have the fix you mention, or is that only going into 2.1?  Thanks.

**Comment by jakehockey10** [comment]
@mmalohlava I tried using the 2.0.6 binary from the download page you mentioned and I get this in the output: 
```
You are trying to use Sparkling Water built for Spark 2.0.1, but your $SPARK_HOME(=) property points to Spark of version Multiple versions of Spark are installed but SPARK_MAJOR_VERSION is not set
1.6. Please ensure correct Spark is provided and re-run Sparkling Water.
```
But if I do this in my Jupyter notebook: `print spark.version`, I see `2.0.2.2.5.4.0-121`
and if I do: 
``` bash
%%bash
echo $SPARK_HOME
```
I see `/usr/hdp/current/spark2-client`
