### ISSUE TITLE
Save/Load H2O Models in spark

### ISSUE THREAD

**Issue by lalitagarw** [h2oai/sparkling-water#207]
Hi,

I am trying to save and load an H2O model using info provided in this issue: https://github.com/h2oai/sparkling-water/issues/14

However, I keep getting error at **import water.serial.ObjectTreeBinarySerializer** saying **_serial is not found_**. Is the ObjectTreeBinarySerializer removed? Or is there a different way to do save and load model in spark.

I am using latest version of sparkling water(spark 2.1) and h2o core.

**Comment by ganeshkrishnan1** [comment]
Don't use the water.serial 

Use this to write the model to disk

```
val dl = new DeepLearning(dlParams)
    val dlModel = dl.trainModel.get
    //save the model
    ModelSerializationSupport.exportH2OModel(dlModel, new File("/data/invdeeplearning.bin").toURI)
```


and this to read the model from disk

` dlModel = ModelSerializationSupport.loadH2OModel(new File("/data/deeplearning.bin").toURI)`

**Comment by mmalohlava** [comment]
Thx for answer!
