### ISSUE TITLE
Mojo predict probabilities in sparkling water

### ISSUE THREAD

**Issue by joscani** [h2oai/sparkling-water#2073]
Hi, again. 
I'm trained my model and save it in s3, I'm using the latest stable sparkling water version. But when I want to load mojo I can only predict the prediction column, not the po, p1 columns. However, if I import the mojo model in h2oflow (with sparkling water) I can predict and get the probabilities.

```scala
val settings = H2OMOJOSettings(convertUnknownCategoricalLevelsToNa = true, convertInvalidNumbersToNa = true)

val model= H2OMOJOModel.createFromMojo("s3a://bucket/mymodel.zip", settings)
val diciembre_df = spark.table("mytable")

val predicciones = model.transform(diciembre_df)
predicciones.select("prediction").show()
+----------+
|prediction|
+----------+
|         0|
|         0|
|         0|
|         0|
|         1|


```

But I don't find how to get p0 and p1 probabilities. My model is a xgboost model with binomial distribution

**Comment by jakubhava** [comment]
Hi @joscani, good question!

We have changed the API to be again more Spark-friendly which might be confusing at first. Currently `prediction` column always returns the real prediction. In case of classification, the predicted label and in case regression the predicted number.

If you would like to obtain also probabilities or mode details coming from predictions, you need to pass `withDetailedPredictionCol = true` to `H2OMOJOSettings`. This will create another column named `detailed_prediction` which also contains field `probabilities` and other fields as well, such as SHAP values etc. I agree this needs to be documented better. I will create a JIRA to document this on this page https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/deployment/load_mojo.html

**Comment by jakubhava** [comment]
https://0xdata.atlassian.net/browse/SW-2194

**Comment by joscani** [comment]
Great. Thanks @jakubhava

**Comment by jakubhava** [comment]
https://github.com/h2oai/sparkling-water/pull/2079/files documentation update will be in next release
