### ISSUE TITLE
Cannot start h2O context on databricks cluster

### ISSUE THREAD

**Issue by AnishDeepak** [h2oai/sparkling-water#2074]
#this is the code i used 2 months ago, It worked. but now its getting error.
from pysparkling import *
from pyspark.sql import SparkSession
import h2o
spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
h2oConf = H2OConf(spark).set("spark.ui.enabled", "false")
hc = H2OContext.getOrCreate(conf=h2oConf)

#spark run time version 5.5LTS
#this is the error i am getting
![databricks_error](https://user-images.githubusercontent.com/59416407/80942170-c043c600-8e01-11ea-89b9-d4d6d214b914.PNG)
 #after removing spark argument also getting this error
![Capture](https://user-images.githubusercontent.com/59416407/80942291-0bf66f80-8e02-11ea-9756-bd2a6dd3a0f4.PNG)

#these are the dependencies i have installed
h2o_pysparkling_2.4
requests
tabulate
future
colorama>=0.3.8

**Comment by jakubhava** [comment]
Hi @AnishDeepak it seems like you are using our latest version which has regression bug on DBC. We are 1 or 2 days from a new release 3.30.0.2 which has this fixes plus brings additional benefits. Sorry for troubles.

**Comment by AnishDeepak** [comment]
So, will it be run if i use the same code after 2 days.

**Comment by jakubhava** [comment]
Yes, I believe so

**Comment by AnishDeepak** [comment]
Ok, I will check after 3 days and let you know.
Thank you for your immediate  reply.

**Comment by jakubhava** [comment]
New release is out, please give it a try

**Comment by AnishDeepak** [comment]
Yeah its working, thank you soo much.

**Comment by jakubhava** [comment]
Great!
