### ISSUE TITLE
Custom metric implementation Scala

### ISSUE THREAD

**Issue by palbha** [h2oai/sparkling-water#2096]
Hi all, 

I was trying H2o models on spark(2.4.5) in scala.
Can someone share details around creating a custom metric function to calculate relative error or is there Mean absolute percentage error directly available in models like GBM GLM in spark(Scala).
Even the documentation around Sparkling water implementation in scala is limited .

TIA

**Comment by jakubhava** [comment]
Hi @palbha , currently, custom metric function is only available via Python client. The Scala implementation is still missing. I have created JIRA for this request https://0xdata.atlassian.net/browse/SW-2221.

I don't think we have MAPE exposed on our algorithms but I will ask H2O-3 development and let you know

**Comment by jakubhava** [comment]
I have checked with H2O-3 developers and we do not expose MAPE metrics. We will implement the custom metric in Scala, please use the JIRA to track the issue.

**Comment by palbha** [comment]
Thanks @jakubhava .Please share if there is any comprehensiver tutorial/documentation of H2O sparkling water scala , since most of the documentation are around python and R.
