### ISSUE TITLE
Calibrate Model in new api

### ISSUE THREAD

**Issue by joscani** [h2oai/sparkling-water#2113]
Hi. 
I'm using sparkling-water-3.30.0.2-1-2.3 with new api spark friendly and I don't find how to specify calibration frame. 

```scala
val piloto = raw_piloto.select(featCols: _*)
  
val calib_df = spark.table("default.calib_table").
  filter($"mes_campana" === "201911" )

val Array(trainingDF, validDF, testingDF) = piloto.randomSplit(Array(0.8, 0.1, 0.1))


val estimator = new H2OXGBoost().
      setLabelCol("target_residencial").
      setNtrees(20).
      setMaxDepth(3).
      setGamma(15).
      setRegAlpha(6).
      setRegLambda(6).
      setColSampleRate(0.8).
      setSampleRate(0.8).
      setMinChildWeight(20).
      setNfolds(3).
      setSeed(42)

val model = estimator.fit(trainingDF)
``` 
Where can I specify calib_df as a calibration frame? I don't find this in doc

**Comment by jakubhava** [comment]
@joscani

This is currently not possible, but @mn-mikke is working on a solution https://github.com/h2oai/sparkling-water/pull/2065

Previously we have defined the parameters manually and it happened that we forgot to expose some. By generating the parameters we will be sure that all options, such as calibration frame is also exposed.

We will let you know once it's ready

**Comment by joscani** [comment]
Wow. 
Thanks for your quick answers. Meanwhile I'll use the old api,  save mojo and predict in production using spark udf using h2o-genmodel-ext-xgboost  in my spark app.

**Comment by jakubhava** [comment]
Yup. We are not removing the old API any time soon after we are sure we can do 100% with the new API

Thanks for trying this out!
