### ISSUE TITLE
setSparkVersionCheckDisabled() no work

### ISSUE THREAD

**Issue by shaoweijob** [h2oai/sparkling-water#2171]
ai.h2o:sparkling-water-package_2.11:3.28.0.1-1-2.4

scala 2.11.8
spark 2.2

   ```
 val spark = SparkSession.builder.appName("auto train").master("local[2]").enableHiveSupport()
    import org.apache.spark.h2o._
    val conf = new H2OConf(spark).setInternalClusterMode().setSparkVersionCheckDisabled()
    val hc = H2OContext.getOrCreate(spark, conf)
```
In Doc:
setSparkVersionCheckDisabled() --> enables check if run-time Spark version matches build time Spark version.

But,  I found that there is no logic to judge this configuration after I read the source code of H2OContent.  
![image](https://user-images.githubusercontent.com/18146142/84143703-9bd6ab80-aa89-11ea-90e7-0c1cefbcedaa.png)

**Comment by jakubhava** [comment]
Hi @shaoweijob.

I see that you are mentioning Spark 2.2 but I see that you are using ai.h2o:sparkling-water-package_2.11:3.28.0.1-1-2.4 which is for Spark 2.4. You need to have the corresponding sparkling water version for your spark.

The option you are referring to is option which 99.99% of users should never change as incompatible Spark And Sparkling Water won't work together.

But regarding your question -> You have high-lighten two unrelated code pieces. One is for checking the Spark version and one is checking whether UI is enabled -> the second call doesn't have anything to do with version.  The method `verifySparkVersion` truly checks the Spark Runtime version.

Hope it helps

Kuba
