### ISSUE TITLE
Setting impurity for tree based algorithms

### ISSUE THREAD

**Issue by kmullapudi-11** [h2oai/sparkling-water#2194]
Hi,
Is there a way to set the impurity to 'entropy' or 'gini' while using tree based algorithms? If not, will it ever be supported in a future release? Also, what is the impurity currently being used by default?

**Comment by mn-mikke** [comment]
cc @michalkurka

**Comment by michalkurka** [comment]
In H2O's GBM & DRF the individual trees are built as regression trees with variance as a measure of impurity.

**Comment by kmullapudi-11** [comment]
@michalkurka Thank you for your response. As a follow-up question, are there plans to support _entropy_ and _gini_ in the future?

**Comment by kmullapudi-11** [comment]
Also, I just wanted to check when the algorithms supported by H2O will be available in Sparkling Water (is there a link where I can see development progress?). I particularly want to enquire about when Naive Bayes, Support Vector Machines, Principal Component Analysis, and Isolation Forest will be supported.

**Comment by jakubhava** [comment]
@kmullapudi-11 If you are using Python or R then you can use the algorithms in Sparkling Water right way via H2O Python or via H2O R client.

If you are a Scala user, then you can either use the H2O Java API (but we are deprecating this approach) or use Sparkling Water algorithm wrappers. At this moment we expose GBM, GLM, H2ODRF, DeepLearning, KMeans, XGBoost, AutoML and GridSearch. We definitelly want to make sure that the algorithms you mentioned are exposed in SW as well

**Comment by jakubhava** [comment]
Hi @kmullapudi-11, I'm closing this issue for now. If you have additional questions feel free to re-open this issue or create a new one.

Thank you!
