### ISSUE TITLE
Stopping parameters in H2OXGBoost - missing

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#2199]
Hi, is it possible to add these parameters (**stoppingMetric**, **stoppingRounds**, **stoppingTolerance**) to **H2OXGBoost** algorithm?

Now I am getting following error: `AttributeError: 'H2OXGBoost' object has no attribute 'stoppingMetric'`

_Running PySparkling (3.26.8-2.4) on YARN._

**Comment by jakubhava** [comment]
Hi @dataspekulant we are actively working on making sure we support all parameters H2O has to offer in Sparkling Water. Namely, these parameters were added in release 3.28.0.2, see https://0xdata.atlassian.net/browse/SW-1802

Kuba
