### ISSUE TITLE
updating saved models with new data

### ISSUE THREAD

**Issue by ThakurRajAnand** [h2oai/sparkling-water#22]
Can some one help me to understand how can we update saved H2O GLM/GBM model.

**Comment by mmalohlava** [comment]
Hi @ThakurRajAnand 

how did you save the models? As POJO? Or in binary form?

**Comment by ThakurRajAnand** [comment]
I haven't saved the model till now. I am working on creating something glm we have in R. Pipeline in R looks like below

model <- glm(y~.,data=train)
save(model,file="model.rda")
load(model.rda)
model_update <- update(model,".~.",data=train_new)

**Comment by mmalohlava** [comment]
So far, we do not have ability to update existing model (i am not pretty sure what would you expect from update).

However, you can continue model training - just configure checkpoint parameter .

**Comment by ThakurRajAnand** [comment]
From update I mean - If I made a GLM model using using past six month data and using it for production. Every month new data is going to come and I want existing model to be updated with more data (I don't want to train the model again). Using thsi whole process model will keep updating itself month on month on new data.

**Comment by mmalohlava** [comment]
Hi @ThakurRajAnand,

you can use checkpoint feature: you can continue model training with new data.
See http://h2o-release.s3.amazonaws.com/h2o/rel-tibshirani/8/docs-website/h2o-docs/index.html#%E2%80%A6%20Building%20Models (look for parameter called `checkpoint`)

For GLM it is not worth it (it is better re-run full data), but for RandomForest/GBM/or DeepLearning the continuation of modeling is available.

**Comment by ThakurRajAnand** [comment]
Thanks

**Comment by MadMan0708** [comment]
Hi @ThakurRajAnand,
 It looks like @mmalohlava answered your question so I'm closing this issue for now. If you have other problems/questions in the future, feel free to reopen this or open a new issue!

Kuba

**Comment by ottok92** [comment]
Any chance support is added for XGBoost?
I mean, are there any blockers documented? I can pick up PR.
