### ISSUE TITLE
Speed-up training of H2OGradientBoosting estimator

### ISSUE THREAD

**Issue by alexHeu** [h2oai/sparkling-water#2201]
Hi,

in my current project I am using H2O together with sparkling-water on Databricks to train a H2OGradientBoosting estimator on a dataset with roughly 130M rows and 80 columns.
I am using 2 Azure D64s_v3 instances that each have 64 cores and 256GB memory. 

Training is working well, however it takes around 5.5 hours to train 600 trees. If possible, we would like to improve the training runtime.

Do you have any suggestions on how to speed up the training process apart from adding more nodes?
Im open to switching to another algorithm like XGBoost. Is GPU support for XGBoost also available in sparkling-water?

Thanks and regards
Alexander

**Comment by jakubhava** [comment]
@honzasterba -> could you please have a look?

**Comment by honzasterba** [comment]
Hi Alex,
do you really need 600 trees? I would suggest configuring GBM with early stopping, you might find out that the benefit of more trees is negligible.
XGBoost does support GPU but only when running on single node, however you might get a performance benefit even from its CPU accelerated version.
Also I am not familiar with Databricks but I would also make sure that all the memory/cores are being utilised by the cluster.

**Comment by jakubhava** [comment]
Thanks @honzasterba fort the reply! I will close this issue for now @alexHeu, but feel free to re-open or open a new one if you have another question. thanks!
