### ISSUE TITLE
cross validation of sparkling water in spark

### ISSUE THREAD

**Issue by jayden526** [h2oai/sparkling-water#2217]
Hi,
I am new to this tool, could you please help me with a few questions?
I am training a logistic regression with thousands of features using ML lib in spark, while it has poor efficiency, especially with cross-validation. So I am looking to try sparkling water in spark.
Does the sparkling water code works with existing spark scala code in the pipeline, I try to only replace existing model training part with sparkling water code (GLM). It will be great if they work together and will save me a lot of work.
Thanks a lot!

**Comment by mn-mikke** [comment]
Hi @jayden526,
Yes, Sparkling Water exposes some of the H2O-3 algorithms as Spark pipeline stages. Currently exposed algorithms as spark pipeline stages are GLM, GBM, DRF, XGBoost, DeepLearning, Automl, Kmeans. [Here](http://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/ml/sw_drf.html) is an tutorial how to use DRF algorithm. Api of GLM is similar, just differs in a specific parametrs.  The next major version of Sparkling Water (coming in September) will expose more H2O-3 algorithms as Spark Pipeline stages. The long term goal is to expose all of them.

**Comment by jayden526** [comment]
@mn-mikke , Thanks a lot for explaining, now I am running examples in scala and hope it works.

**Comment by mn-mikke** [comment]
@jayden526 I'm closing the issue for now. If you have any further questions, you can reopen it or create another one.
