### ISSUE TITLE
Invalid file in examples

### ISSUE THREAD

**Issue by ganeshkrishnan1** [h2oai/sparkling-water#222]
The example file uses a hardcoded file that is not in the repository

https://github.com/h2oai/sparkling-water/blob/master/examples/src/main/scala/org/apache/spark/examples/h2o/AmazonFineFood.scala

The file path in example file is ""/Users/michal/Tmp/amazon-fine-foods/Reviews.csv""

Please move this file to repo and put it as relative path

**Comment by jakubhava** [comment]
@ganeshkrishnan1 Good catch, I will file up a JIRA for this issue and ensure it's fixed. Thanks for reporting!

**Comment by mmalohlava** [comment]
Note: we cannot bundle the file in repo, pleas keep it on mind

**Comment by ganeshkrishnan1** [comment]
Why not put the file in the resources folder? If it's too big you can drop a subset of it there. 
Without the csv file, the example does not justify.

**Comment by mmalohlava** [comment]
Explanation is simple - you need to download that manually, since it is Kaggle dataset and we cannot distribute it.

**Comment by ganeshkrishnan1** [comment]
Ah I see. I didn't know that was a Kaggle dataset. Its fair enough to leave the code as-is then. I can download from Kaggle and modify the path on my system.

**Comment by jakubhava** [comment]
@mmalohlava thanks for explanation,  we can put this info to the script itself
