### ISSUE TITLE
as_h2o_frame() function could not be found!

### ISSUE THREAD

**Issue by SieSiongWong** [h2oai/sparkling-water#2221]
Hi, 

I'm facing the issue of getting the as_h2o_frame() function. I have installed the **rsparkling_3.30.0.6-1-2.4**, **h2o_3.30.0.1 , sparklyr_1.3.1**   and **spark 2.4.3**.  

Note that I can connect to spark and would like to convert the spark dataframe to h2o dataframe for using h2o machine learning algorithms.

Can someone help how to resolve this issue?

Thanks,
Siong

**Comment by jakubhava** [comment]
@SieSiongWong Please read our documentation https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/rsparkling.html. In this version, there is no longer method `as_h2o_frame` but instead `asH2OFrame` on `H2OContext` instance

**Comment by SieSiongWong** [comment]
@jakubhava 

Thanks for the information.
