### ISSUE TITLE
No man pages found in package  'rsparkling' !

### ISSUE THREAD

**Issue by SieSiongWong** [h2oai/sparkling-water#2222]
Hi,

I try to follow what is given in this link to install H2O and rsparkling: http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/rsparkling.html, successfully getting H2O installed but for rsparkling I'm getting the: No man pages found in package  'rsparkling' . Below is the info.

trying URL 'http://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.30.0.6-1-2.4/R/src/contrib/rsparkling_3.30.0.6-1-2.4.tar.gz'
Content type 'application/x-tar' length 116101431 bytes (110.7 MB)
downloaded 110.7 MB

* installing *source* package 'rsparkling' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Found more than one class "H2OMOJOModelBase" in cache; using the first, from namespace 'rsparkling'
Also defined by '.GlobalEnv'
** help
No man pages found in package  'rsparkling' 
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error: package or namespace load failed for 'rsparkling' in library.dynam(lib, package, package.lib):
 DLL 'htmltools' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/Gang Zhang/Documents/R/win-library/3.6/rsparkling'
Warning in install.packages :
  installation of package ‘rsparkling’ had non-zero exit status

**Comment by jakubhava** [comment]
I just verified locally and I was able to install the version ok. 

This error seems relevant `DLL 'htmltools' not found: maybe not installed for this architecture?` Please install htmltools package first

**Comment by SieSiongWong** [comment]
@jakubhava 

I checked I have the 'htmltools' package installed. Should it be loaded before doing rsparkling installation?

**Comment by jakubhava** [comment]
It is not required to load it. It seems like some specific environmental problem. Can you try reinstall the htmltools library?

**Comment by SieSiongWong** [comment]
@jakubhava 

Sure, I will do that. Thank you so much for your quick response.
