### ISSUE TITLE
Kerberos: keytab instead of password

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#2264]
According to the guidelines mentioned in this link: [http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/kerberos_auth.html](http://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/kerberos_auth.html) you have to provide password explicitly during initialization of H2OContext.

This way it is working with no issues.

But is there way to use kerberos **keytab file** instead of **password** in code?

**Comment by jakubhava** [comment]
Yup, I hope this document helps https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/kerberized_cluster.html

**Comment by jakubhava** [comment]
This document demonstrates how to enable Sparkling Water on kerberized cluster https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/tutorials/kerberized_cluster.html but it is a bit different then authentification. Currently, password is required for authentification
