### ISSUE TITLE
XGBoost not found; Cannot initialize XGBoost backend

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#2289]
**Trying to use XGBoost in Sparkling Water but getting following error:**

Py4JJavaError: An error occurred while calling o699.fit.
: ai.h2o.sparkling.backend.exceptions.RestApiCommunicationException: H2O node 10.245.54.13:54321 responded with
Status code: 404 : Not Found
Server error: {"__meta": {"schema_version":3,"schema_name":"H2OErrorV3","schema_type":"H2OError"},"timestamp":1597243172772,"error_url":"POST /99/Grid/xgboost","msg":"\n\nERROR MESSAGE:\n\nPOST /99/Grid/**xgboost not found**\n\n"
...
...

**According to H2O logs there is problem to initialize XGBoost backend:**

07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO: **Cannot initialize XGBoost backend**! Xgboost (enabled GPUs) needs: 
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO:   - CUDA 8.0
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO: XGboost (minimal version) needs: 
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO:   - GCC 4.7+
07-28 14:02:38.516 127.0.0.1:54321       18034  main      INFO: For more details, run in debug mode: `java -Dlog4j.configuration=file:///tmp/log4j.properties -jar h2o.jar`
07-28 14:02:38.569 127.0.0.1:54321       18034  main      INFO: ----- H2O started  -----
07-28 14:02:38.569 127.0.0.1:54321       18034  main      INFO: Build git branch: rel-zahradnik
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build git hash: 42bc323d9860bac8b25e904eec22b9cf827abcb5
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build git describe: jenkins-3.30.0.6-24-g42bc323
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build project version: 3.30.0.7
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Build age: 6 days
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Built by: 'jenkins'
07-28 14:02:38.570 127.0.0.1:54321       18034  main      INFO: Built on: '2020-07-21 17:20:25'
...
...

Do you have any idea what should be the problem here?
Thanks!

_Running PySparkling (3.30.0.7-1-2.4) on YARN._

**Comment by mn-mikke** [comment]
@dataspekulant Can you share more details about your environment? What operating system do you use for your cluster and what version of GCC is installed there?

**Comment by michalkurka** [comment]
cc: @michalkurka 

we will also update the error message to be a bit more clear: https://0xdata.atlassian.net/browse/PUBDEV-7724

**Comment by dataspekulant** [comment]
**OS:** Red Hat Enterprise Linux Server release 6.10 (Santiago)
**GCC:** gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)

**Comment by michalkurka** [comment]
@dataspekulant RedHat 6.x is no longer supported with current XGBoost version

@mn-mikke pointed me to another issue https://github.com/h2oai/sparkling-water/issues/2290 - it seems like you upgraded to 3.30.0.7, this version bundles XGBoost based on 1.0 distribution; with this version, we can no longer support your OS.

XGBoost 1.0 brings performance enhancement, please consider upgrading your OS

**Comment by dataspekulant** [comment]
Thank you for the answer.
