### ISSUE TITLE
model.transform - detailed prediction column missing

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#2290]
After upgrade of Sparkling Water from version **3.26.8-2.4** to **3.30.0.7-1-2.4** the type of **PREDICTION** column changed from **struct** which contains detailed probabilities to simple **string** with 0/1 values only.

Is there way how to get detailed probabilities after model.transform run?

_Running PySparkling (3.30.0.7-1-2.4) on YARN._

**Comment by mn-mikke** [comment]
Yes, you can set the parameter `withDetailedPredictionCol` to `true` on any algorithm or [`H2OMOJOSettings`](https://h2o-release.s3.amazonaws.com/sparkling-water/spark-2.4/3.30.0.7-1-2.4/doc/deployment/load_mojo.html?highlight=mojo#customizing-the-mojo-settings) and use the `detailed_prediction` column instead.

Note: From the version `3.30.1.1-1`, the `detailed_prediction` column is always enabled.

**Comment by dataspekulant** [comment]
Thank you for the answer.
