### ISSUE TITLE
installed h2o_pysparkling_2.4 but unable to create h2o contenxt

### ISSUE THREAD

**Issue by p9anand** [h2oai/sparkling-water#2292]
Below is the details of error:
spark = create_sparksession('***', num_exec=1, app_name="****", exec_memory="4g",
                                          exec_image="****",
                                          ui_port=5555)
from pysparkling import *
h2oContext = H2OContext.getOrCreate()

`---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-11-5f20a6db1cc7> in <module>
----> 1 h2oContext = H2OContext.getOrCreate()

/usr/local/lib/python3.6/site-packages/ai/h2o/sparkling/H2OContext.py in getOrCreate(spark, conf)
     87             selected_conf = conf
     88         else:
---> 89             selected_conf = H2OConf()
     90         selected_conf.set("spark.ext.h2o.rest.api.based.client", "true")
     91 

/usr/local/lib/python3.6/site-packages/ai/h2o/sparkling/H2OConf.py in __init__(self, spark)
     33             Initializer.load_sparkling_jar()
     34             _jvm = SparkSession._instantiatedSession.sparkContext._jvm
---> 35             self._jconf = _jvm.org.apache.spark.h2o.H2OConf()
     36         except:
     37             raise

/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1523         answer = self._gateway_client.send_command(command)
   1524         return_value = get_return_value(
-> 1525             answer, self._gateway_client, None, self._fqn)
   1526 
   1527         for temp_arg in temp_args:

/opt/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling None.org.apache.spark.h2o.H2OConf.
: java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class
	at ai.h2o.sparkling.utils.SparkSessionUtils$.<init>(SparkSessionUtils.scala:32)
	at ai.h2o.sparkling.utils.SparkSessionUtils$.<clinit>(SparkSessionUtils.scala)
	at org.apache.spark.h2o.H2OConf.<init>(H2OConf.scala:55)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more`

spark context:

SparkSession - in-memory

SparkContext

Spark UI

Version
    v2.4.4
Master
    k8s://https://kubernetes.default.svc.cluster.local:443
AppName
    customer-churn

enviroment variabel:

{'KUBERNETES_PORT': '***',
 'KUBERNETES_SERVICE_PORT': '443',
 'PRAKASH_INSIGHTS_SERVICE_HOST': '****,
 'HOSTNAME': 'prakash-insights-0',
 'PYTHON_PIP_VERSION': '19.1.1',
 'HOME': '/root',
 'PRAKASH_INSIGHTS_SERVICE_PORT': '80',
 'PRAKASH_INSIGHTS_PORT': '****',
 'GPG_KEY': '<hidden>',
 'PRAKASH_INSIGHTS_PORT_80_TCP_ADDR': '*****',
 'PRAKASH_INSIGHTS_PORT_80_TCP_PORT': '80',
 'PRAKASH_INSIGHTS_PORT_80_TCP_PROTO': 'tcp',
 'KUBERNETES_PORT_443_TCP_ADDR': '100.64.0.1',
 'PATH': '/opt/utils:/opt/spark:/opt/spark/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
 'KUBERNETES_PORT_443_TCP_PORT': '443',
 'KUBERNETES_PORT_443_TCP_PROTO': 'tcp',
 'LANG': 'C.UTF-8',
 'PRAKASH_INSIGHTS_PORT_80_TCP': '*****',
 'SHELL': '/bin/bash',
 'PYTHON_VERSION': '3.6.8',
 'KUBERNETES_PORT_443_TCP': '******,
 'KUBERNETES_SERVICE_PORT_HTTPS': '443',
 'KUBERNETES_SERVICE_HOST': '100.64.0.1',
 'PWD': '/home/jovyan',
 'PRAKASH_INSIGHTS_SERVICE_PORT_HTTP_PRAKASH_INSIGHTS': '80',
 'NB_PREFIX': '/notebook/prakash-anand/prakash-insights',
 'SPARK_HOME': '/opt/spark',
 'KERNEL_LAUNCH_TIMEOUT': '40',
 'JPY_PARENT_PID': '8',
 'TERM': 'xterm-color',
 'CLICOLOR': '1',
 'PAGER': 'cat',
 'GIT_PAGER': 'cat',
 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline',
 'MLUSER_S3_READONLY_IAM_ROLE': '********',
 'KMP_DUPLICATE_LIB_OK': 'True',
 'KMP_INIT_AT_FORK': 'FALSE',
 'PYSPARK_PYTHON': 'python3',
 'PYSPARK_DRIVER_PYTHON': 'python3'}

**Comment by mn-mikke** [comment]
Hi @p9anand,
what version of `h2o_pysparkling_2.4` have you installed? Such an error happens if you try to run SW on a different Spark version. Can you double-check that the pysparkling package is really for Spark 2.4?

Also can you try to perform some data processing with Spark before calling `h2oContext = H2OContext.getOrCreate()`?

**Comment by mn-mikke** [comment]
Hi @p9anand,
have you managed to solve your problem? Can I close this ticket or is there any help needed?

**Comment by mn-mikke** [comment]
Closing the issue due to inactivity in the threat. If the problem still holds feel free to reopen and provide more details.
