### ISSUE TITLE
ignore constant column default value is set to true but there is no way to change it in sparkling water

### ISSUE THREAD

**Issue by elunenule** [h2oai/sparkling-water#2296]
- All versions
I'm currently using sparkling water, to train and export my models however sometimes the normalized numeric features end up being a constant column when working with a small dateset, is there any chance that we add the ignore_constant_col param to Sparkling water Models or change the default behavior to False?

**Comment by jakubhava** [comment]
The upcoming major release of Sparkling Water ensures consistency between H2O and SW parameters and ignoreConstCols is exposed. The release is expected to go out in september

**Comment by elunenule** [comment]
Thank you for the quick response and the insight!
