### ISSUE TITLE
asH2OFrame Columns names lost when converting one hot encoded/vector column

### ISSUE THREAD

**Issue by elunenule** [h2oai/sparkling-water#2301]
Hello, 
First and foremost thank you the impeccable efforts you've put into Sparkling water.

So i've been working generally with pyspark to prepare data perform feature engineering, feature selection, my only issue is that when training my sparkling water model, and specifically with a OneHotEncoded column or a VectorAssembled column, h2o disregards completely the metadata,

For example  i have a Sex encoded column.
Sex | 
------------ | 
(4,[0],[1.0]) | 
(4,[1],[1.0])|

and i can get which idx corresponds to which category 
```
{'ml_attr': {'attrs': {'binary': [{'idx': 0, 'name': 'male'},
    {'idx': 1, 'name': 'female'},
    {'idx': 2, 'name': '__unknown'},
    {'idx': 3, 'name': 'invalidValues'}]},
  'num_attrs': 4}}
```
However when converting this Spark Dataframe to H2OFrame i get :

Sex.0 | Sex.1 | Sex.2 | Sex.3
-- | -- | -- | --
1 | 0 | 0 | 0
1 | 0 | 0 | 0

I can do the liaison myself manually, but this poses a huge problem when predicting with model, as it register these features as Sex.0 Sex.1 etc, what if we introduce new categories? they will always be encoded as Sex.0 Sex.1 

Any work around or suggestions would be appreciated.

Thank you for your time.

**Comment by mn-mikke** [comment]
Hi @elunenule,
If you work with a categorical features, it's better for H2O algorithms to represent them as `StringType` columns. E.g.:

Sex |
---  |
male |
female |
female |
__unknown |
male | 
invalidValues |

Spark MLlib world and H2O-3 world are a bit different. For MLlib, you have to do every single feature engineering step manually and usually you have to pass a single vector column with all the features encoded to the mllib algorithm. H2O-3 is more flexible in this regards. Features could be represented by multiple columns of any types. H2O-3 algorithm then internally applies ono-hot-encoding if it's needed.

cc @michalkurka

**Comment by elunenule** [comment]
@mn-mikke 
Thank you for your feedback, i agree on the part of leaving categorical features to H2O, i have thought about it and implemented the possibility to do that, however it still affects vector columns especially when performing feature selection for example when using Chi2Selector.

I suppose this is not a major issue, i could resolve the problem by exploding the vector columns myself and assigning names, i just think that h2o handled this part much more efficiently.
