### ISSUE TITLE
save model in a edge node

### ISSUE THREAD

**Issue by joscani** [h2oai/sparkling-water#2304]
Hi. 
I'm using sparkling water 3.30.06 in aws EMR cluster, via rsparkling. When I try to save my model in a serialize mode I write 

 I run sparkling water from edge node.

` 
h2o.saveModel(mymodel, path = "mydir")
`
It works but the model is in a core ec2 instance instead master or edge node. My problem is that I cannot acces to worker nodes , and move the model to a s3 or to my local laptop. How can I change this? 

Thanks

**Comment by mn-mikke** [comment]
Hi @joscani,
can you try to save your model to HDFS?

**Comment by joscani** [comment]
No, using sparkling water in scala I can save in hdfs but using rsparkling not. Right now, our emr is off, I'll check again next monday. Thanks.

**Comment by joscani** [comment]
With  a little of help , I finally get save and load in hdfs, but not in s3 directly. I'll make a workaround . Thansk
