### ISSUE TITLE
Problem in Azure Databricks Cluster to use xgboost from pysparkling

### ISSUE THREAD

**Issue by acsjumpi** [h2oai/sparkling-water#2320]
I have detected a problem when I use PySparkling with xgboost. The error shown in the log attached

Sparkling Water / PySparkling 2.4
Azure Databricks Runtime Version: 6.6 ML (Apache Spark 2.4.5, Scala 2.11)

I start to discuss with @michalkurka and @mn-mikke and the suggestion is change runtime to no-ml version, it works as a quick solution, but we discuss the future problems because of runs with runtime using no-ml generate other problems that affect customers that will require to run Databricks ML version to have different ML libraries (PyTorch, TensorFlow) available in their environment.

One suggestion from @michalkurka is to relocate XGBoost in Spark, because the problem occurs when Spark tries to picking up XGBoost from Spark, not from the H2O XGBoost.

[pysparkling-error-log.txt](https://github.com/h2oai/sparkling-water/files/5241753/pysparkling-error-log.txt)

**Comment by neemah2o** [comment]
Closing since tracked in Jira: https://0xdata.atlassian.net/browse/SW-2437
