### ISSUE TITLE
lambda search in GLM algorithm

### ISSUE THREAD

**Issue by jayden526** [h2oai/sparkling-water#2339]
Hi again, I am training a H2O GLM model in spark with cross validation (regularization lambda search), while I am still confused with the model output even after reading all Sparkling Water documentations.

    Code is:
      val h2oModel = new H2OGLM()
      .setModelId("glm")
      .setNfolds(3)
      .setFeaturesCols(featureList)
      .setLabelCol("label")
      .setFamily("binomial")
      .setSolver("L_BFGS")
      .setAlphaValue(Array(0.0))
      .setLambdaSearch(true)
      .setNlambdas(30)
      .setLambdaMinRatio(1E-4)
      .setMaxIterations(500)

    println(h2oModel.getModelDetails())

Part of the output is:
  "model_category": "Binomial",
  "model_summary": {
    "name": "GLM Model",
    "description": "summary",
    "columns": [
      {
        "name": "",
        "type": "string",
        "format": "%s",
        "description": ""
      },
      {
        "name": "family",
        "type": "string",
        "format": "%s",
        "description": "Family"
      },
      {
        "name": "link",
        "type": "string",
        "format": "%s",
        "description": "Link"
      },
      {
        "name": "regularization",
        "type": "string",
        "format": "%s",
        "description": "Regularization"
      },
      {
        "name": "lambda_search",
        "type": "string",
        "format": "%s",
        "description": "Lambda Search"
      },
      {
        "name": "number_of_predictors_total",
        "type": "int",
        "format": "%d",
        "description": "Number of Predictors Total"
      },
      {
        "name": "number_of_active_predictors",
        "type": "int",
        "format": "%d",
        "description": "Number of Active Predictors"
      },
      {
        "name": "number_of_iterations",
        "type": "int",
        "format": "%d",
        "description": "Number of Iterations"
      },
      {
        "name": "training_frame",
        "type": "string",
        "format": "%s",
        "description": "Training Frame"
      }
    ],
    "rowcount": 1,
    **"data": [
      [""],
      [ "binomial"],
      ["logit"],
      ["Ridge ( lambda \u003d 0.001661 )"],
      ["nlambda \u003d 30, lambda.max \u003d 12.091, lambda.min \u003d 12.091, lambda.1se \u003d 0.008129"],
      [5757],
      [ "5757"],
      [126],
      ["frame_rdd_62_99affc374d2c2de8ac18cf9127ec4a6e"]
    ]**
  },

Iterations and lambda values:
      [
        11,
        14,
        17,
        21,
        25,
        30,
        43,
        47,
        52,
        56,
        61,
        66,
        68,
        72,
        92,
        93,
        102,
        103,
        104,
        105,
        106,
        107,
        108,
        120,
        121,
        122,
        123,
        124,
        125,
        126
      ],
      [
        ".12E2",
        ".88E1",
        ".64E1",
        ".47E1",
        ".34E1",
        ".25E1",
        ".18E1",
        ".13E1",
        ".95E0",
        ".69E0",
        ".5E0",
        ".37E0",
        ".27E0",
        ".19E0",
        ".14E0",
        ".1E0",
        ".75E-1",
        ".55E-1",
        ".4E-1",
        ".29E-1",
        ".21E-1",
        ".15E-1",
        ".11E-1",
        ".81E-2",
        ".59E-2",
        ".43E-2",
        ".31E-2",
        ".23E-2",
        ".17E-2",
        ".12E-2"
      ],

  "lambda_best": 12.091067942694941,
  "lambda_1se": 0.008129257277684368,
  "dispersion": 0.0

My questions are:
1: If I use the lambda search, looks like I can only set lambda numbers and min/max ratio, while can't set lambda range, In the output, it printed out the range it tried is 12 to 0.0012, how does the 12 be calculated?

2. The output said 'Ridge ( lambda \u003d 0.001661 )', looks like it chooses 0.001661 as best lambda, while "nlambda \u003d 30, lambda.max \u003d 12.091, lambda.min \u003d 12.091, lambda.1se \u003d 0.008129" the range looks weird (max = min), and then at the end "lambda_best": 12.091067942694941, just wondering which part is providing the final lambda value from the cross validation?  (as in my experiment, 'lambda_best' is not printing the correct value?)
Thank you very much!

**Comment by mn-mikke** [comment]
cc @michalkurka @wendycwong @maurever @Pscheidl

**Comment by jayden526** [comment]
Got another one:
summary:
      ["Ridge ( lambda \u003d 0.06201 )"],
      ["nlambda \u003d 30, lambda.max \u003d 13.718, lambda.min \u003d 0.08519, lambda.1se \u003d 0.2209"]
lambdas tried in iterations:
      [
        ".14E2",
        ".1E2",
        ".73E1",
        ".53E1",
        ".39E1",
        ".28E1",
        ".2E1",
        ".15E1",
        ".11E1",
        ".79E0",
        ".57E0",
        ".42E0",
        ".3E0",
        ".22E0",
        ".16E0",
        ".12E0",
        ".85E-1",
        ".62E-1",
        ".45E-1"
      ],

Final results:
  "lambda_best": 0.08518848174970675,
  "lambda_1se": 0.2208889453632228,
  "dispersion": 0.0

@michalkurka @wendycwong @maurever @Pscheidl  Please help, thanks

**Comment by wendycwong** [comment]
Here is my answer to your question: If I use the lambda search, looks like I can only set lambda numbers and min/max ratio, while can't set lambda range, In the output, it printed out the range it tried is 12 to 0.0012, how does the 12 be calculated?

Let L = negative log likelihood of your GLM model.  The maximum lambda is set to be dL/dbeta.  It is the derivative of L with respect to beta, the coefficients.  Here is the code to set the rest of lambdas to try

            _parms._lambda = new double[_parms._nlambdas];
            double dec = Math.pow(_parms._lambda_min_ratio, 1.0 / (_parms._nlambdas - 1));
            _parms._lambda[0] = _lmax;
            double l = _lmax;
            for (int i = 1; i < _parms._nlambdas; ++i)
              _parms._lambda[i] = (l *= dec);

Note: _lmax is the maximum lambda value, _parms._lambda_min_ratio is 1e-4 or 1e-2.  Hence, you can see as you change nlambdas, the dec levels will be different and you will get different results when you change nlambdas.

**Comment by wendycwong** [comment]
Here is the answer to your other question: The output said 'Ridge ( lambda \u003d 0.001661 )', looks like it chooses 0.001661 as best lambda, while "nlambda \u003d 30, lambda.max \u003d 12.091, lambda.min \u003d 12.091, lambda.1se \u003d 0.008129" the range looks weird (max = min), and then at the end "lambda_best": 12.091067942694941, just wondering which part is providing the final lambda value from the cross validation? (as in my experiment, 'lambda_best' is not printing the correct value?)

As in my previous answer, when you change nlambdas, you change the dec variable and hence you will get different lambda_best.

Lambda_max = lmax, lambda_min should be _parms._lambda[_parms._nlambdas-1] from previous question.  Lambda_best will be the best lambda found.  The lambda_1se is a strange one.  We use the deviance metric to rank the lambdas during lambda_search.  The lower the deviance, the better.  If we have cross-validation, we will calculate a mean and standard deviation for this deviance metrics.  The lambd_1se corresponds to the lambda value where the deviance value is at deviance_mean + 1 standard deviance away.  Hence, it is not lambda_1se.  In theory, lambda_max and lambda_min should not be the same.  If you find that they are the same, it is probably a bug.  We will need to fix it.  Thank you for bringing it to our attention.

**Comment by jayden526** [comment]
@wendycwong , thank you very much for the detailed explanation, very helpful! While I am still not clear with the second question?
Here is the simplification of the two experiments results I put:

A. ["Ridge ( lambda 0.001661 )"],
["nlambda 30, lambda.max 12.091, lambda.min 12.091"]
"lambda_best": 12.091067942694941

lambda search path in iteration: ".12E2",".88E1",".64E1",".47E1",".34E1",".25E1",".18E1",".13E1",".95E0",".69E0",".5E0",".37E0",".27E0",".19E0",".14E0",".1E0",".75E-1",".55E-1",".4E-1",".29E-1",".21E-1",".15E-1",".11E-1",".81E-2",".59E-2",".43E-2",".31E-2",".23E-2",".17E-2",".12E-2"

B. ["Ridge ( lambda 0.06201 )"],
["nlambda 30, lambda.max 13.718, lambda.min 0.08519]
"lambda_best": 0.08518848174970675

lambda search path in iteration:
".14E2",".1E2",".73E1",".53E1",".39E1",".28E1",".2E1",".15E1",".11E1",".79E0",".57E0",".42E0",".3E0",".22E0",".16E0",".12E0",".85E-1",".62E-1",".45E-1"

Why isn't the lambda in line 1 (model summary) consistent with line 3 (lambda_best)? and which one should I trust? The lambda in line 1 (for A and B) looks more reasonable if we take a look at the lambda search path, for both examples line 1 is the second to last element. However for the lambda best, obviously not correct for A (max = min = lambda best = 12.09). Could you please confirm? Thank you so much!

**Comment by wendycwong** [comment]
@jayden526 

When you enable lambda search, we search over an array of lambdas determined by the algorithm and your dataset distribution.  The lambda_best is derived from array of lambdas that the algorithm has picked for you.  It does not mean that it is the best lambda possible for your dataset.  However, this should give you a range of lambdas to try manually.  If I were you, if you somehow find an optimal lambda and then ask GLM to do lambda search to find you a lambda, I will compare the metrics (logloss/accuracy/mse) and decide which one to use.

**Comment by jayden526** [comment]
@wendycwong @mn-mikke , Thanks a lot! BTW, I was trying to understand the source code that implements the logic you showed above, but couldn't find it in this repo, is it from hex GLM.java in the project h2o-3 ?

**Comment by wendycwong** [comment]
@jayden526:  Yes, you are correct.  It is in GLM.java and start from method computeImpl().

Wendy

**Comment by mn-mikke** [comment]
Thanks @wendycwong for looking after this ticket! @jayden526 Do you have more questions to this topic or can we close the ticket?

**Comment by jayden526** [comment]
Thanks, will close this issue
