### ISSUE TITLE
Serialization for MOJO Models

### ISSUE THREAD

**Issue by preet3loq** [h2oai/sparkling-water#2357]
Hi, 
Is there an option to serial MOJO models (like Mleap without Sparkcontext/ H2Ocontext) /or any other way to deploy model in an API service?

**Comment by mn-mikke** [comment]
The MOJO model as doesn't require any runtime, for making predictions on individual records you can use [`EasyPredictModelWrapper`](http://docs.h2o.ai/h2o/latest-stable/h2o-genmodel/javadoc/hex/genmodel/easy/EasyPredictModelWrapper.html). See also [this piece](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/mojo-quickstart.html#step-2-compile-and-run-the-mojo) of H2O-3 documentation.

**Comment by mn-mikke** [comment]
@preet3loq Do you need more help on this ticket or can we close it?
