### ISSUE TITLE
Differences in H2OGradientBoostingEstimator model training

### ISSUE THREAD

**Issue by alexHeu** [h2oai/sparkling-water#2386]
Hi,

I have a question regarding the H2OGradientBoostingEstimator in a distributed setting.

We are working on Azure Databricks with sparkling-water version: h2o-pysparkling-3.0==3.30.1.3-1
As workers, we are using 3 equally sized nodes and 1 smaller node as driver.

Most of the time, training works very well. However, in some cases it takes about twice the time as usual (with everything else being equal).
We have the suspicion, that the difference is related to the specific CPUs that are assigned to our cluster at startup.

This is a configuration that works well. All 3 worker nodes have the same type of CPU.
![image](https://user-images.githubusercontent.com/8157458/98792855-6868c600-2407-11eb-8e17-c5746acc14ce.png)

On the other hand, this is an example for a configuration that had slow training. Here, one worker has a different type of CPU than the other two:
![image](https://user-images.githubusercontent.com/8157458/98793084-ae258e80-2407-11eb-8f2a-2bb67b9a10a7.png)

Do you think that having different CPUs within the workers can indeed be the reason for the huge performance difference?
Does the driver have any influence at all? 
Or are there any other influencing factors that you can think of?

I appreciate any help and insight that you can provide.

Thanks and best regards
Alexander

**Comment by mn-mikke** [comment]
Hi @alexHeum
Do you pass any extra parameters to `H2OContext` of do you use just default? cc @michalkurka @honzasterba @wendycwong @Pscheidl

**Comment by alexHeu** [comment]
Hi @mn-mikke 

We initialize the context as follows:
`
h2oConf = H2OConf().set("spark.ui.enabled", "false")
hc = H2OContext.getOrCreate(conf=h2oConf)
`
Is there anything that we should change?

**Comment by alexHeu** [comment]
The differences are also visible in the cluster metrics.
This are the metrics in case of normal trainng time
![image](https://user-images.githubusercontent.com/8157458/98810123-ff8d4800-241e-11eb-846e-3b4479d03ebc.png)

In the case of slow training it looks like the CPUs are idling a lot:
![image](https://user-images.githubusercontent.com/8157458/98810397-7b879000-241f-11eb-9660-6134a83b7b35.png)

**Comment by Pscheidl** [comment]
The slowdown with one less-powerful CPU makes sense. Sparkling Water is backed by [H2O-3](https://github.com/h2oai/h2o-3).

H2O-3 is a distributed machine learning platform. The input dataset is distributed evenly across all H2O nodes (provided all nodes are the same). Each H2O node has it's unique portion of the dataset and no other nodes have access to it. TThere are many good reasons for that,  including the data not being small enough to fit into one node. Also, moving data across the cluster is expensive.

With each node having a it's own chunk of the dataset in memory (RAM), each node performs operation on that chunk only. If there are `n` nodes and one of them has half the number of CPUs, as described in this case, then it would take approximately twice the time to finish the operations, be it training or anything else. The reason for that is very simple - the faster nodes are soon done with the computation, yet the slower node is not done yet and other nodes have to wait for it to proceed. 

Ideally, each H2O node should be equally sized in terms of memory and CPUs. More details on that topic can be found in the official documentation, specifically in the [H2O Architecture section](http://docs.h2o.ai/h2o/latest-stable/h2o-docs/architecture.html).

Hope this answers your question. If not, we're here to help.

**Comment by mn-mikke** [comment]
@alexHeu Do you have more questions regarding this topic or can we close?

**Comment by alexHeu** [comment]
@Pscheidl @mn-mikke  thanks for the responses.

In my case the problem was/is that the training time also increases from time to time when using the same cluster configuration. On one day it takes normal training time while on the other day it might take twice the time for no apparent reason and configuration wise all being being equal.
In my initial post I had the suspicion that different CPU types, that are somehow randomly assigned when starting the cluster, are causing this problem.
Unfortunately, after further experiments, I can rule that out as I had the same problem with CPU types that previously worked well.

However, after upgrading to the newest sparkling-water release, so far I have not yet encountered the problem. 
I will update you if the problem persists.

**Comment by mn-mikke** [comment]
I'm closing the issue for now if there are more questions feel free to reopen the issue.
