### ISSUE TITLE
How to calculate Multiclass Classification metrics using mllib evaluations

### ISSUE THREAD

**Issue by dzlab** [h2oai/sparkling-water#2443]
I'm trying to use `org.apache.spark.mllib.evaluation.MulticlassMetrics` to calculate basic metrics on predictions generated by a sparkling water model.

I train a model then run predictions, say something like this
```
  val model = new H2OGBM()
      .setLabelCol("class")
      .setNtrees(5)
      .fit(irisTable)

    // Make prediction on train data
    val predictions = model.transform(irisTable)
```
Now the `predictions` DataFrame has a string column `class` with original labels and `prediction` string column with predicted labels. But what `MulticlassMetrics` takes are the indices of the labels (not the label themselves).

I've something thats works only when labels are String with integer values, but need a more general way
```
    val rawPredictionsAndLabels: RDD[(Double, Double)] = results
      .withColumn("prediction", col("prediction").cast("Double"))
      .withColumn(s"class", col(s"classl").cast("Double"))
      .select(col("prediction"), col(s"$class")).rdd.map(row => (row.getAs[Double]("prediction"), row.getAs[Double](s"class")))
    new MulticlassMetrics(rawPredictionsAndLabels)
```

Is there a way in Sparkling Water to get the mapping (between labels and an index) used during training??

**Comment by mn-mikke** [comment]
Hi @dzlab,
you can try to take a look at the order of the columns under `detailed_prediction.probabilities`. The columns are named by individual classes.

**Comment by dzlab** [comment]
@mn-mikke thanks for the hint, I've end up doing something like below, is that good?
```scala
  /**
   * Calculate a mapping class name to index
   */
  def getMapping(results: DataFrame): Map[String, Double] = {
    results.schema("detailed_prediction").dataType.asInstanceOf[StructType].fields
      .filter(_.name.equals("probabilities")).flatMap(_.dataType.asInstanceOf[StructType].fields)
      .map(field => (field.name))
      .zipWithIndex.map{case (name, index) => (name, index.toDouble)}
      .toMap
  }
```

**Comment by dzlab** [comment]
@mn-mikke how about Boolean columns? they seem to be encode into 0/1, how can I tell in this case what true was mapped to??

**Comment by dzlab** [comment]
@mn-mikke  how about the other way to get categorical encodings using `model.getDomainValues` which returns `Map[String -> Array[String]]` where the keys are names of categorical columns in the dataset and values are the actual categories.
Assuming, the position of the value in this array matches the position of the column in the probabilities. Is using this a better option than looking into the schema of `detailed_predictions.probabilities`.

**Comment by mn-mikke** [comment]
> @mn-mikke how about Boolean columns? they seem to be encode into 0/1, how can I tell in this case what true was mapped to??

The logic for binomial cases is the same. The first column name of `detailed_predictions.probabilities` represents negative label.

> how about the other way to get categorical encodings using model.getDomainValues

yes, you can use `model.getDomainValues` the order is the same.
