### ISSUE TITLE
AutoML Leaderboard is not available in SW

### ISSUE THREAD

**Issue by atigbadr** [h2oai/sparkling-water#2458]
Hello,

I've been wondering if H2OAutoML leaderboard is gonna be exposed in SW, or if it is in the roadmap?

Right now, i'm doing some automated processing in order to extract all the models and compare them using Pysparkling, i wonder if there is a ticket  that i could probably work on?

Thank you.

**Comment by mn-mikke** [comment]
Hi @atigbadr,
it's exposed, check the bottom of [this page](http://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/ml/sw_automl.html).

**Comment by atigbadr** [comment]
Thank you the reply, idk how i missed it.
