### ISSUE TITLE
Add Spark 3.1.1 support

### ISSUE THREAD

**Issue by derSascha** [h2oai/sparkling-water#2470]
Any plans to Support Spark 3.1? Looks like only minor changes happens in Spark (mostly PySpark improvements) and it should be easy to be added in sparkling-water.

 http://spark.apache.org/releases/spark-release-3-1-1.html

**Comment by derSascha** [comment]
After playing with a little bit, it seems to be very easy to support Spark 3.1 See my PR #2471

**Comment by mn-mikke** [comment]
@derSascha We have been thinking about adding Spark 3.1.1 to the upcoming major release `3.32.1.1-1` (the second half of March). There are few operational things that needs to be done before including this feature into the release. (such as allocating new space for new artifacts in PyPi)  Thanks for your PR! I will take a look and let know if there more things that needs to be added.

**Comment by mn-mikke** [comment]
The support will added in `3.32.1.2-1`. Thanks for you contribution!

**Comment by derSascha** [comment]
@mn-mikke thanks for the update! Can't find `3.32.1.2-1`, is there a plan to release this soon?
