### ISSUE TITLE
Final version numbers do not follow python specifications

### ISSUE THREAD

**Issue by cdesouza21** [h2oai/sparkling-water#2497]
I am unable to make the sparkling-water package available in Conda Forge using the package published to pypi:
- https://pypi.org/project/h2o-pysparkling-3.0/

The version numbers being produced do not follow Python specifications for final releases. Conda forge pull request is here:
- https://github.com/conda-forge/staged-recipes/pull/14532

The raw logs are here:
- https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/302714/logs/13

The specific error is:
`2021-04-12T15:26:13.0221267Z Error: bad character '-' in package/version: 3.32.1.1-1`

Would it be possible to get version number scheme published that is compatible with Python specifications for final releases?
- https://www.python.org/dev/peps/pep-0440/#final-releases

**Comment by mn-mikke** [comment]
@cdesouza21 Are you happy with the answer above? Can I close the issue?

**Comment by mn-mikke** [comment]
@cdesouza21 I'm closing this issue. Let me know if you have troubles with  https://anaconda.org/h2oai/h2o_pysparkling_3.0.
