### ISSUE TITLE
Increasing 'spark.locality.wait' to value 30000 forever?

### ISSUE THREAD

**Issue by zma4** [h2oai/sparkling-water#25]
I was trying to use h2o on a spark cluster launched through the spark-ec2 script on AWS. I follow the instruction at http://h2o-release.s3.amazonaws.com/sparkling-water/rel-1.5/6/index.html
At step 4,  val h2oContext = new H2OContext(sc).start() a lot of "collect at H2OContextUtils.scala:54" were generated. The number of tasks inside grow exponentially, and it wouldn't proceed.
Does anyone have a tip on this? Thanks

**Comment by mmalohlava** [comment]
Make sure, that TCP/UDP ports are opened between instances:  by default ports 54321 (TCP) and 54322 (TCP & UDP) are used.

**Comment by zma4** [comment]
Seems like I got a out-dated hadoop version. Update to 2.4 solved the issue. Thanks.
