### ISSUE TITLE
SW H2OGridSearch poor performance

### ISSUE THREAD

**Issue by atigbadr** [h2oai/sparkling-water#2503]
- Sparkling Water/PySparkling/RSparkling version: 2.2_3.32.1.1-1
- Hadoop Version & Distribution: 2.6
- Execution mode: Yarn-cluster
- OS: Centos 6.7
- Spark & Sparkling Water configuration including the memory configuration: 
```
spark.driver.cores                  32
spark.driver.maxResultSize          14g
spark.logConf                       true
spark.driver.memory                 14g
spark.executor.memory               14g
spark.python.worker.memory          10g
spark.python.worker.reuse           true
spark.executor.instances            10  
spark.executor.cores	            32
spark.scheduler.minRegisteredResourcesRatio 1
spark.network.timeout 3600
spark.executor.heartbeatInterval 10

spark.ext.h2o.backend.cluster.mode  internal
spark.ext.h2o.nthreads  -1
spark.ext.h2o.repl.enabled  false
spark.ext.h2o.client.verbose    true

spark.yarn.driver.memoryOverhead 2g
spark.yarn.executor.memoryOverhead 2g
spark.yarn.am.memoryOverhead 2g
spark.yarn.am.memory 13g
spark.yarn.heterogeneousExecutors.enabled   false
spark.yarn.max.executor.failures    1
spark.yarn.am.cores 32
```
Hello, thank you in advance for reading this.

I have been experimenting with H2OGridSearch on SW and i have noticed that the computing time is really poor, here are some information regarding the dataset

* Dataset size: 18.4 GO on RAM
* n columns : 327 (Mostly numeric features)
* multiclassification ( 5classes) 

I have tried to train two DRF with an [H2OGridSearch](http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/ml/sw_grid.html) of only `ntrees=[500, 1000]` and a fixed `nfolds=3`, the rest of parameters are set to default

### What i have tried:
* Reducing/Adding more workers/threads
* Reducing the dataset to fit one node and train on one node
* Changing the level of parallelism 0, 1, 2, 4
* Changing launch mode
* do/don't compute aucpr
* Not using H2OGridSearch and sticking to a manual gridsearch  using H2ODRF
* Consulting/Administrating H2O Cluster activities , cluster status, data locality/distribution, job tracking and cpu meter activity showed that there was no idle item and everything seemed fine

### What i have noticed
1. No matter what i did regarding the H2OGridSearch the performance was really slow and i really couldn't find any explaination to why i have such a poor performance, after over 22hours of training the H2OGridSearch didn't finish my 2 models (which are 2* 3 +2=8 or 6 with nfolds=3, if im not mistaken)  i had to interrupt the training

2. Training two H2ODRF with the same parameters given to H2OGridSearch succeeeded after 14Hours.

I have no idea why there is such a huge gap of performance and i've been unable to confirm/find any other related issues regarding this, i wonder if this is just a misconfiguration from my side, i would appreciate your input regarding this issue.

Cheers!

**Comment by mn-mikke** [comment]
Hi @atigbadr,
Can you share YARN logs for this interrupted run?
```yarn logs -applicationId <Application ID>```

Do you experience the same behavior if you try to use H2O-3 API? 
http://docs.h2o.ai/h2o/latest-stable/h2o-docs/grid-search.html#grid-search-examples

cc @michalkurka @maurever @wendycwong

**Comment by atigbadr** [comment]
The file is too big, do you want specific logs ? if not here is the log on gdrive  https://drive.google.com/file/d/10IGsPC7fVkRsvmQYDAsM0yZbkH0MmB4K/view?usp=sharing

Regarding the H2O-3 API, i'll perform a test and keep you updated.

**Comment by michalkurka** [comment]
@atigbadr thanks for sharing your experience, I requested access to the log file on google drive

My hunch is that the issue will be somehow related to the type of problem (multiclass). We will see more in the logs once we have them available.

**Comment by atigbadr** [comment]
@mn-mikke, Hello i have tried to execute it using the H2O-3 API and i  got more information + full logs, i have launched two trainings, one in parallel and one in sequential mode.

Here is the bloc of code i used 
```python
spark.catalog.clearCache()
data = hc.asH2OFrame(data_train_cleaner)
test = hc.asH2OFrame(data_test_cleaner)
x = data.columns
y = target
x.remove(y)
data[target] = data[target].asfactor()
test[target] = test[target].asfactor()
for cat_col in categorical_cols:
    data[cat_col] = data[cat_col].asfactor()
    test[cat_col] = test[cat_col].asfactor()

ss = data.split_frame(seed=1)
train = ss[0]
valid = ss[1]

# DRF hyperparameters
drf_params = {'ntrees': [500, 1000]}

# Train and validate a cartesian grid of DRFs
drf_grid = H2OGridSearch(model=H2ORandomForestEstimator,
                          grid_id='drf_grid',
                          hyper_params=drf_params,
                         parallelism=6) # 1 for sequential
drf_grid.train(x=x, y=y,
                training_frame=train,
                validation_frame=valid,
                seed=1,
                nfolds=3)
```
Both applications are still running and here are the logs:

[h2ologs_20210420_102422_parallel.zip](https://github.com/h2oai/sparkling-water/files/6342634/h2ologs_20210420_102422_parallel.zip)

[h2ologs_20210420_102553_sequential.zip](https://github.com/h2oai/sparkling-water/files/6342637/h2ologs_20210420_102553_sequential.zip)

What i understood by reading the logs is that there is a frequent GC triggering even so there is enought memory and it could probably be resolved by setting extraJavaOptions for spark executors and spark driver?

Im thinking about setting the follow JVM options and attempt another training job
```-XX:NewSize=800m -XX:MaxNewSize=800m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:ParallelGCThreads=4```


![Parallel_status](https://user-images.githubusercontent.com/33746912/115378649-0dff3d00-a1d1-11eb-840f-0dadcaef2f07.PNG)
![Parallel](https://user-images.githubusercontent.com/33746912/115378653-0f306a00-a1d1-11eb-828f-18a41325934f.PNG)
![Sequential_status](https://user-images.githubusercontent.com/33746912/115378654-0fc90080-a1d1-11eb-8c79-294e33cb59b4.PNG)
![Sequential](https://user-images.githubusercontent.com/33746912/115378656-0fc90080-a1d1-11eb-82ef-572503685f3f.PNG)

**Comment by michalkurka** [comment]
@atigbadr 

The "sequential" run shows you are running Out Of Memory:

```
04-20 08:36:45.471 10.155.132.22:54321   24053     FJ-2-95  INFO hex.tree.SharedTree: 545. tree was built in 00:00:25.578 (Wall: 20-Apr 08:36:45.471) 
04-20 08:36:47.709 10.155.132.22:54321   24053  ice Thread  WARN water.default: Swapping!  GC CALLBACK, (K/V:9.19 GB + POJO:583.4 MB + FREE:2.69 GB == MEM_MAX:12.44 GB), desiredKV=7.20 GB OOM!
04-20 08:36:50.077 10.155.132.22:54321   24053  ice Thread  WARN water.default: Swapping!  GC CALLBACK, (K/V:9.19 GB + POJO:553.0 MB + FREE:2.72 GB == MEM_MAX:12.44 GB), desiredKV=7.26 GB OOM!
```

DKV on that node has 8GB while maximum memory is only 12GB.

In Flow - can you take a screenshot of how the frame is distributed? In menu Data -> List all frames -> training frame -> And expand "chunk summary" and "frame distribution summary"

<img width="1022" alt="Screen Shot 2021-04-20 at 10 41 03 AM" src="https://user-images.githubusercontent.com/20690218/115415484-f3bf6200-a1c4-11eb-9d19-e41c6f3d7fed.png">

**Comment by atigbadr** [comment]
@michalkurka 

Here is the screenshot that you requested
![distriub](https://user-images.githubusercontent.com/33746912/115424745-43228400-a1ff-11eb-819c-3f9000474476.PNG)


Here is an updated log for the "sequential_job"

[h2ologs_20210420_051304_seq_last.zip](https://github.com/h2oai/sparkling-water/files/6344812/h2ologs_20210420_051304_seq_last.zip)

UPDATE on the job i run with  `parallelism=3`: i got an error with the following message:
```
Hyper-parameter: ntrees, 1000
failure_details: Illegal argument(s) for DRF model: DRF_model_1618833568207_2_cv_3.  Details: ERRR on field: _ntrees: The tree model will not fit in the driver node's memory (195.9 KB per tree x 1000 > 54.9 MB) - try decreasing ntrees and/or max_depth or increasing min_rows!

failure_stack_traces: water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for DRF model: DRF_model_1618833568207_2_cv_3.  Details: ERRR on field: _ntrees: The tree model will not fit in the driver node's memory (195.9 KB per tree x 1000 > 54.9 MB) - try decreasing ntrees and/or max_depth or increasing min_rows!
```


Our cluster configuration for max yarn container size is limited to 16GB, would increasing container size resolve this problem?

Sorry for the mass updates, and thank you again for your help.

**Comment by michalkurka** [comment]
Since you are having memory problems - first thing I would do would be to disable additional parallelism and just use the default. You don't want to be running multiple models in parallel if you don't have enough memory.

That won't help because even the sequential run had memory issues. I think increasing memory per container is a very good idea.

My question is - the problem you are running seems imbalanced - majority of the observations are in Class 1. Only small franctions in the rest. Would it make sense to first train a binomial model to distinguish between class 1 and the rest and then train a secondary model that would identify the other 4 classes?

**Comment by atigbadr** [comment]
@michalkurka Yup, it does make sense, however the end results for us would be the same, because what we are interested in is the aucpr, with OVO for each class.

But it still is wierd that running two H2ODRF sequentially (without GridSearch) is faster than an H2OGridSearch (two models as well)  with 0 parallelisme

**Comment by michalkurka** [comment]
> But it still is wierd that running two H2ODRF sequentially didn't trigger an OOM (without GridSearch) and is faster than an H2OGridSearch (two models as well) with 0 parallelisme

Yes, that shouldn't happen - definitely suspicious.

> @michalkurka Yup, it does make sense, however the end results for us would be the same, because what we are interested in is the aucpr, with OVO for each class.

I see, calculating AUCPR for multiclass is quite expensive. Did you try running with AUCPR disabled?

cc: @maurever just fiy for now, lets find out if AUCPR could be the cause

**Comment by atigbadr** [comment]
> I see, calculating AUCPR for multiclass is quite expensive. Did you try running with AUCPR disabled?

@michalkurka , yes both of these jobs are running without AUCPR enabled,  (i have already tested with AUCPR enabled) and there was no difference in the computation time (since we have more than enough cores maybe?)

I would like to note that i have tried running H2OGridSearch in another cluster with a bigger container size, (28GB per container) and it took 21Hours to finish training Two models sequentially (ntrees=[500, 100]) and cv=3 for both, with AUCPR on

**Comment by atigbadr** [comment]
@michalkurka , Hello thank for your help, the main issue was that there was alot of other jobs in parallel which made the performance evaluation harder, on top of the limited container sizes
