### ISSUE TITLE
How can i get the source code of H2OGBM and H2ODeepLearning

### ISSUE THREAD

**Issue by monkey408** [h2oai/sparkling-water#2504]
-Sparkling Water 3.32.1.1-1-2.4
Hi , In this version, how can i get the source code of  H2OGBM and H2ODeepLearning class?
I download the project but I can't compile the project successfully.

**Comment by mn-mikke** [comment]
Hi @monkey408,
these classes are auto-genereted from [domain classes of H2O-3 REST API](https://github.com/h2oai/h2o-3/tree/687e42a9840f9320a48ab684036d3247d21f7ea5/h2o-algos/src/main/java/hex/schemas).

To compile the project, you can run:
`./gradlew build -x check`

To create a deployable artifact under `dist` folder. Run:
`./gradlew dist`

What trouble you have with building the project?
