### ISSUE TITLE
How can I get all the models from the AutoML leaderboard

### ISSUE THREAD

**Issue by dzlab** [h2oai/sparkling-water#2520]
I'm training an automl model, after training it gives me a leader model only
```
val automl = new H2OAutoML()
      .setFeaturesCols(featureCols)
      .setLabelCol(labelCol)
      ...
val model = automl.fit(trainDF)
```
How can I get all the other models in the leaderboard as H2OMojoModel?

**Comment by mn-mikke** [comment]
Hi @dzlab,
This is not currently supported by SW API. But it sounds like a good feature. I've create a Jira ticket for it [here](https://h2oai.atlassian.net/browse/SW-2560) where you can track the progress.

**Comment by mn-mikke** [comment]
The feature has been release in SW `3.32.1.3-1`. http://docs.h2o.ai/sparkling-water/3.0/latest-stable/doc/ml/sw_automl.html
