### ISSUE TITLE
Unable to generate shaply values using Pysparkling h2o isolation forest

### ISSUE THREAD

**Issue by cibinjohn** [h2oai/sparkling-water#2527]
I am not able to obtain shaply values from isolation forest on my data set, following the instructions provided in this link (http://docs.h2o.ai/sparkling-water/2.1/latest-stable/doc/ml/shap_values.html#get-contributions-from-raw-mojo).   I have tried to obtain shaply values from XGboost algorithm by following the steps in the above link, which is working fine. 

Any inputs are appreciated.   Thanks in advance.

**Versions**
- h2o-pysparkling-3.0: 3.32.1.2.post1
- Hadoop Version: hadoop-2.7.1
- Execution mode : local
- Spark version: spark-3.0.1-bin-hadoop2.7
- Ubuntu 18.04

### Code

```
import h2o
from pysparkling import H2OContext
from pysparkling.ml import H2OIsolationForest

hc = H2OContext.getOrCreate()

df = h2o.import_file("../data/sample.csv")
trainingDF = hc.asSparkFrame(df)
trainingDF = trainingDF.withColumn("Class", trainingDF.Class.cast("string"))

estimator = H2OIsolationForest(featuresCols=['v1','v2'],  withContributions=True)

model = estimator.fit(trainingDF)

test_df = hc.asSparkFrame(df)
pred = model.transform(test_df)

pred.toPandas().to_csv('predictions.csv')

```
### sample.csv (Input file)
```
v1,v2,Class
1,1,0
1,1,0
1,1,0
2,2,0
2,2,0
2,1,0
3,1,0
3,2,0
3,3,0
5,1,0
-1,2,0
2,1,0
7,2,0
2,4,0
10000,1000,1
-10000,12222,1
```

### predictions.csv (Output file)
```
,v1,v2,Class,detailed_prediction,prediction
0,1,1,0,"Row(score=1.26, normalizedScore=0.08333333333333333)",1.26
1,1,1,0,"Row(score=1.26, normalizedScore=0.08333333333333333)",1.26
2,1,1,0,"Row(score=1.26, normalizedScore=0.08333333333333333)",1.26
3,2,2,0,"Row(score=1.3, normalizedScore=0.027777777777777776)",1.3
4,2,2,0,"Row(score=1.3, normalizedScore=0.027777777777777776)",1.3
5,2,1,0,"Row(score=1.28, normalizedScore=0.05555555555555555)",1.28
6,3,1,0,"Row(score=1.28, normalizedScore=0.05555555555555555)",1.28
7,3,2,0,"Row(score=1.3, normalizedScore=0.027777777777777776)",1.3
8,3,3,0,"Row(score=1.28, normalizedScore=0.05555555555555555)",1.28
9,5,1,0,"Row(score=1.32, normalizedScore=0.0)",1.32
10,-1,2,0,"Row(score=1.32, normalizedScore=0.0)",1.32
11,2,1,0,"Row(score=1.28, normalizedScore=0.05555555555555555)",1.28
12,7,2,0,"Row(score=1.3, normalizedScore=0.027777777777777776)",1.3
13,2,4,0,"Row(score=1.26, normalizedScore=0.08333333333333333)",1.26
14,10000,1000,1,"Row(score=0.66, normalizedScore=0.9166666666666666)",0.66
15,-10000,12222,1,"Row(score=0.6, normalizedScore=1.0)",0.6
```

**Comment by mn-mikke** [comment]
The contributions are not supported on IsolationForest and you will see the following warning the call of `tranform` method.:
```WARN ai.h2o.sparkling.ml.models.H2OMOJOCache: Computing contributions is not allowed on MOJO of type 'class hex.genmodel.algos.isofor.IsolationForestMojoModel'!```

We will remove the `withContributions` from the algorithm to avoid confusions.

cc @michalkurka

**Comment by mn-mikke** [comment]
if you have any related questions, don't hesitate to reopen the issue. I'm closing it for now.
