### ISSUE TITLE
SVM support in Sparkling Water

### ISSUE THREAD

**Issue by dzlab** [h2oai/sparkling-water#2532]
It seems that SVM is part of H2O core [doc](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/svm.html) and there was a ticket in Sparkling Water to add support of SVM [SW-1589](https://h2oai.atlassian.net/browse/SW-1589) but it has been a year without activity.

Any ideas when the support of SVM be added?

**Comment by mn-mikke** [comment]
The SVM algorithm is on the todo list, but it's not a priority right now since changes in H2O-3 are required for it.
