### ISSUE TITLE
How to cancel a running H2OJob

### ISSUE THREAD

**Issue by dzlab** [h2oai/sparkling-water#2539]
@mn-mikke I see that there is a `H2OJob` that can be used to wait until job finishes `H2OJob(id).waitForFinish()`.
The API to get status from H2O seems to be a `GET /3/Jobs/$jobId`.
I also see that `H2OJobStatus` has a `CANCELLED` value, so a job can technically reach that state.
How I can cancel a job? what's the H2O API or URL?

**Comment by dzlab** [comment]
@mn-mikke I figure out the API and made a PR https://github.com/h2oai/sparkling-water/pull/2540

**Comment by mn-mikke** [comment]
Hi @dzlab,
you can cancel a running job in Flow UI.

1. Go to admin tab > jobs
![image](https://user-images.githubusercontent.com/3674621/123816045-48830580-d8f7-11eb-899d-2114284ad05c.png)

2. Select the job that you want to cancel.
![image](https://user-images.githubusercontent.com/3674621/123817524-87658b00-d8f8-11eb-875d-eab9de029973.png)

3. Press cancel button.
![image](https://user-images.githubusercontent.com/3674621/123816372-8c760a80-d8f7-11eb-86cf-dc19c933dc0b.png)



Is there any motivation to do it programatically? If so, IMHO the API needs to be changed differently, `H2OJob` is an internal class utilized by SW API and also available only in scala.

**Comment by dzlab** [comment]
@mn-mikke yeah I need to cancel programmatically, I've end up copying `H2OJob` class and changing it (e.g. making the class extend `RestCommunication`).
Let me know if you think it is worth adding this to SW, I will be happy to change my PR with your input.

**Comment by mn-mikke** [comment]
@dzlab We can add this functionality if other users can benefit as well. Can you share a bigger picture of your use case? Do you trigger model training asynchronously and then you wait for a time period and you cancel the job eventually? Where do you get a jobId?

**Comment by dzlab** [comment]
@mn-mikke I see your point, this may not be useful to other users. In my case, I run the training manually by directly invoking H2O API to start training so I have a job id. The goal of implementing cancel is almost like early stopping, e.g. when i release the models are too bad or I want chose other training options I don't have to wait for current training to finish.
