### ISSUE TITLE
What's the difference between  "new H2OContext(sc).start" and  "H2OContext.getOrCreate(sc)" ?

### ISSUE THREAD

**Issue by mwlgcmwlgc** [h2oai/sparkling-water#26]
The DEVEL.md was modified in which `new H2OContext(sc).start` was changed to `H2OContext.getOrCreate(sc)` .  
In sparkling-shell, it works fine when I use `new H2OContext(sc).start` , but I get  **0**  number of executors when use   `H2OContext.getOrCreate(sc) ` and the Flow URL is  "http://null:0".  The MASTER was set to " local-cluster[3,2,1024] ".   
I didn't find any documentation  about  `getOrCreate`, so what's the difference and how should I decide which one to use ?
I use spark 1.5.2 and sparkling-water 1.5.9 .

**Comment by MadMan0708** [comment]
Hi mwlgcmwlgc,
    thanks for reporting this! We internally switched to using `H2OContext.getOrCreate(sc)`, but it does exactly the same as the `new H2OContext.start()`.

 `H2OContext.getOrCreate(sc)` has the advantage that it initiates and starts H2OContext in one call and can also be used for obtaining already existing or creating new H2OContext.

I have clarified the use of both starting options in DEVEL.md and fixed the issue
>In sparkling-shell, it works fine when I use new H2OContext(sc).start , but I get 0 number of executors when use H2OContext.getOrCreate(sc) and the Flow URL is "http://null:0". The MASTER was set to " local-cluster[3,2,1024] ".

in current master branch, so the both ways should now work correctly.

**Comment by MadMan0708** [comment]
I'm closing this issue, please start new issue if you still have some problems with it.

Thank you,
Kuba
