### ISSUE TITLE
create lernel for jupterhub

### ISSUE THREAD

**Issue by vhp1360** [h2oai/sparkling-water#269]
hi experts,
in PySparkling you provide `PYSPARK_DRIVER_PYTHON="ipython" PYSPARK_DRIVER_PYTHON_OPTS="notebook" bin/pysparkling` commands to join jupyter notebook for running PySparkling, I'm wondering if any one provide me to how can I create PySparkling kernel for jupyterhub.

Regards,

**Comment by jakubhava** [comment]
Hi @vhp1360, sorry for late answer. You can check this article - http://jinyi.me/2015/12/Setting-up-IPython-Jupyterhub-for-pyspark/. Setting up pysparkling is the same as setting up pyspark with only exception that you need to put pysparkling egg file on the python pathas well  in the kernel specification.

**Comment by vhp1360** [comment]
Hi @jakubhava, thanks for the reply.
could you please let me know what do you mean of _you need to put pysparkling egg file_?
as I understood, you meant I should put a file in ENV section in "PYTHONPATH" value, am I right?
but I don't know which file.

Thanks.

**Comment by vhp1360** [comment]
Hi @jakubhava, thanks for the reply.
could you please let me know what do you mean of _you need to put pysparkling egg file_?
as I understood, you meant I should put a file in ENV section in "PYTHONPATH" value, am I right?
but I don't know which file.
```
  1-/home/vhp/sparkling-water-rel-2.1/bin/pysparkling
  2-/home/vhp/sparkling-water-rel-2.1/py/pysparkling
  3-/home/vhp/sparkling-water-rel-2.1/py/build/h2o_pysparkling_2.1.egg-info
  4-/home/vhp/sparkling-water-rel-2.1/py/build/dist/h2o_pysparkling_2.1-2.1.6-py2.7.egg
```

Thanks.

**Comment by jakubhava** [comment]
Hi @vhp1360, you need to put the egg file on the PYTHONPATH in the kernel script. In your case - /home/vhp/sparkling-water-rel-2.1/py/build/dist/h2o_pysparkling_2.1-2.1.6-py2.7.egg file
