### ISSUE TITLE
error: Different version of the JAR

### ISSUE THREAD

**Issue by dataspekulant** [h2oai/sparkling-water#2690]
Trying to initialize H2OContext in PySpark but getting following error:

`Exception: JAR file for Sparkling Water 2.4.2 is already attached to the cluster, but you are starting PySparkling for 3.34.0.3-1-2.4. Either remove the attached JAR of the different version or use PySparkling of the same version as the attached JAR.`

Any help?

_Running PySparkling (3.34.0.3-1-2.4) on YARN._

**Comment by krasinski** [comment]
That most likely means an old version of Sparkling Water (from early 2019) was found on your cluster classpath. Can you check if that's the case?
What this check does is looking for a file "sw.version" (which contains Sparkling Water version) on a classpath and checks if PySparkling version is the same.
