### ISSUE TITLE
use h2o in spark cluster

### ISSUE THREAD

**Issue by Damonsoul** [h2oai/sparkling-water#2738]
h2o works well at local mode,but failed when I try to use at spark cluster

R code:
library(sparklyr)
library(h2o)
library(rsparkling)

conf <- spark_config()
conf$`sparklyr.shell.driver-memory` <- "6G"
conf$driver.memory <-  "6G"
conf$spark.cores.max <- 6
conf$spark.executor.memory <- "6G"
conf$spark.executor.cores <- 6
conf$spark.locality.wait <- 3000
conf$spark.scheduler.minRegisteredResourcesRatio <- 1
conf$spark.task.maxFailures <- 1
conf$spark.executor.heartbeatInterval <- '10s'
conf$spark.dynamicAllocation.enabled <- FALSE
conf$spark.yarn.heterogeneousExecutors.enabled <- FALSE
conf <- c(conf, list(
  "spark.hadoop.yarn.timeline-service.enabled" = "false",
  "spark.ext.h2o.external.cluster.size" = "1",
  "spark.ext.h2o.backend.cluster.mode" = Sys.getenv("spark.ext.h2o.backend.cluster.mode"),
  "sparklyr.connect.enablehivesupport" = FALSE,
  "sparklyr.gateway.connect.timeout" = 240,
  "sparklyr.gateway.start.timeout" = 240,
  "sparklyr.backend.timeout" = 240,
  "sparklyr.log.console" = TRUE,
  "spark.ext.h2o.external.start.mode" = "auto",
  "spark.ext.h2o.external.disable.version.check" = "true",
  "sparklyr.gateway.port" = 55555,
  "sparklyr.connect.timeout" = 60 * 5,
  "spark.master" = "spark://172.33.6.75:7077"
))
sc <- spark_connect(master = "spark://172.33.6.75:7077",config = conf)
hc <- H2OContext.getOrCreate()

sparklog:
22/02/21 23:20:42 INFO H2OContext: Sparkling Water version: 3.36.0.2-1-2.4
22/02/21 23:20:42 INFO H2OContext: Spark version: 2.4.7
22/02/21 23:20:42 INFO H2OContext: Integrated H2O version: 3.36.0.2
22/02/21 23:20:42 INFO H2OContext: The following Spark configuration is used: 
    (spark.dynamicAllocation.enabled,false)
    (spark.home,C:\Users\Administrator\AppData\Local\spark\spark-2.4.7-bin-hadoop2.7)
    (spark.scheduler.minRegisteredResourcesRatio,1)
    (spark.driver.memory,6G)
    (spark.task.maxFailures,1)
    (spark.shuffle.maxChunksBeingTransferred,100)
    (spark.master,spark://172.33.6.75:7077)
    (spark.app.name,sparklyr)
    (spark.executor.memory,6G)
    (spark.locality.wait,0)
    (spark.yarn.heterogeneousExecutors.enabled,false)
    (spark.spark.port.maxRetries,128)
    (spark.submit.deployMode,client)
    (spark.sql.warehouse.dir,C:/Users/Administrator/AppData/Local/spark/spark-2.4.7-bin-hadoop2.7/tmp/hive)
    (spark.sql.legacy.utcTimestampFunc.enabled,true)
    (spark.ext.h2o.external.cluster.size,1)
    (spark.local.dir,C:/Users/Administrator/AppData/Local/spark/spark-2.4.7-bin-hadoop2.7/tmp/local)
    (spark.ext.h2o.external.disable.version.check,true)
    (spark.app.id,app-20220221232037-116709)
    (spark.hadoop.yarn.timeline-service.enabled,false)
    (spark.ext.h2o.cloud.name,sparkling-water-Administrator_app-20220221232037-116709)
    (spark.executor.id,driver)
    (spark.driver.host,QS016055Deploy.ehai.com)
    (spark.ext.h2o.hdfs_conf,C:\Users\Administrator\AppData\Local\spark\spark-2.4.7-bin-hadoop2.7\tmp\local\spark-048683ab-4c22-45a2-932b-9e0fcc4bccc2\hdfs_conf6297637897647894553.xml)
    (spark.executor.heartbeatInterval,10s)
    (spark.repl.local.jars,file:///C:/Program%20Files/R/R-4.1.2/library/rsparkling/java/sparkling_water_assembly.jar)
    (spark.executor.cores,6)
    (spark.ext.h2o.client.language,r)
    (spark.driver.port,19385)
    (spark.network.timeout,99999s)
    (spark.ext.h2o.external.start.mode,auto)
    (spark.jars,file:///C:/Program%20Files/R/R-4.1.2/library/rsparkling/java/sparkling_water_assembly.jar,file:/C:/Program%20Files/R/R-4.1.2/library/sparklyr/java/sparklyr-2.4-2.11.jar)
    (spark.cores.max,6)
22/02/21 23:20:42 INFO InternalH2OBackend: Starting the H2O cluster inside Spark.
22/02/21 23:20:42 INFO SparkContext: Starting job: collect at SpreadRDDBuilder.scala:69
22/02/21 23:20:42 INFO DAGScheduler: Registering RDD 2 (distinct at SpreadRDDBuilder.scala:68) as input to shuffle 0
22/02/21 23:20:42 INFO DAGScheduler: Got job 0 (collect at SpreadRDDBuilder.scala:69) with 11 output partitions
22/02/21 23:20:42 INFO DAGScheduler: Final stage: ResultStage 1 (collect at SpreadRDDBuilder.scala:69)
22/02/21 23:20:42 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 0)
22/02/21 23:20:42 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 0)
22/02/21 23:20:42 INFO DAGScheduler: Submitting ShuffleMapStage 0 (MapPartitionsRDD[2] at distinct at SpreadRDDBuilder.scala:68), which has no missing parents
22/02/21 23:20:42 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 7.5 KB, free 3.0 GB)
22/02/21 23:20:42 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 4.1 KB, free 3.0 GB)
22/02/21 23:20:42 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on QS016055Deploy.ehai.com:19419 (size: 4.1 KB, free: 3.0 GB)
22/02/21 23:20:42 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1184
22/02/21 23:20:42 INFO DAGScheduler: Submitting 11 missing tasks from ShuffleMapStage 0 (MapPartitionsRDD[2] at distinct at SpreadRDDBuilder.scala:68) (first 15 tasks are for partitions Vector(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
22/02/21 23:20:42 INFO TaskSchedulerImpl: Adding task set 0.0 with 11 tasks
22/02/21 23:20:42 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, 172.33.6.77, executor 0, partition 0, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:20:42 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, 172.33.6.77, executor 0, partition 1, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:20:42 INFO TaskSetManager: Starting task 2.0 in stage 0.0 (TID 2, 172.33.6.77, executor 0, partition 2, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:20:42 INFO TaskSetManager: Starting task 3.0 in stage 0.0 (TID 3, 172.33.6.77, executor 0, partition 3, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:20:42 INFO TaskSetManager: Starting task 4.0 in stage 0.0 (TID 4, 172.33.6.77, executor 0, partition 4, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:20:42 INFO TaskSetManager: Starting task 5.0 in stage 0.0 (TID 5, 172.33.6.77, executor 0, partition 5, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:21:15 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.33.6.77:33971 (size: 4.1 KB, free: 3.0 GB)
22/02/21 23:21:15 INFO TaskSetManager: Starting task 6.0 in stage 0.0 (TID 6, 172.33.6.77, executor 0, partition 6, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:21:15 INFO TaskSetManager: Starting task 7.0 in stage 0.0 (TID 7, 172.33.6.77, executor 0, partition 7, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:21:15 INFO TaskSetManager: Starting task 8.0 in stage 0.0 (TID 8, 172.33.6.77, executor 0, partition 8, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:21:15 INFO TaskSetManager: Finished task 4.0 in stage 0.0 (TID 4) in 33067 ms on 172.33.6.77 (executor 0) (1/11)
22/02/21 23:21:15 INFO TaskSetManager: Finished task 2.0 in stage 0.0 (TID 2) in 33071 ms on 172.33.6.77 (executor 0) (2/11)
22/02/21 23:21:15 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 33072 ms on 172.33.6.77 (executor 0) (3/11)
22/02/21 23:21:15 INFO TaskSetManager: Starting task 9.0 in stage 0.0 (TID 9, 172.33.6.77, executor 0, partition 9, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:21:15 INFO TaskSetManager: Finished task 5.0 in stage 0.0 (TID 5) in 33085 ms on 172.33.6.77 (executor 0) (4/11)
22/02/21 23:21:15 INFO TaskSetManager: Starting task 10.0 in stage 0.0 (TID 10, 172.33.6.77, executor 0, partition 10, PROCESS_LOCAL, 7861 bytes)
22/02/21 23:21:15 INFO TaskSetManager: Finished task 3.0 in stage 0.0 (TID 3) in 33088 ms on 172.33.6.77 (executor 0) (5/11)
22/02/21 23:21:15 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 33105 ms on 172.33.6.77 (executor 0) (6/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 6.0 in stage 0.0 (TID 6) in 77 ms on 172.33.6.77 (executor 0) (7/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 7.0 in stage 0.0 (TID 7) in 76 ms on 172.33.6.77 (executor 0) (8/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 8.0 in stage 0.0 (TID 8) in 78 ms on 172.33.6.77 (executor 0) (9/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 9.0 in stage 0.0 (TID 9) in 71 ms on 172.33.6.77 (executor 0) (10/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 10.0 in stage 0.0 (TID 10) in 70 ms on 172.33.6.77 (executor 0) (11/11)
22/02/21 23:21:16 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
22/02/21 23:21:16 INFO DAGScheduler: ShuffleMapStage 0 (distinct at SpreadRDDBuilder.scala:68) finished in 33.430 s
22/02/21 23:21:16 INFO DAGScheduler: looking for newly runnable stages
22/02/21 23:21:16 INFO DAGScheduler: running: Set()
22/02/21 23:21:16 INFO DAGScheduler: waiting: Set(ResultStage 1)
22/02/21 23:21:16 INFO DAGScheduler: failed: Set()
22/02/21 23:21:16 INFO DAGScheduler: Submitting ResultStage 1 (MapPartitionsRDD[4] at distinct at SpreadRDDBuilder.scala:68), which has no missing parents
22/02/21 23:21:16 INFO MemoryStore: Block broadcast_1 stored as values in memory (estimated size 3.8 KB, free 3.0 GB)
22/02/21 23:21:16 INFO MemoryStore: Block broadcast_1_piece0 stored as bytes in memory (estimated size 2.2 KB, free 3.0 GB)
22/02/21 23:21:16 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on QS016055Deploy.ehai.com:19419 (size: 2.2 KB, free: 3.0 GB)
22/02/21 23:21:16 INFO SparkContext: Created broadcast 1 from broadcast at DAGScheduler.scala:1184
22/02/21 23:21:16 INFO DAGScheduler: Submitting 11 missing tasks from ResultStage 1 (MapPartitionsRDD[4] at distinct at SpreadRDDBuilder.scala:68) (first 15 tasks are for partitions Vector(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
22/02/21 23:21:16 INFO TaskSchedulerImpl: Adding task set 1.0 with 11 tasks
22/02/21 23:21:16 INFO TaskSetManager: Starting task 6.0 in stage 1.0 (TID 11, 172.33.6.77, executor 0, partition 6, NODE_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 0.0 in stage 1.0 (TID 12, 172.33.6.77, executor 0, partition 0, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 1.0 in stage 1.0 (TID 13, 172.33.6.77, executor 0, partition 1, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 2.0 in stage 1.0 (TID 14, 172.33.6.77, executor 0, partition 2, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 3.0 in stage 1.0 (TID 15, 172.33.6.77, executor 0, partition 3, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 4.0 in stage 1.0 (TID 16, 172.33.6.77, executor 0, partition 4, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory on 172.33.6.77:33971 (size: 2.2 KB, free: 3.0 GB)
22/02/21 23:21:16 INFO MapOutputTrackerMasterEndpoint: Asked to send map output locations for shuffle 0 to 172.33.6.77:38952
22/02/21 23:21:16 INFO TaskSetManager: Starting task 5.0 in stage 1.0 (TID 17, 172.33.6.77, executor 0, partition 5, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 3.0 in stage 1.0 (TID 15) in 276 ms on 172.33.6.77 (executor 0) (1/11)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 7.0 in stage 1.0 (TID 18, 172.33.6.77, executor 0, partition 7, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 4.0 in stage 1.0 (TID 16) in 276 ms on 172.33.6.77 (executor 0) (2/11)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 8.0 in stage 1.0 (TID 19, 172.33.6.77, executor 0, partition 8, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 1.0 in stage 1.0 (TID 13) in 278 ms on 172.33.6.77 (executor 0) (3/11)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 9.0 in stage 1.0 (TID 20, 172.33.6.77, executor 0, partition 9, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Starting task 10.0 in stage 1.0 (TID 21, 172.33.6.77, executor 0, partition 10, PROCESS_LOCAL, 7668 bytes)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 0.0 in stage 1.0 (TID 12) in 280 ms on 172.33.6.77 (executor 0) (4/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 2.0 in stage 1.0 (TID 14) in 280 ms on 172.33.6.77 (executor 0) (5/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 6.0 in stage 1.0 (TID 11) in 297 ms on 172.33.6.77 (executor 0) (6/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 8.0 in stage 1.0 (TID 19) in 40 ms on 172.33.6.77 (executor 0) (7/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 9.0 in stage 1.0 (TID 20) in 40 ms on 172.33.6.77 (executor 0) (8/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 10.0 in stage 1.0 (TID 21) in 40 ms on 172.33.6.77 (executor 0) (9/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 5.0 in stage 1.0 (TID 17) in 47 ms on 172.33.6.77 (executor 0) (10/11)
22/02/21 23:21:16 INFO TaskSetManager: Finished task 7.0 in stage 1.0 (TID 18) in 47 ms on 172.33.6.77 (executor 0) (11/11)
22/02/21 23:21:16 INFO TaskSchedulerImpl: Removed TaskSet 1.0, whose tasks have all completed, from pool 
22/02/21 23:21:16 INFO DAGScheduler: ResultStage 1 (collect at SpreadRDDBuilder.scala:69) finished in 0.335 s
22/02/21 23:21:16 INFO DAGScheduler: Job 0 finished: collect at SpreadRDDBuilder.scala:69, took 33.836862 s
22/02/21 23:21:16 INFO SpreadRDDBuilder: Detected 1 spark executors for 1 H2O workers!
22/02/21 23:21:16 INFO TransportClientFactory: Successfully created connection to /172.33.6.77:39151 after 31 ms (0 ms spent in bootstraps)
22/02/21 23:21:19 ERROR TransportResponseHandler: Still have 1 requests outstanding when connection from /172.33.6.77:39151 is closed
22/02/21 23:21:19 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20220221232037-116709/0 is now EXITED (Command exited with code 255)
22/02/21 23:21:19 ERROR TaskSchedulerImpl: Lost executor 0 on 172.33.6.77: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
22/02/21 23:21:19 INFO StandaloneSchedulerBackend: Executor app-20220221232037-116709/0 removed: Command exited with code 255
22/02/21 23:21:19 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20220221232037-116709/1 on worker-20211130164651-172.33.6.77-40490 (172.33.6.77:40490) with 6 core(s)
22/02/21 23:21:19 INFO StandaloneSchedulerBackend: Granted executor ID app-20220221232037-116709/1 on hostPort 172.33.6.77:40490 with 6 core(s), 6.0 GB RAM
22/02/21 23:21:19 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20220221232037-116709/1 is now RUNNING
22/02/21 23:21:19 INFO DAGScheduler: Executor lost: 0 (epoch 1)
22/02/21 23:21:19 INFO BlockManagerMaster: Removal of executor 0 requested
22/02/21 23:21:19 INFO BlockManagerMasterEndpoint: Trying to remove executor 0 from BlockManagerMaster.
22/02/21 23:21:19 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asked to remove non-existent executor 0
22/02/21 23:21:19 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(0, 172.33.6.77, 33971, None)
22/02/21 23:21:19 INFO BlockManagerMasterEndpoint: Trying to remove executor 0 from BlockManagerMaster.
22/02/21 23:21:19 INFO BlockManagerMaster: Removed 0 successfully in removeExecutor
22/02/21 23:21:19 INFO DAGScheduler: Shuffle files lost for executor: 0 (epoch 1)
22/02/21 23:21:20 INFO BlockManagerInfo: Removed broadcast_1_piece0 on QS016055Deploy.ehai.com:19419 in memory (size: 2.2 KB, free: 3.0 GB)
22/02/21 23:21:20 INFO CodeGenerator: Code generated in 173.1058 ms
22/02/21 23:21:22 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.33.6.77:38986) with ID 1
22/02/21 23:21:22 INFO BlockManagerMasterEndpoint: Registering block manager 172.33.6.77:46088 with 3.0 GB RAM, BlockManagerId(1, 172.33.6.77, 46088, None)

**Comment by mn-mikke** [comment]
Hi @Damonsoul,
Can you share more details about the problem? Do you get any error? 

From the provided logs I can see that Spark app lost an executor and this may happen from various reasons. Would it be possible to share logs from Spark executors?

**Comment by Damonsoul** [comment]
@mn-mikke 
Thank you for your reply. More detailed logs and environment are attached
[R console error.txt](https://github.com/h2oai/sparkling-water/files/8110738/R.console.error.txt)
[spark executor log.txt](https://github.com/h2oai/sparkling-water/files/8110773/spark.executor.log.txt)
[environment.txt](https://github.com/h2oai/sparkling-water/files/8110777/environment.txt)

**Comment by krasinski** [comment]
that's how the executor dies:
`002-22 00:14:12.337 172.33.6.77:54321     17659  ent-loop-7 FATAL water.default: Unable to open hdfs configuration file /opt/spark-2.4.7/work/app-20220222001342-116722/0/./C:\Users\Administrator\AppData\Local\spark\spark-2.4.7-bin-hadoop2.7\tmp\local\spark-e557887d-1eac-470f-a6fc-963d2eaac39d\hdfs_conf7746215744220877489.xml`

so we have some really stange path here - windows path mixed with linux path

@Damonsoul 
can you please describe your environment a little bit more? are you running on a windows machine and submitting to an external linux spark cluster?

**Comment by Damonsoul** [comment]
yes，my local machine is windows 10.the external spark cluster is on the linux
@krasinski

**Comment by Damonsoul** [comment]
I created a hive-site.xml file  in my working directory,and run following r code:
h2oConf <- H2OConf()
h2oConf$setHdfsConf("hive-site.xml")
hc <- H2OContext.getOrCreate(h2oConf)

then connect h2o successfully.

the  hive-site.xml is as follows:
<configuration>
  <property>
    <name>hive.exec.scratchdir</name>
    <value>PUT HERE LOCATION OF TEMP FOLDER</value>
    <description>Scratch space for Hive jobs</description>
  </property>
</configuration>
@krasinski

**Comment by krasinski** [comment]
@Damonsoul apologies for the late response, Windows is a bit of a non-standard environment

I was able to successfully submit a job from a Windows machine to a Linux cluster with `spark.ext.h2o.hdfs_conf` set to a local windows path, the file was properly recognised and uploaded to the cluster.
I did encounter a similar to yours error message when I was passing a path to a non-existing file. I would suggest looking into file permissions, maybe moving the file to another location. You can even force spark to upload the file by using `addFile` method on spark context. The `setHdfsConf` method you mentioned just sets the `spark.ext.h2o.hdfs_conf` when passed a String.
