### ISSUE TITLE
cant't find souce code of H2OXGBoostClassifier or H2OAutoMLClassifier

### ISSUE THREAD

**Issue by HCMY** [h2oai/sparkling-water#2741]
hi there, I can't find any source code if H2OAutoMLClassifier、H2OXGBoostClassifier under the "ml/algos/" folder, and other source code too.  Is this part of code doesn't published?

**Comment by krasinski** [comment]
hello, those classes are auto generated during the build, and some others too. The most convenient way to browse the code would be to build the project, and then open it in an IDE like IntelliJ.

**Comment by HCMY** [comment]
thanks for reply,  i'll try! But..the auto generated code will be some .class file, dont't they? I'd like to read source code

**Comment by HCMY** [comment]
> @HCMY Nope, it will generate java classes first. After you compile SW, You can find it on the following paths.
> 
> * `./sparkling-water/ml/src-gen/main/scala/ai/h2o/sparkling/ml/algos/classification/H2OAutoMLClassifier.scala`
> * `./sparkling-water/ml/src-gen/main/scala/ai/h2o/sparkling/ml/algos/classification/H2OXGBoostClassifier.scala`

thanks a lot!
