### ISSUE TITLE
Where I can find the dockerfile of sparkling-water-python:3.36.0.3-1-3.1?

### ISSUE THREAD

**Issue by gurumoorthy208524** [h2oai/sparkling-water#2747]

**Comment by mn-mikke** [comment]
Hi @gurumoorthy208524, it's on [dockerhub](https://hub.docker.com/layers/sparkling-water-python/h2oai/sparkling-water-python/3.36.0.3-1-3.1/images/sha256-136e6ecaf8a3af1fc92d71569d8f39a8dd52fbed892b0189113243d332f9a824?context=explore).
