### ISSUE TITLE
Updating previously trained XGBoost

### ISSUE THREAD

**Issue by ottok92** [h2oai/sparkling-water#2777]
Hello, people.
How can we go about warm-starting/updating a previously trained XGBoost model?
Same question as [this closed issue](https://github.com/h2oai/sparkling-water/issues/22) but for XGBoost.

I see the argument "checkpoint" is ignored [here](https://github.com/h2oai/sparkling-water/blob/44db2ae3b91c279e117418956c7647cebb4a9601/api-generation/src/main/scala/ai/h2o/sparkling/api/generation/common/IgnoredParameters.scala#L38) but do not see any docs on why.

Alternatively, would loading previously trained model and calling fit on new data replicate the behavior or would it refresh the model as if it were boosting round zero?

**Comment by mn-mikke** [comment]
Hi @ottok92, 
checkpointing is not conceptually possible with SW API. SW API trains directly [MOJO models](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/save-and-load-model.html#mojo-models) which are meant for production environment. Checkpointing is based on  so called ["binary models"](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/save-and-load-model.html#binary-models) which require a running H2O clusters are rather meant for experiments and tuning.

If you want to utilize checkpointing, you would need to switch to  H2O-3 API to train an xgboost model. (see [this page](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/checkpointing-models.html#checkpoint-with-xgboost) for more details)

**Comment by ottok92** [comment]
Thank you for the quick reply @mn-mikke. I will make the switch to H2O-3 API for experimental models then.
