### ISSUE TITLE
Updating to scala 2.11

### ISSUE THREAD

**Issue by devldevelopment** [h2oai/sparkling-water#28]
Hi Guys
Great product for spark. Are there any plans to upgrade to scala 2.11? Before I go ahead and split out my projects for different versions?

Thanks

**Comment by MadMan0708** [comment]
Hi devldevelopment, 
  it's definitely on the roadmap and we plan to start working on it soon. I'll let you know when there's some change in development status. 

Thank you for your interest!

Kuba

**Comment by gridcellcoder** [comment]
Any progress on this, to include this on the roadmap?

**Comment by jangorecki** [comment]
@gridcellcoder I believe scala version will get updated on sparking water upgrade to spark 2.0.0, more on this in recent article on [linux.com](https://www.linux.com/news/sparkling-water-bridging-open-source-machine-learning-and-apache-spark).

**Comment by mmalohlava** [comment]
right now we are publishing scala_2.10, scala_2.11 artifacts for H2O scala API. The artifacts for Sparkling Water will follow shortly (aprox next week).

**Comment by jakubhava** [comment]
Hi all, right now when spark 2.0 is supported, we produce artefacts for scala 2.11. If you want to build sparkling water for spark 2.0 run gradle build with `-PscalaBaseVersion=2.10`  argument. I will close this one for now, if you have any issues, please file up a jira or contact us here.

**Comment by lev112** [comment]
Hi,
would it be possible to publish the sparkling water 2.0.0 with scala 2.10 to maven?
I see that only the 2.11 is published
thanks.

**Comment by mmalohlava** [comment]
Hi @lev112 , yes, we will release a new version soon as well.

**Comment by lev112** [comment]
Hi @mmalohlava,
any plans on publishing sparking water for scala 2.10?
the latest 2.10 published version is 1.6.8
thanks.
