### ISSUE TITLE
Save H2o Sparkling water models to Disk

### ISSUE THREAD

**Issue by webcluster4u** [h2oai/sparkling-water#2851]
I have a PySpark code to train an H2o DRF model. I need to save this model to disk and then load it.

```
from pysparkling.ml import H2ODRF
drf = H2ODRF(featuresCols = predictors,
                labelCol = response,
                columnsToCategorical = [response])
```
I can not find any document on this so I am asking this question here.

**Comment by mn-mikke** [comment]
Here is one example: https://docs.h2o.ai/sparkling-water/2.4/latest-stable/doc/deployment/pysparkling_pipeline.html

In general SW implepents spark pipeline API. So The SW models have the same methods as Model from Spark mllib: https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.ml.Pipeline.html
