### ISSUE TITLE
rsparkling weird connection to amazon?

### ISSUE THREAD

**Issue by randomgambit** [h2oai/sparkling-water#296]
Hello there,

Thanks for this amazing package. I have a HPC cluster with Spark and Sparkling Water installed. I am running the simple code:

```
library('sparklyr')
library('dplyr')
library('rsparkling')

Sys.setenv(SPARK_HOME="mypath/spark-2.0.2-bin-hadoop2.6/") 
sc <- spark_connect(master = "spark://node1234:7077")
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") : unable to connect to 's3.amazonaws.com' on port 80.
```

Why does `rsparkling` need to connect to amazon at all? I am behind a firewall so this is not possible.
Any ideas?

Thanks!

**Comment by jakubhava** [comment]
Hi @randomgambit, RSparkling has been moved to a different repository. Please post the question in https://github.com/h2oai/rsparkling. 

Thanks for understanding,

Kuba

**Comment by randomgambit** [comment]
done thanks!
