### ISSUE TITLE
Question/Observation Launching Instances

### ISSUE THREAD

**Issue by DarkBlaez** [h2oai/sparkling-water#31]
This might have to do with my setup but unsure which is why I will ask here...

I have a small standalone Spark Cluster consisting of 1 Master and 3 Workers. For normal tasks everything works just fine. I have compiled sparkling-water rel 1.6 for my version of Spark.

I have included the the sparkling-water jar in my spark-defaults.conf (spark.executor.extraClassPath and spark.driver.extraClassPath) across all Spark Workers and the Master

When I launch a spark-shell (remote or on master) and instantiate H2O
scala>
import org.apache.spark.h2o._
val h2oContext = H2OContext.getOrCreate(sc)
OR
val h2oContext = new H2OContext(sc).start(3)

I only get one instance which launches locally of H2O running on the node which I launched spark-shell

Is this the correct behavior? Most of the examples I have seen just launch instances locally on the same machine.

I was expecting instances to spin up on all workers, in this case 3 instances, 1 across each of the Spark Workers.

Am I missing something here? Please advise, and greatly appreciated , thanks

**Comment by mdymczyk** [comment]
@DarkBlaez how are you starting spark shell? Do you set `MASTER` env variable?

**Comment by jakubhava** [comment]
Closing since we haven't heard from @DarkBlaez for a while. Feel free to open new issue when you hit a new problem
