### ISSUE TITLE
pysparkling on zeppelin retrieve error

### ISSUE THREAD

**Issue by dark-spark2** [h2oai/sparkling-water#324]
Hi,
Running pysparkling on zeppelin returned:
Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-8681863745810614621.py", line 349, in <module>
    raise Exception(traceback.format_exc())
Exception: Traceback (most recent call last):
  File "/tmp/zeppelin_pyspark-8681863745810614621.py", line 337, in <module>
    exec(code)
  File "<stdin>", line 32, in <module>
  File "/tmp/spark-1a33dbdd-eecd-4b77-9e79-148d0f2f107d/userFiles-98022213-6cc1-4503-b746-0fae8925d298/h2o_pysparkling_2.1-2.1.9.zip/h2o/estimators/estimator_base.py", line 204, in train
    model.poll()
  File "/tmp/spark-1a33dbdd-eecd-4b77-9e79-148d0f2f107d/userFiles-98022213-6cc1-4503-b746-0fae8925d298/h2o_pysparkling_2.1-2.1.9.zip/h2o/job.py", line 53, in poll
    pb = ProgressBar(title=self._job_type + " progress", hidden=hidden)
  File "/tmp/spark-1a33dbdd-eecd-4b77-9e79-148d0f2f107d/userFiles-98022213-6cc1-4503-b746-0fae8925d298/h2o_pysparkling_2.1-2.1.9.zip/h2o/utils/progressbar.py", line 101, in __init__
    if file_mode is None: file_mode = not sys.stdout.isatty()
AttributeError: 'Logger' object has no attribute 'isatty'

Any idea ?
Thanks!

**Comment by jakubhava** [comment]
you need to have python package `colorama` with version at least  `0.3.8` or higher available

**Comment by dark-spark2** [comment]
It worked !
Thank you very much!

Rotem

**Comment by jakubhava** [comment]
@dark-spark2

No worries, happy to hear that helped. We put a runtime check for the correct colorama dependency into the latest h2o. That should eliminate these weird errors in the future.

Kuba

**Comment by Tagar** [comment]
We still get this error on latest colorama 0.3.9 too.
There was a PR to fix this on Zeppelin side too - https://github.com/apache/zeppelin/pull/2555

**Comment by jakubhava** [comment]
@Tagar Which Sparkling Water version are you using ? Can you verify that Spark is using the correct python version which has colorama 0.3.9 installed  ? ( I saw this error in environments where people updated colorama on one python version, however spark was picking up different version with older colorama )

Can you reproduce the same issue outside of Zeppelin environment ?

You can download sparkling water distribution from our page and then just follow PySparkling instructions http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/2/index.html .

You can run the ./bin/pysparkling script which will start spark context/spark session and you can start h2o services by

```
from pysparkling import *
hc = H2OContext.getOrCreate(spark)
```

Please let us know if it happens also in this case.

**Comment by Tagar** [comment]
@jakubhava we use Sparkling Water 2.2.1.

Nope we can't reproduce this outside of Zeppelin.
Zeppelin creates its own logger (notice `Logger` in the exception stack below) that doesn't define `isatty` attribute.

Notice it's only h2o's progress bar that fails:

```
m.train(x=train_x, y="RESPONSE", training_frame=train, validation_frame=valid)
```

produces 

> Fail to execute line 13: m.train(x=train_x, y="RESPONSE", training_frame=train, validation_frame=valid)
> Traceback (most recent call last):
>   File "/tmp/zeppelin_pyspark-5229389836262955294.py", line 333, in <module>
>     exec(code, _zcUserQueryNameSpace)
>   File "<stdin>", line 13, in <module>
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/estimators/estimator_base.py", line 208, in train
>     model.poll(verbose_model_scoring_history=verbose)
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/job.py", line 54, in poll
>     pb = ProgressBar(title=self._job_type + " progress", hidden=hidden)
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/utils/progressbar.py", line 100, in __init__
>     if file_mode is None: file_mode = not sys.stdout.isatty()
> AttributeError: 'Logger' object has no attribute 'isatty'

Workaround we found is to set 
```
import sys
sys.stdout.isatty = lambda : False
sys.stdout.encoding = None
```
in Zeppelin notebook before we call  SW API.

Ans yes we use latest colorama 0.3.9.

I have reviewed changes made in colorama from 0.3.7 to 0.3.9 and only one I see relevant is 
https://github.com/tartley/colorama/commit/44dc8af9bc8111b70dd046a822bb26c851ba3687#diff-45f96939f027f939f0ac9586847bb97a 

but that fix is for Windows terminals only? Which other colorama fix had to fix this?

Honestly I think this should be fixed in Zeppelin codebase as their customer loggers doesn't define `isatty` and `encoding` attributes, but that Zeppelin PR 2555 seems stalled. Would be great if H2O / Sparkling Water has a workaround for this build in. It could be just that two-liner I pasted above.

ps. Also, any way to disable progress bar in h2o model build? As its the only one that triggers this issue.

**Comment by jakubhava** [comment]
Hi @Tagar, 
 thanks a lot for this great explanation!

I asked the team if putting this workaround into h2o/Sparkling Water would be an option.

Regarding disabling the progress bar, we have this method
```
h2o.h2o.no_progress()
```
Disable the progress bar from flushing to stdout. The completed progress bar is printed when a job is complete so as to demarcate a log file.

**Comment by jakubhava** [comment]
Hi @Tagar , we are working on this PR https://github.com/h2oai/h2o-3/pull/1705/files which should resolve the issue on H2O/PySparkling side.

**Comment by Tagar** [comment]
Thanks a lot @jakubhava

**Comment by jakubhava** [comment]
@Tagar So the PR above was already merged into master and will be in the next H2O's release on which new Sparkling Water version will be based
