### ISSUE TITLE
Problems with hc.as_spark_frame. Missing column in spark frame

### ISSUE THREAD

**Issue by Jordi-Nadal** [h2oai/sparkling-water#343]
Hello,

I found a problem when trying to export a H2OFrame to (Py) Spark dataframe as:

[...]
predicted = h2o_km.predict(h2o_data)
h2o_data["PREDICTED"] = predicted

data = hc.as_spark_frame(h2o_data)
data["PREDICTED"]             < <---- This variable is missing
[...]

Am I missing something?

Thanks a lot in advance,
Jordi

+ info:
H2O cluster version: | 3.10.4.7
Python version: | 2.7.13 final

**Comment by jakubhava** [comment]
Hi @Jordi-Nadal, this is not a proper way how to do what you're trying to do.

the `predicted = h2o_km.predict(h2o_data)` call will return a frame with a single column containing predicted data.

To create a new frame with the combined input & predicted data, you need to do:
```combined = h2o_data.cbind(predicted)```

Here, the `combined` dataframe contains the predictions as the last column. To get the name of the columns you can run `combined.describe`

They you can do the conversion `data = hc.as_spark_frame(combined)`

Hope this helps,

Kuba

**Comment by Jordi-Nadal** [comment]
That's great & works! Thanks a lot.

Jordi

**Comment by jakubhava** [comment]
No worries, happy to hear it works 👍
