### ISSUE TITLE
Sparkling Water1.6.8 on CDH 5.12's Spark 1.6

### ISSUE THREAD

**Issue by mughilanand** [h2oai/sparkling-water#348]
Getting below error when creating H2O content

```
scala> val h2oContext = new H2OContext(sc).start()
<console>:30: error: constructor H2OContext in class H2OContext cannot be accessed in class $iwC
         val h2oContext = new H2OContext(sc).start()

```

**Comment by jakubhava** [comment]
Hi @mughilanand, 

The correct way how to create `H2OContext` is `val h2oContext = H2OContext.getOrCreate(spark)`

Also I would suggest using newer Sparkling Water built either for Spark 2.1 or Spark 2.0. Sparkling Water for Spark 1.6 is no longer updated.

**Comment by mughilanand** [comment]
scala> import org.apache.spark.h2o._
import org.apache.spark.h2o._
```
Hi jakubhava - I tried the way you advised but still getting error. Thanks

scala> val h2oContext = H2OContext.getOrCreate(spark)
<console>:28: error: not found: value spark
         val h2oContext = H2OContext.getOrCreate(spark)
```

**Comment by jakubhava** [comment]
ups, sorry. SparkSession is available only in Spark 2.0+ and you are Spark 1.6.  Please go for `val h2oContext = H2OContext.getOrCreate(sc)`. I would also suggest reading Spark and our Sparkling Water documentation.

Kuba

**Comment by jakubhava** [comment]
This problem is fixed in Sparkling Water 1.6.9. I would strongly suggest updating to Sparkling Water 2.1.12 for Spark 2.1 or Sparkling Water 2.0.13 for Spark 2.0 or 

If you need to stick with Spark 1.6, then please upgrade to Sparkling Water 1.6.12 where this problem should not occur anymore.

**Comment by mughilanand** [comment]
thanks for your info :)

**Comment by jakubhava** [comment]
No worries, happy to help :)  I'm closing this issue for now. If you have any more problems even with the upgraded version, please let us now
