### ISSUE TITLE
How to change Ivy cache location?

### ISSUE THREAD

**Issue by rexhu100** [h2oai/sparkling-water#372]
Hi, 

Sparkling Water tries to create its Ivy cache in $HOME/.ivy2 by default. However, I have very little space quota in this location. Is there a way for me to change that?

I apologize in advance if this question is naive, but I am quite a novice when it comes to Ivy.

Thanks!

**Comment by mmalohlava** [comment]
Hi @rexhu100 , this is default behavior of Spark, the option was provided in version 2.2.0 (see here https://issues.apache.org/jira/browse/SPARK-17568). If you are using older version, i would recommend to create a symlink from $HOME/.ivy2 to a location with higher space quota.

**Comment by rexhu100** [comment]
I use Spark 2.0.0, and the symlink method works! Thank you!
