### ISSUE TITLE
Does XGBoost work with Sparkling Water?

### ISSUE THREAD

**Issue by renegademonkey** [h2oai/sparkling-water#399]
Hi there,

I am trying to run XGBoost with sparklyr (6.3) and h2o (3.14.02) using sparkling water (rsparkling 2.2) on a Spark (2.2) cluster (with grid param search), but I am getting the following errors:

` [2017-10-02 15:05:09] failure_stack_traces: water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for XGBoost model: depth_grid_xgboost_small_model_9.  Details: ERRR on field: XGBoost: XGBoost is not available!`

I've tried to find documentation on similar issues, but I haven't found anyone using h2o's implementation of the XGBoost backend on Spark - is this not implemented yet, or am I missing something? Happy to provide reproducable code if this is supposed to be working already.

**Comment by jakubhava** [comment]
Hi @renegademonkey, XGBoost is currently supported only in local mode. We are still working on a distributed implementation. In sparkling water, it means that you can use XGBoost in `MASTER=local` mode. 

But I still haven't tried that from RSparkling. Can you please ensure you run in local mode and try again ? Thanks!

**Comment by jakubhava** [comment]
small update to be sure: Just tried on the latest Sparkling Water and can assure that XGBoost works in Sparkling Water in local mode, please let me know how it works in RSparkling when you have some time.

**Comment by renegademonkey** [comment]
Hi @jakubhava - thanks for the prompt response. I was afraid that this was the case, unfortunately I need to run this on a Spark cluster because of the large data sizes involved, so running XGBoost  local mode won't help me in this case.

**Comment by benmccann** [comment]
I see the h20 docs say that multi-node has beta support. Is this true in sparkling water as well then? What does it mean for something to be a beta feature? We do have to do anything special to enable it or is it automatically available and we should just expect some level of rough edges / bugs?

http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/xgboost.html
