### ISSUE TITLE
This H2O node couldn't find the file(s) to parse. Please check files and/or working directories.

### ISSUE THREAD

**Issue by venkateshmadala** [h2oai/sparkling-water#402]
Hi Team, I am getting below error when I tried to parse HDFS file from sparkling water cluster nodes(in H2O flow). It is working fine for me in standalone mode and I am able to import hdfs file and parse and run the parse job in sparkling water (H2O flow). 
Our requirement is:
Import the file from hdfs file system to H2O flow.
Parse the file, run the job and generating data frame.
I have tried these combinations
Spark: 1.6.2 and Sparkling water 1.6.13 
Spark 2.0.2 and Sparkling water 2.0.15
same H2O flow is working fine for S3 bucket and local file system. only facing issue with hdfs file system.
Note: H2O context is running on spark cluster. I am able to open Open H2O Flow in browser. 
Sparkling Water Context:
  H2O name: h2o-cluster
  cluster size: 2
  list of used nodes:
  (executorId, host, port)
  ------------------------
  (1,host1,54321)
  (0,host-2,54321)
  ------------------------
  Open H2O Flow in browser: http://host-2:54323 (CMD + click in Mac OSX)
====================================================
ERRR: DistributedException from <--- H2ONode --->:54321: 'This H2O node couldn't find the file(s) to parse. Please check files and/or working directories.', caused by java.lang.RuntimeException: This H2O node couldn't find the file(s) to parse. Please check files and/or working directories.
ERRR:         at water.MRTask.getResult(MRTask.java:478)
ERRR:         at water.MRTask.getResult(MRTask.java:486)
ERRR:         at water.MRTask.doAll(MRTask.java:402)
ERRR:         at water.parser.ParseSetup.guessSetup(ParseSetup.java:269)
ERRR:         at water.api.ParseSetupHandler.guessSetup(ParseSetupHandler.java:40)
ERRR:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ERRR:         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
ERRR:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ERRR:         at java.lang.reflect.Method.invoke(Method.java:498)
ERRR:         at water.api.Handler.handle(Handler.java:63)
ERRR:         at water.api.RequestServer.serve(RequestServer.java:448)
ERRR:         at water.api.RequestServer.doGeneric(RequestServer.java:297)
ERRR:         at water.api.RequestServer.doPost(RequestServer.java:223)
ERRR:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
ERRR:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
ERRR:         at ai.h2o.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
ERRR:         at ai.h2o.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
ERRR:         at ai.h2o.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
ERRR:         at ai.h2o.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
ERRR:         at ai.h2o.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
ERRR:         at ai.h2o.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
ERRR:         at ai.h2o.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
ERRR:         at ai.h2o.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
ERRR: Caused by: java.lang.RuntimeException: This H2O node couldn't find the file(s) to parse. Please check files and/or working directories.
ERRR:         at water.parser.ParseSetup$GuessSetupTsk.map(ParseSetup.java:410)
ERRR:         at water.MRTask.compute2(MRTask.java:601)
ERRR:         at water.H2O$H2OCountedCompleter.compute1(H2O.java:1258)
ERRR:         at water.parser.ParseSetup$GuessSetupTsk$Icer.compute1(ParseSetup$GuessSetupTsk$Icer.java)
ERRR:         at water.H2O$H2OCountedCompleter.compute(H2O.java:1254)
ERRR:         at jsr166y.CountedCompleter.exec(CountedCompleter.java:468)
ERRR:         at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:263)
ERRR:         at jsr166y.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:974)
ERRR:         at jsr166y.ForkJoinPool.runWorker(ForkJoinPool.java:1477)
ERRR:         at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)

**Comment by jakubhava** [comment]
Hi @venkateshmadala,
 can you please share the code you use to create a new H2OFrame from HDFS ?

Thanks, Kuba

**Comment by venkateshmadala** [comment]
@jakubhava Thanks for reverting back at the earliest. below is the code which we are testing.
import org.apache.spark.h2o._
val h2oContext = H2OContext.getOrCreate(sc)  //we are seeing h2o context created 
val h2oFrame = new H2OFrame(new java.net.URI("hdfs://hadoop-node1:8020/tmp/allyears2k.csv")) // getting mentioned error while executing this line

we tried loading this file in clustered sparkling-water H2O web interface. we are getting same issue there also. 
Hadoop hdfs is kerberised and we are executing the script with valid kerberos ticket. 
Same script is working in standalone mode and we are able to parse the hdfs file in standalone sparkling-water H2O webui. just to update one more time this distribution error is coming only for HDFS file but same is working for s3 bucket.

**Comment by mmalohlava** [comment]
@venkateshmadala quick question - are you able to process data via spark? Are you able to run ```sc.textFile("hdfs://hadoop-node1:8020/tmp/allyears2k.csv").count()```?

**Comment by jakubhava** [comment]
Hi @venkateshmadala, do you please have any update on the issue ? Does the command above works fo you ? 

Thanks, Kuba

**Comment by jakubhava** [comment]
Hi @venkateshmadala please let us know if you have any more updates on this. We would be happy to help. However I'm closing this issue for now as there hasn't been any input for a while.

Thanks, Kuba
