### ISSUE TITLE
how to export mojo model in java

### ISSUE THREAD

**Issue by Du-Li** [h2oai/sparkling-water#445]
According to [this article](https://github.com/h2oai/h2o-3/blob/master/h2o-docs/src/product/productionizing.rst), it seems a (GBM) model can be exported in MOJO as a zip file that can be loaded directly without the need to compile generated source code as does in POJO. However, the article only gives examples in R and python. Can you show an example in java?  I tried a few options with method model.getMojo.writeTo() but it failed with different exceptions.

**Comment by jakubhava** [comment]
Hi @Du-Li , you can use this method https://github.com/h2oai/sparkling-water/blob/34a605fce22cbbab1bffc9d99caacadf9c9cdd29/core/src/main/scala/water/support/ModelSerializationSupport.scala#L29 . 

Kuba

**Comment by Du-Li** [comment]
Thanks @jakubhava 

I tried the following that is the same as ModelSerializationSupport.exportMojoModel()
`val uri = URI.create("file:/Users/dli/tmp/gbmmodel.zip")`
`val destFile = new File(uri)`
`val fos = new FileOutputStream(destFile)`
`model.getMojo.writeTo(fos)`

But it failed with exception `water.exceptions.H2ONotFoundArgumentException: Failed to find schema for version: 3 and type: GBMModel`

Do you know what's the right way to pass the destination argument of exportMojoModel(model, destination)?

**Comment by jakubhava** [comment]
Hi @Du-Li , it's not definitely the same. The code of the method I shared is

```     
def exportH2OModel(model: Model[_, _, _], destination: URI): URI = {
    val modelKey = model._key.asInstanceOf[Key[_ <: Keyed[_ <: Keyed[_ <: AnyRef]]]]
    val p: Persist = H2O.getPM.getPersistForURI(destination)
    val os: OutputStream = p.create(destination.toString, true)
    model.writeAll(new AutoBuffer(os, true)).close

    destination
  }
``` Can you please give a try to this method first before trying different solutions ? 

Thanks

**Comment by Du-Li** [comment]
@jakubhava Sorry for the confusion but I thought my question was about how to export MOJO model.

I tried this method exportH2OModel() and it worked without any issue. However, the method requires a h2o context, so it can only be used in the spark driver. 

What I am trying to do is to load the model from spark executors so as to make lots of predictions in parallel. So either POJO or MOJO seems the way to go. I tried POJO, it worked but requires an extra step to compile the generated source code. By h2o documentation, it seems MOJO could avoid this extra step, so I want to give it a try but it's unclear how to export MOJO model in JVM.

**Comment by jakubhava** [comment]
@Du-Li oh, my bad, sorry. I was the confused one :)

Let me test the `exportMojoModel` method on `GBM` if I can reproduce the error.

**Comment by jakubhava** [comment]
So tested the method and works fine.

Can you please share full reproducible code for the error you're getting ? That would help a lot! Thanks

**Comment by Du-Li** [comment]
@jakubhava Following is the code I actually used, in which model is just a trained GBM model.
`val uri = URI.create("file:/Users/dli/tmp/gbmmodel.zip")
val destFile = new File(uri)
val fos = new FileOutputStream(destFile)
model.getMojo.writeTo(fos)`

**Comment by Du-Li** [comment]
@jakubhava Did you use a similar uri as I gave above? Which version of h2o did you use?

**Comment by jakubhava** [comment]
I'm using Sparkling Water 2.2.2 and the URI is not relevant. It's just location where your mojo is saved.h

Without the full reproducible code, we can't debug this

**Comment by Du-Li** [comment]
@jakubhava I am using an older version 1.6x of sparkling water. Will try it out on 2.2 and let you know. Thanks.

**Comment by jakubhava** [comment]
Hi @Du-Li any new updates on this ?

**Comment by jakubhava** [comment]
Closing this issue as there is no response on this and we don't have full reproducible code.

**Comment by venkim** [comment]
I see the same issue.
