### ISSUE TITLE
Sparkling Water from Livy?

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#449]
Was trying to find documentation but there seems to be none if it's possible to integrate Sparking Water with a Livy session? Any references will be extremely helpful.

**Comment by jakubhava** [comment]
Hi @Tagar, currently there is no documentation for it and I even haven't tried it.

But I think that in case we provide correct dependencies to Spark as usual ( sparkling-water jar in case of Scala, PySparkling zip file in case of python ) it should be fine. 

In Livy you can execute arbitrary Scala code using the rest api, therefore you can also execute Sparkling Water code.

If you decide to experiment with it, anything what you could share or even write up small doc would be very appreciated. I created a JIRA for it https://0xdata.atlassian.net/browse/SW-587. Current sparkling water documentation is available here https://github.com/h2oai/sparkling-water/tree/master/doc with https://github.com/h2oai/sparkling-water/blob/master/doc/DEVEL.rst as the main dispatch file.

**Comment by mmalohlava** [comment]
@tagar following @jakubhava answer. There should be not technical obstacles - if i am correct, Livy is already used in MS Azure.

**Comment by Tagar** [comment]
Thank you @jakubhava and @mmalohlava ! Good to know it's possible. We will give it a try.

Thanks for creating that jira and refernecing the dependencies required - that's really helpful.

**Comment by jakubhava** [comment]
No worries. I will close this issue for now. If you hit any specific issues related to Livy please let us know.
