### ISSUE TITLE
pysparkling making malformed url for window version

### ISSUE THREAD

**Issue by RobinTPotter** [h2oai/sparkling-water#457]
when spark session is opened in windows, the library is imported and the H2OConf created there's an exception from py4j about a malformed url for the sparkling_water_assembly.jar. we traced this to the initializer script and added an extra / to make file:///

forked and changed:

https://github.com/h2oai/sparkling-water/compare/master...RobinTPotter:patch-1#diff-187ac98a16a3071877fc6aa7da10fb3f

**Comment by jakubhava** [comment]
Hi @RobinTPotter,
 thanks for the investigation. Can you please create Pull Request ?

**Comment by RobinTPotter** [comment]
thanks @jakubhava - I just did. https://github.com/h2oai/sparkling-water/pull/458 happy to take feedback

**Comment by jakubhava** [comment]
Thanks! I'll close this, let's continue in the PR
