### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.getUserJars(Lorg/apache/spark/SparkConf;Z)Lscala/collection/Seq; using HDP 2.6/spark 2.2/scala 2.11 / YARN

### ISSUE THREAD

**Issue by fredyvilla** [h2oai/sparkling-water#486]
I'm getting the following error trying to run sparkling-water-2.2.4 in Hortonworks 2.6 running Spark 2,2, YARN and scala 2.11.  I get the following:

vagrant@thermalx1:~/sparkling-water-2.2.4$ bin/sparkling-shell --conf "spark.executor.memory=1g"

-----
  Spark master (MASTER)     : local
  Spark home   (SPARK_HOME) : /usr/hdp/current/spark2-client
  H2O build version         : 3.16.0.2 (wheeler)
  Spark build version       : 2.2.0
  Scala version             : 2.11
----

Warning: Ignoring non-spark config property: yarn.timeline-service.enabled=false
Warning: Ignoring non-spark config property: hadoop.yarn.timeline-service.enabled=false
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Spark context Web UI available at http://192.168.1.79:4040
Spark context available as 'sc' (master = local, app id = local-1512896128325).
Spark session available as 'spark'.
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.2.0.2.6.3.0-235
      /_/

Using Scala version 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112)
Type in expressions to have them evaluated.
Type :help for more information.

scala> import org.apache.spark.h2o._
import org.apache.spark.h2o._

scala> val hc = H2OContext.getOrCreate(sc)
17/12/10 00:55:38 WARN H2OContext: Method H2OContext.getOrCreate with an argument of type SparkContext is deprecated and parameter of type SparkSession is preferred.
17/12/10 00:55:39 WARN InternalH2OBackend: Increasing 'spark.locality.wait' to value 30000
17/12/10 00:55:39 WARN InternalH2OBackend: Due to non-deterministic behavior of Spark broadcast-based joins
We recommend to disable them by
configuring `spark.sql.autoBroadcastJoinThreshold` variable to value `-1`:
sqlContext.sql("SET spark.sql.autoBroadcastJoinThreshold=-1")
12-10 00:55:40.868 192.168.1.79:54321    57922  #r thread INFO: Found XGBoost backend with library: xgboost4j
12-10 00:55:40.889 192.168.1.79:54321    57922  #r thread INFO: Your system supports only minimal version of XGBoost (no GPUs, no multithreading)!
12-10 00:55:40.889 192.168.1.79:54321    57922  #r thread INFO: ----- H2O started  -----
12-10 00:55:40.889 192.168.1.79:54321    57922  #r thread INFO: Build git branch: rel-wheeler
12-10 00:55:40.889 192.168.1.79:54321    57922  #r thread INFO: Build git hash: 1de6d68cab3cfe79531fc68b28d96b938d194ca1
12-10 00:55:40.889 192.168.1.79:54321    57922  #r thread INFO: Build git describe: jenkins-3.16.0.1-13-g1de6d68cab
12-10 00:55:40.889 192.168.1.79:54321    57922  #r thread INFO: Build project version: 3.16.0.2 (latest version: 3.16.0.2)
12-10 00:55:40.890 192.168.1.79:54321    57922  #r thread INFO: Build age: 9 days
12-10 00:55:40.890 192.168.1.79:54321    57922  #r thread INFO: Built by: 'jenkins'
12-10 00:55:40.890 192.168.1.79:54321    57922  #r thread INFO: Built on: '2017-11-30 15:19:55'
12-10 00:55:40.890 192.168.1.79:54321    57922  #r thread INFO: Watchdog Build git branch: (unknown)
12-10 00:55:40.890 192.168.1.79:54321    57922  #r thread INFO: Watchdog Build git hash: (unknown)
12-10 00:55:40.890 192.168.1.79:54321    57922  #r thread INFO: Watchdog Build git describe: (unknown)
12-10 00:55:40.890 192.168.1.79:54321    57922  #r thread INFO: Watchdog Build project version: (unknown)
12-10 00:55:40.891 192.168.1.79:54321    57922  #r thread INFO: Watchdog Built by: (unknown)
12-10 00:55:40.891 192.168.1.79:54321    57922  #r thread INFO: Watchdog Built on: (unknown)
12-10 00:55:40.891 192.168.1.79:54321    57922  #r thread INFO: XGBoost Build git branch: (unknown)
12-10 00:55:40.891 192.168.1.79:54321    57922  #r thread INFO: XGBoost Build git hash: (unknown)
12-10 00:55:40.891 192.168.1.79:54321    57922  #r thread INFO: XGBoost Build git describe: (unknown)
12-10 00:55:40.891 192.168.1.79:54321    57922  #r thread INFO: XGBoost Build project version: (unknown)
12-10 00:55:40.892 192.168.1.79:54321    57922  #r thread INFO: XGBoost Built by: (unknown)
12-10 00:55:40.892 192.168.1.79:54321    57922  #r thread INFO: XGBoost Built on: (unknown)
12-10 00:55:40.892 192.168.1.79:54321    57922  #r thread INFO: Processed H2O arguments: [-name, sparkling-water-vagrant_local-1512896128325, -ga_opt_out, -log_level, INFO, -baseport, 54321, -ip, 192.168.1.79, -log_dir, /home/vagrant/sparkling-water-2.2.4/h2ologs/local-1512896128325]
12-10 00:55:40.892 192.168.1.79:54321    57922  #r thread INFO: Java availableProcessors: 4
12-10 00:55:40.892 192.168.1.79:54321    57922  #r thread INFO: Java heap totalMemory: 530.0 MB
12-10 00:55:40.892 192.168.1.79:54321    57922  #r thread INFO: Java heap maxMemory: 2.67 GB
12-10 00:55:40.893 192.168.1.79:54321    57922  #r thread INFO: Java version: Java 1.8.0_112 (from Oracle Corporation)
12-10 00:55:40.893 192.168.1.79:54321    57922  #r thread INFO: JVM launch parameters: [-Dhdp.version=2.6.3.0-235, -Dscala.usejavacp=true, -Xmx3G]
12-10 00:55:40.893 192.168.1.79:54321    57922  #r thread INFO: OS version: Linux 4.4.0-101-generic (amd64)
12-10 00:55:40.893 192.168.1.79:54321    57922  #r thread INFO: Machine physical memory: 7.62 GB
12-10 00:55:40.893 192.168.1.79:54321    57922  #r thread INFO: X-h2o-cluster-id: 1512896139317
12-10 00:55:40.893 192.168.1.79:54321    57922  #r thread INFO: User name: 'vagrant'
12-10 00:55:40.893 192.168.1.79:54321    57922  #r thread INFO: Opted out of sending usage metrics.
12-10 00:55:40.894 192.168.1.79:54321    57922  #r thread INFO: IPv6 stack selected: false
12-10 00:55:40.894 192.168.1.79:54321    57922  #r thread INFO: Possible IP Address: eth0 (eth0), 192.168.1.79
12-10 00:55:40.894 192.168.1.79:54321    57922  #r thread INFO: Possible IP Address: lo (lo), 127.0.0.1
12-10 00:55:40.894 192.168.1.79:54321    57922  #r thread INFO: H2O node running in unencrypted mode.
12-10 00:55:40.898 192.168.1.79:54321    57922  #r thread INFO: Internal communication uses port: 54322
12-10 00:55:40.898 192.168.1.79:54321    57922  #r thread INFO: Listening for HTTP and REST traffic on http://192.168.1.79:54321/
12-10 00:55:40.930 192.168.1.79:54321    57922  #r thread INFO: H2O cloud name: 'sparkling-water-vagrant_local-1512896128325' on /192.168.1.79:54321, discovery address /225.115.218.143:57715
12-10 00:55:40.930 192.168.1.79:54321    57922  #r thread INFO: If you have trouble connecting, try SSH tunneling from your local machine (e.g., via port 55555):
12-10 00:55:40.930 192.168.1.79:54321    57922  #r thread INFO:   1. Open a terminal and run 'ssh -L 55555:localhost:54321 vagrant@192.168.1.79'
12-10 00:55:40.930 192.168.1.79:54321    57922  #r thread INFO:   2. Point your browser to http://localhost:55555
12-10 00:55:41.073 192.168.1.79:54321    57922  #r thread INFO: Log dir: '/home/vagrant/sparkling-water-2.2.4/h2ologs/local-1512896128325'
12-10 00:55:41.073 192.168.1.79:54321    57922  #r thread INFO: Cur dir: '/home/vagrant/sparkling-water-2.2.4'
12-10 00:55:41.082 192.168.1.79:54321    57922  #r thread INFO: Using HDFS configuration from /usr/hdp/2.6.3.0-235/hadoop/conf
12-10 00:55:41.083 192.168.1.79:54321    57922  #r thread INFO: HDFS subsystem successfully initialized
12-10 00:55:41.088 192.168.1.79:54321    57922  #r thread INFO: S3 subsystem successfully initialized
12-10 00:55:41.088 192.168.1.79:54321    57922  #r thread INFO: Flow dir: '/home/vagrant/h2oflows'
12-10 00:55:41.102 192.168.1.79:54321    57922  #r thread INFO: Cloud of size 1 formed [thermalx1/192.168.1.79:54321]
12-10 00:55:41.160 192.168.1.79:54321    57922  #r thread INFO: Registered parsers: [GUESS, ARFF, XLS, SVMLight, AVRO, ORC, PARQUET, CSV]
12-10 00:55:41.160 192.168.1.79:54321    57922  #r thread INFO: Watchdog extension initialized
12-10 00:55:41.160 192.168.1.79:54321    57922  #r thread INFO: XGBoost extension initialized
12-10 00:55:41.161 192.168.1.79:54321    57922  #r thread INFO: Registered 2 core extensions in: 112ms
12-10 00:55:41.161 192.168.1.79:54321    57922  #r thread INFO: Registered H2O core extensions: [Watchdog, XGBoost]
12-10 00:55:41.741 192.168.1.79:54321    57922  #r thread INFO: Registered: 162 REST APIs in: 580ms
12-10 00:55:41.741 192.168.1.79:54321    57922  #r thread INFO: Registered REST API extensions: [XGBoost, Algos, AutoML, Core V3, Core V4]
12-10 00:55:41.913 192.168.1.79:54321    57922  #r thread INFO: Registered: 246 schemas in 170ms
12-10 00:55:41.913 192.168.1.79:54321    57922  #r thread INFO: H2O started in 1527ms
12-10 00:55:41.913 192.168.1.79:54321    57922  #r thread INFO:
12-10 00:55:41.914 192.168.1.79:54321    57922  #r thread INFO: Open H2O Flow in your web browser: http://192.168.1.79:54321
12-10 00:55:41.914 192.168.1.79:54321    57922  #r thread INFO:
java.lang.NoSuchMethodError: org.apache.spark.util.Utils$.getUserJars(Lorg/apache/spark/SparkConf;Z)Lscala/collection/Seq;
  at org.apache.spark.repl.h2o.H2OInterpreter.createSettings(H2OInterpreter.scala:66)
  at org.apache.spark.repl.h2o.BaseH2OInterpreter.initializeInterpreter(BaseH2OInterpreter.scala:101)
  at org.apache.spark.repl.h2o.BaseH2OInterpreter.<init>(BaseH2OInterpreter.scala:291)
  at org.apache.spark.repl.h2o.H2OInterpreter.<init>(H2OInterpreter.scala:42)
  at water.api.scalaInt.ScalaCodeHandler.createInterpreterInPool(ScalaCodeHandler.scala:100)
  at water.api.scalaInt.ScalaCodeHandler$$anonfun$initializeInterpreterPool$1.apply(ScalaCodeHandler.scala:94)
  at water.api.scalaInt.ScalaCodeHandler$$anonfun$initializeInterpreterPool$1.apply(ScalaCodeHandler.scala:93)
  at scala.collection.immutable.Range.foreach(Range.scala:160)
  at water.api.scalaInt.ScalaCodeHandler.initializeInterpreterPool(ScalaCodeHandler.scala:93)
  at water.api.scalaInt.ScalaCodeHandler.<init>(ScalaCodeHandler.scala:37)
  at water.api.scalaInt.ScalaCodeHandler$.registerEndpoints(ScalaCodeHandler.scala:132)
  at water.api.CoreRestAPI$.registerEndpoints(CoreRestAPI.scala:32)
  at water.api.RestAPIManager.register(RestAPIManager.scala:39)
  at water.api.RestAPIManager.registerAll(RestAPIManager.scala:31)
  at org.apache.spark.h2o.backends.internal.InternalH2OBackend.init(InternalH2OBackend.scala:119)
  at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:121)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:355)
  at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:390)
  ... 50 elided

**Comment by goosalex** [comment]
Looks like you are using Spark 2.2.1. They changed (SPARK 21714) the method signature between 2.2.0 and 2.2.1:
https://github.com/apache/spark/commit/1813c4a8dd4388fe76a4ec772c9be151be0f60a1#diff-d239aee594001f8391676e1047a0381eL2608
Quick workaround: downgrade.

**Comment by jakubhava** [comment]
Yup, thanks for pointing it out @goosalex. We still need to make sure that everything passes as expected on Spark 2.2.1. Here's the Jira to track progress of this issue https://0xdata.atlassian.net/browse/SW-629

**Comment by JeroenSchmidt** [comment]
Thank you @jakubhava.
We also encountered the same problem when we moved from Spark 2.1.1 to 2.2.1.
