### ISSUE TITLE
h2o/__init__.py: No such file or directory: .../h2o/version.txt

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#493]
Started getting this error after upgrading to SW 2.2.4:

```
from pysparkling import *
import h2o
hc = H2OContext.getOrCreate(spark)
```

> Fail to execute line 1: from pysparkling import *
> Traceback (most recent call last):
>   File "/tmp/zeppelin_pyspark-943274820172791510.py", line 333, in <module>
>     exec(code, _zcUserQueryNameSpace)
>   File "<stdin>", line 1, in <module>
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/pysparkling/__init__.py", line 11, in <module>
>     from pysparkling.context import H2OContext
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/pysparkling/context.py", line 5, in <module>
>     from h2o.frame import H2OFrame
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/__init__.py", line 39, in <module>
>     with open(path.join(here, 'version.txt'), encoding='utf-8') as f:
>   File "/opt/cloudera/parcels/Anaconda/lib/python2.7/codecs.py", line 896, in open
>     file = __builtin__.open(filename, mode, buffering)
> IOError: [Errno 2] No such file or directory: u'/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/h2o/version.txt'
> 

Any ideas how to fix this?

**Comment by Tagar** [comment]
I manually created version.txt file under that path with string "2.2.4" inside. 
Then was getting the same error regarding "buildinfo.txt" - created that file with one empty line.
It seems to be worked around the issue. 
2.2.4 pysparkling pip build seems to be broken in this sense?

**Comment by jakubhava** [comment]
It is fixed in the latest release 2.2.5 which will be officially published later today. Latest working version is already published  on pipy

**Comment by Tagar** [comment]
Thank you for prompt response @jakubhava

**Comment by jakubhava** [comment]
No worries - new sparkling water has been released
