### ISSUE TITLE
Splitting H2O DataFrame && org.apache.spark.ml.h2o.algos

### ISSUE THREAD

**Issue by spaszek** [h2oai/sparkling-water#570]
Hello,
two quick questions - what would be the equivalent of those calls in `Sparkling Water`? I feel like there is none.
Python:
```python
train, valid, test = data.split_frame([0.8, 0.2])
```
R:
```R
parts <- h2o.splitFrame(data, 0.8)
train <- parts[[1]]
test <- parts[[2]]
```
Scala:
```
//?
```

and the second one - why does `org.apache.spark.ml.h2o.algos` contain just `H2ODeepLearning` and `H2OGBM` models? is it possible to attach another H2O algorithm (for example Naive Bayes, XGBoost or GLM) in Spark's Pipeline?

If it's WIP - may I see the Jira's ticket? If not - are you guys open to contributions? I could try wrapping some of the H2O's algorithms into Spark(if it can be achieved in reasonable time considering I have no prior `Sparkling Water` experience :) )

**Comment by jakubhava** [comment]
Hi @spaszek,
 if you are using Scala API of Sparkling Water then you could use this helper method for splitting https://github.com/h2oai/sparkling-water/blob/e8378983a02eaf1dc5f730dc2089235cab488026/core/src/main/scala/water/support/H2OFrameSupport.scala#L32

Regarding the pipelines ->  You are correct, Currently, we have only Deeplearning and GBM ported to the Spark pipelines. I'm currently finishing porting AutoML to the Spark pipelines but work has not yet been started on the other ones so far.

We love open-source contribution. Even though this is a more technical task, it would be great to have all algorithms ported to the Spark pipelines. I would suggest with looking at the code of H2ODeeplearning for example.

We always need to port it to both Scala API and PySparkling. If you would like to give it a try you can experiment with KMeans - https://0xdata.atlassian.net/browse/SW-716. Feel free to ask me if you have any questions! 

Thank you!

**Comment by spaszek** [comment]
Wow, such a quick response!

Thanks for your answer.

As of KMeans - that sounds great and achievable. I will certainly give it a try. Let's move our discussion to Jira then!

**Comment by jakubhava** [comment]
Thanks @spaszek!

Do you have a JIRA account? If not, can you please create one and let me know the user name?

**Comment by spaszek** [comment]
@jakubhava 

I'm that guy in the comments: https://0xdata.atlassian.net/browse/SW-716 :)

**Comment by jakubhava** [comment]
@spaszek sorry, I missed that, you're there!

Thanks! Feel free to ping me if you need any help. I would start with the Scala API and then we can re-iterate it together before moving towards the python API. We can continue discussion on the attached Jira
