### ISSUE TITLE
changing default H2O port 

### ISSUE THREAD

**Issue by davidwangdw** [h2oai/sparkling-water#572]
Hello all,

I am trying to start a Sparkling Water instance with a custom port for H2O, due to corporate rules not allowing the port 54321. I am allowed to use port 443. How do I change the custom port used by H2O?

This is what I have tried so far:

`bin/sparkling-shell --conf "spark.ext.h2o.port.base=443`

I see it in the spark configuration info:

`thread INFO: The following Spark configuration is used: (spark.driver.memory,3G), (spark.app.id,local-1518537886474), (spark.home,/usr/lib/spark), (spark.driver.host,<IP-ADDRESS>), (spark.executor.id,driver), (spark.driver.port,37246), (spark.ext.h2o.port.base,443), (spark.repl.class.outputDir,/tmp/root/spark/work/spark-212df1d6-dc76-48b0-9ec9-529c38f9eae1/repl-8a817c90-8f71-40ed-8c47-47d3b7f674ab), (spark.app.name,Spark shell), (spark.sql.catalogImplementation,hive), (spark.locality.wait,30000), (spark.repl.local.jars,file:/usr/lib/sparkling-water/assembly/build/libs/sparkling-water-assembly_2.11-2.2.7-all.jar), (spark.ext.h2o.cloud.name,sparkling-water-root_local-1518537886474), (spark.ext.h2o.client.log.dir,/usr/lib/sparkling-water/h2ologs/local-1518537886474), (spark.master,local[*]), (spark.submit.deployMode,client), (spark.repl.class.uri,spark://<IP-ADDRESS>:37246/classes), (spark.ext.h2o.client.ip,<IP-ADDRESS>), (spark.driver.extraJavaOptions,), (spark.jars,file:/usr/lib/sparkling-water/assembly/build/libs/sparkling-water-assembly_2.11-2.2.7-all.jar)`

However, it looks like it's passing 54321 later anyway after I execute the Scala code:

`import org.apache.spark.h2o._
val h2oContext = H2OContext.getOrCreate(spark) `

Result:
`7774  #r thread INFO: Processed H2O arguments: [-name, sparkling-water-root_local-1518537886474, -ga_opt_out, -log_level, INFO, -baseport, 54321, -ip, <IP-ADDRESS>, -log_dir, /usr/lib/sparkling-water/h2ologs/local-1518537886474]`

Is there something I'm missing? Is there an additional configuration option to allow me to change the default port Sparkling Water/H2O uses?

Thanks for any help!

**Comment by jakubhava** [comment]
Hi @davidwangdw,
 the property is actually called `spark.ext.h2o.client.port.base"`, seems like you have missed the workd `client` in it

**Comment by davidwangdw** [comment]
hi @jakubhava thank you for the quick response!

I tried changing it as per your suggestion:

`bin/sparkling-shell --conf "spark.ext.h2o.client.port.base=443"`

Unfortunately it's still defaulting to 54321 though

**Comment by davidwangdw** [comment]
hi, I was able to get approval to use port 54321. After a day of troubleshooting I couldn't figure it out, so it must have been some configuration issue. Thank you for the help

**Comment by jakubhava** [comment]
Thanks @davidwangdw,

 it is actually `spark.ext.h2o.client.web.port` configuration property which should help. Sorry for giving wrong answer before

**Comment by axiomoixa** [comment]
How would I specify the port when I run `rsparkling`?

The default launch procedure is:
```
library(rsparkling)
## create spark instance: sc
h2o_context(sc)
library(h2o)
```

**Comment by jakubhava** [comment]
HI @axiomoixa , opening the issue on RSparkling project is fine - https://github.com/h2oai/rsparkling/issues/74 - no need to duplicate it here. Let's continue the discussion there.

Thanks!
