### ISSUE TITLE
Please publish Sparkling Water POM files with Spark project dependencies in the "provided", not "compile", scope

### ISSUE THREAD

**Issue by mallman** [h2oai/sparkling-water#577]
The Spark dependencies for Sparkling Water as of this writing are defined in the "compile" scope. For example, see http://search.maven.org/remotecontent?filepath=ai/h2o/sparkling-water-core_2.11/2.2.8/sparkling-water-core_2.11-2.2.8.pom. Spark apps run in a container that provides the API and implementation at runtime. Declaring Spark as a "compile" scope dependency can lead to the introduction of conflicting or duplicate classfiles at runtime. This is especially true when building "assembly" jars or "fat jars" which include compile dependencies for deployment, however this is also a problem when using a classloader that can load maven library dependencies at runtime (e.g. Ammonite). See https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope and http://ammonite.io/#import$ivy.

**Comment by jakubhava** [comment]
Hi @mallman, thanks for the report!

It would make sense to declare the spark dependencies as provided. I created JIRA for this where you can track the status of this issue. Also feel free to comment there - https://0xdata.atlassian.net/browse/SW-726. Thanks a lot!

**Comment by jakubhava** [comment]
I closed this ticket as we use JIRA for tracking state of the issues

**Comment by mallman** [comment]
Thank you @jakubhava! I've added myself as a watcher to that ticket and will respond to any questions.

**Comment by jakubhava** [comment]
Hi @mallman, the fix is going into master and will be in the next Sparkling Water release. Thanks!

**Comment by mallman** [comment]
Awesome, thanks!!!
