### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/pysparkling/version.txt'

### ISSUE THREAD

**Issue by clayms** [h2oai/sparkling-water#583]
When I try and import the python bindings, I get the following error:

```
IOError: [Errno 2] No such file or directory: '/pysparkling/version.txt'
IOErrorTraceback (most recent call last)
in engine
----> 1 from pysparkling import *

/pysparkling/__init__.py in <module>()
     17         __version__ = archive.read('pysparkling/version.txt').decode('utf-8').strip()
     18 else:
---> 19     with open(path.join(here, 'version.txt'), encoding='utf-8') as f:
     20         __version__ = f.read().strip()
     21 
```
I see the code was changed [here](https://github.com/h2oai/sparkling-water/commit/e66f1f88f30241f4f9ffeb1b465bf7954fbc96a0)

Do I need to create my own `/pysparkling/version.txt`  ?  If so, what is the format?

Thanks,

**Comment by clayms** [comment]
I commented out the following lines (15-20) in the `/pysparkling/__init__.py`  file and everything imported without errors.  I have not tried to run any functions yet.  Will this cause a problem?  Perhaps this code should either be removed from the distribution, or a `/pysparkling/version.txt` file should be included.

#if '.zip' in here:
#    with zipfile.ZipFile(path.dirname(here), 'r') as archive:
#        __version__ = archive.read('pysparkling/version.txt').decode('utf-8').strip()
#else:
#    with open(path.join(here, 'version.txt'), encoding='utf-8') as f:
#        __version__ = f.read().strip()

**Comment by jakubhava** [comment]
Hi @clayms, what PySparkling version are you using please ?

**Comment by jakubhava** [comment]
We also need more info such as how are you starting the application - are you using the prepared scripts for it? Are you installing pysparkling from pypi ?

**Comment by clayms** [comment]
Thanks @jakubhava 
Sorry I did not include. 

PySparkling version  2.2.8
I downloaded the python bindings from https://github.com/h2oai/sparkling-water/tree/rel-2.2/py/pysparkling and uploaded to my working directory on the cluster driver node.

I ran `pip install h2o_pysparkling_2.2` from the driver node terminal. 

I am probably not using the prepared scripts correctly.  I have been continuing to try and get it to work with the following.  (with lines 15-20 commented out in the `/pysparkling/__init__.py` file)

```
import pyspark
spark = pyspark.sql.SparkSession\
.builder.master('yarn').appName('H2O_test')\
.config("spark.jars.packages","ai.h2o:sparkling-water-core_2.11:2.2.8,ai.h2o:sparkling-water-core_2.11:2.2.8")\
.config("spark.dynamicAllocation.enabled", True)\
.getOrCreate()

from pysparkling import *
import h2o
hc = H2OContext.getOrCreate(spark)
```

However, that generates the errors I submitted [here](https://github.com/h2oai/sparkling-water/issues/584).  That issue should contain enough information on my cluster configuration.

Thanks,

**Comment by pranavbethapudi** [comment]
I am getting the same error as @clayms. i did the same thing as mentioned above. i am running it through spark-submit.

**Comment by jakubhava** [comment]
@clayms thanks for sharing. This is however not supported way of installing PySparkling. PySparkling has a lot of other dependencies which are included as well during the build process.

@pranavbethapudi @clayms. 
You can either install pysparkling from the official `pip` page or download the official distribution from here http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/10/index.html
