### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 65535 at water.DKV.get(DKV.java:204) when trying to cache large dataset

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#597]
This happens when we try to pull a huge spark dataframe to h2o frame.
63m records x 6300 columns.
Although H2O/ Sparkling Water cluster sized properly: (there are 40 executors x 17g of memory each, and each Spark executor has 4 threads/ cores)
So total amount of memory is 680Gb; total number of spark cores - 160.
This parquet table (from which we create Spark dataframe) is around 140Gb.

Spark 2.2 (from Cloudera).
CDH 5.12.

$ pip freeze | grep sparkling
h2o-pysparkling-2.2==2.2.7

> 
Py4JJavaError: An error occurred while calling o110.asH2OFrame. : org.apache.spark.SparkException: Job aborted due to stage failure: Task 366 in stage 8.0 failed 4 times, most recent failure: Lost task 366.3 in stage 8.0 (TID 4882, pc1udatahad17, executor 63): java.lang.ArrayIndexOutOfBoundsException: 65535 at water.DKV.get(DKV.java:204) at water.DKV.get(DKV.java:177) at water.Key.get(Key.java:84) at water.fvec.Frame.createNewChunks(Frame.java:985) at water.fvec.FrameUtils$class.createNewChunks(FrameUtils.scala:43) at water.fvec.FrameUtils$.createNewChunks(FrameUtils.scala:70) at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.createChunks(InternalWriteConverterCtx.scala:37) at org.apache.spark.h2o.converters.SparkDataFrameConverter$.org$apache$spark$h2o$converters$SparkDataFrameConverter$$perSQLPartition(SparkDataFrameConverter.scala:108) at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$1.apply(SparkDataFrameConverter.scala:82) at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$1.apply(SparkDataFrameConverter.scala:82) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) at org.apache.spark.scheduler.Task.run(Task.scala:108) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Driver stacktrace: at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487) at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486) at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814) at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814) at scala.Option.foreach(Option.scala:257) at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669) at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658) at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48) at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:630) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2022) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2043) at org.apache.spark.SparkContext.runJob(SparkContext.scala:2075) at org.apache.spark.h2o.converters.WriteConverterCtxUtils$.convert(WriteConverterCtxUtils.scala:85) at org.apache.spark.h2o.converters.SparkDataFrameConverter$.toH2OFrame(SparkDataFrameConverter.scala:81) at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:199) at org.apache.spark.h2o.H2OContext$$anonfun$asH2OFrame$2.apply(H2OContext.scala:199) at org.apache.spark.h2o.utils.H2OContextUtils$class.withConversionDebugPrints(H2OContextUtils.scala:76) at org.apache.spark.h2o.H2OContext.withConversionDebugPrints(H2OContext.scala:64) at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:199) at org.apache.spark.h2o.H2OContext.asH2OFrame(H2OContext.scala:200) at org.apache.spark.h2o.JavaH2OContext.asH2OFrame(JavaH2OContext.java:101) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.apache.zeppelin.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231) at org.apache.zeppelin.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381) at org.apache.zeppelin.py4j.Gateway.invoke(Gateway.java:290) at org.apache.zeppelin.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133) at org.apache.zeppelin.py4j.commands.CallCommand.execute(CallCommand.java:79) at org.apache.zeppelin.py4j.GatewayConnection.run(GatewayConnection.java:209) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.ArrayIndexOutOfBoundsException: 65535 at water.DKV.get(DKV.java:204) at water.DKV.get(DKV.java:177) at water.Key.get(Key.java:84) at water.fvec.Frame.createNewChunks(Frame.java:985) at water.fvec.FrameUtils$class.createNewChunks(FrameUtils.scala:43) at water.fvec.FrameUtils$.createNewChunks(FrameUtils.scala:70) at org.apache.spark.h2o.backends.internal.InternalWriteConverterCtx.createChunks(InternalWriteConverterCtx.scala:37) at org.apache.spark.h2o.converters.SparkDataFrameConverter$.org$apache$spark$h2o$converters$SparkDataFrameConverter$$perSQLPartition(SparkDataFrameConverter.scala:108) at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$1.apply(SparkDataFrameConverter.scala:82) at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$1.apply(SparkDataFrameConverter.scala:82) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) at org.apache.spark.scheduler.Task.run(Task.scala:108) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ... 1 more

**Comment by Tagar** [comment]
Exception stack matches https://github.com/h2oai/sparkling-water/issues/182

**Comment by Tagar** [comment]
This exception also matches (somewhat dated) conversation on google groups - https://groups.google.com/forum/#!topic/h2ostream/TEiz13V1ST0

**Comment by jakubhava** [comment]
Hi @Tagar,
 seems like one of the Spark executors died. Without any further logs, I would say that at this Scale it would make sense to have a look at the External backend which is solving this issue http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/deployment/backends.html

**Comment by Tagar** [comment]
Yep, seems this exception can happen after an executor is lost (due to various reasons, like it ran out of memory etc). Thanks @jakubhava !

Sparkling Water doesn't support Spark Dynamic allocation nor YARN preemption so we already had to hoard away resources away already from other users.. if we also have to create a static External backend it'll be very resource inefficient for us. 

Are there any fine tuning we can / should do for such a big dataset?

**Comment by jakubhava** [comment]
Hi @Tagar, we have this tuning guide for internal backend -> http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/configuration/internal_backend_tuning.html

**Comment by Tagar** [comment]
Thank you for pointing to that documentation, @jakubhava . It was great to meet and chat with you at Strata Data conference! 

What would be memory estimate for an h2o cluster to fir data with below schema? 
We tried 680Gb and SW still gives oom issues.. Please see schema in the xlsx file:

[wideschema_6316.xlsx](https://github.com/h2oai/sparkling-water/files/1804577/wideschema_6316.xlsx)

There are over 6300 columns with total combined number of distinct values of all those columns around 260 million. This is a lot if h2o converts most of those columns to categorical variables. Notice all columns (except very 1st one which is an id column) have datatype `double`. What logic does h2o apply to `double` datatype to detect if it actually encodes categorical features? I heard there is a threshold for cardinality, below which h2o will consider a column to be categorical/factor column? Can't find anywhere what that threshold is. 

cc @mmalohlava as we chattedon this with him a bit too.

Thank you both !

**Comment by Tagar** [comment]
Same dataset after it was converted to an h2o frame - 

![ccb8904d](https://user-images.githubusercontent.com/3013418/37492511-4b20368a-2867-11e8-9422-6d66f07a9a36.PNG)

None of the columns got converted to `categorical` so looks like H2O always assume non-categorical for `float` input data type?

**Comment by Tagar** [comment]
@jakubhava I tried both internal mode tuning 
and external backend mode .. the latter unfortunately has its own issues 
https://github.com/h2oai/sparkling-water/issues/625, https://github.com/h2oai/sparkling-water/issues/626 
It seems we're running into an issue after an issues when trying to deal with wide datasets. Any ideas?

**Comment by jakubhava** [comment]
Just responded on those 2 tickets
