### ISSUE TITLE
OOM - workarounds for widedatasets

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#598]
We have a 130Gb parquet table trying to build a simple GLM model and getting OOMs.
40 executors x 17Gb spark.executor.memory each = 680Gb.
Would you recommend some fine tuning for this (larger) dataset? 
There are 63m records x 6300 columns in this dataset.
Is there is something special would you recommend for this larger dataset?

Also, would you recommend some particular settings for ```spark.memory.fraction``` and ```spark.memory.storageFraction```? I think we should set at least ```spark.memory.storageFraction``` to a much lower value as we don't use Spark caching when we run Sparkling Water - data is in-memoried with h2o frames. Similarly, ```spark.memory.fraction``` should be lowered so more memory is available for H2O which lives in the same JVMs as Spark executors.

One of yarn container logs:

> 03-06 09:03:50.997 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:5.40 GB + FREE:2.37 GB == MEM_MAX:17.00 GB), desiredKV=6.21 GB OOM!
> 03-06 09:04:05.471 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:5.92 GB + FREE:1.84 GB == MEM_MAX:17.00 GB), desiredKV=5.16 GB OOM!
> 03-06 09:04:08.945 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:6.25 GB + FREE:1.51 GB == MEM_MAX:17.00 GB), desiredKV=4.49 GB OOM!
> 03-06 09:04:13.337 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:6.53 GB + FREE:1.23 GB == MEM_MAX:17.00 GB), desiredKV=3.94 GB OOM!
> 03-06 09:04:16.265 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:6.80 GB + FREE:989.7 MB == MEM_MAX:17.00 GB), desiredKV=3.40 GB OOM!
> 03-06 09:04:27.295 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:6.98 GB + FREE:807.3 MB == MEM_MAX:17.00 GB), desiredKV=3.05 GB OOM!
> 03-06 09:04:30.600 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:7.09 GB + FREE:688.5 MB == MEM_MAX:17.00 GB), desiredKV=2.82 GB OOM!
> 03-06 09:04:33.692 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:7.17 GB + FREE:606.8 MB == MEM_MAX:17.00 GB), desiredKV=2.66 GB OOM!
> 03-06 09:04:36.582 10.20.33.75:54325     31534  #e Thread WARN: Swapping!  GC CALLBACK, (K/V:9.24 GB + POJO:7.22 GB + FREE:553.5 MB == MEM_MAX:17.00 GB), desiredKV=2.55 GB OOM!
>

**Comment by jakubhava** [comment]
To be able to fit the dataset into H2O memory, rule of thumb is that number of memory should be 4 times higher than the size of data before import
