### ISSUE TITLE
Spark 1.3.0 is unsuported

### ISSUE THREAD

**Issue by nftw** [h2oai/sparkling-water#6]
Hi,

From the quick look I had, in `core/src/main/scala/org/apache/spark/h2o/H2OContext.scala` `ExistingRdd` and `SparkLogicalPlan` are now removed and replaced by `LogicalRDD`. Also, `SchemaRDD` has now been replaced by `DataFrame`.

Thanks!

**Comment by petro-rudenko** [comment]
+1 would be great to rename toDataFrame to something like toH2ODataFrame, to not confuse with spark's dataframe.

**Comment by mmalohlava** [comment]
This is the next step to migrate to the newest version of Spark. Feel free to commit any PR involving migration.

**Comment by nickpoorman** [comment]
+1

**Comment by mmalohlava** [comment]
The current plan is to rename H2O's DataFrame to H2OFrame and make corresponding changes in API. Thank you for your note!

**Comment by mmalohlava** [comment]
Already implemented in master/rel-1.4/rel-1.5
