### ISSUE TITLE
Unable to access Hive table from pysprkling (permission denied)

### ISSUE THREAD

**Issue by Dom-nik** [h2oai/sparkling-water#61]
Hello,
I'm running pysparkling (Sparkling Water 1.5.16) with a command:
`$SPARKLING_HOME/bin/pysparkling --num-executors 3 --executor-memory 20g --executor-cores 10 --driver-memory 20g --master yarn-client --conf "spark.scheduler.minRegisteredResourcesRatio=1" --conf "spark.ext.h2o.topology.change.listener.enabled=false" --conf "spark.ext.h2o.node.network.mask=155.111.184.0/24" --conf "spark.ext.h2o.fail.on.unsupported.spark.param=false"`

In the console I run the following set of commands:

```
from pysparkling import *
hc= H2OContext(sc).start()
import h2o
query="select * from default.table"
combinations=sqlContext.sql(query)
h2oframe = hc.as_h2o_frame(combinations)
```

The lat one fails with an error:

> Permission denied: user=<username>, access=READ_EXECUTE, inode="/user/hive/warehouse/table":hive:hive:drwxrwx--t

I kinited before starting pysparkling and I tested that I actually can run the same query in Hive via HUE. Can you please help me debug the case?

**Comment by mmalohlava** [comment]
Hi Dominik, does it work if you run normal pyspark? 

```scala
query="select * from default.table"
combinations=sqlContext.sql(query)
combinations.take(100)```

**Comment by jakubhava** [comment]
Hi Dominik, any response on this please ?

Thanks!

**Comment by Dom-nik** [comment]
Hello Jakub, sorry for this, we weren't using the tool and it just slipped my mind.
Right now I'm not able to reproduce it anymore, but we are on the verge of updating to Spark 1.6, so we'll be able to use a newer version of Sparkling Water. I'll try to test then.

Thank you!

**Comment by jakubhava** [comment]
Hi Dominik, sorry for extremely late reply. If you are not able reproduce the problem then let me close this issue, but feel free to reopen it or create new one when you hit new or similar problems

Thanks,
Kuba
