### ISSUE TITLE
OOM on small dataset

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#624]
Getting OOM  when trying to put a small dataset (1m rows x 6314 columns) 
into an h2o frame - see yarn container log in \[1\].
This is a larger cluster that has SW 40 executors x 17Gb memory each.

\[1\]

> 03-15 15:34:50.746 10.20.33.76:54323     87134  #-123-143 INFO: Locking cloud to new members, because water.rapids.Session$1
> 03-15 15:52:42.569 10.20.33.76:54323     87134  #75:54321 WARN: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:Zero   + POJO:Zero   + FREE:17.00 GB == MEM_MAX:17.00 GB), desiredKV=17.00 GB OOM!
> 
> LogType:h2o_10.20.33.76_54323-4-warn.log
> Log Upload Time:Fri Mar 16 10:03:20 -0600 2018
> LogLength:213
> Log Contents:
> 03-15 15:52:42.569 10.20.33.76:54323     87134  #75:54321 WARN: Unblock allocations; cache below desired, but also OOM: OOM, (K/V:Zero   + POJO:Zero   + FREE:17.00 GB == MEM_MAX:17.00 GB), desiredKV=17.00 GB OOM!
> 
> LogType:h2o_10.20.33.76_54323-5-error.log
> Log Upload Time:Fri Mar 16 10:03:20 -0600 2018
> LogLength:0
> Log Contents:
> 
> LogType:h2o_10.20.33.76_54323-6-fatal.log
> Log Upload Time:Fri Mar 16 10:03:20 -0600 2018
> LogLength:0
> Log Contents:
> 
> LogType:h2o_10.20.33.76_54323-httpd.log
> Log Upload Time:Fri Mar 16 10:03:20 -0600 2018
>

**Comment by jakubhava** [comment]
@Tagar can you share full configuration? What code are you running?

**Comment by NkululekoThangelane** [comment]
@Tagar  I am getting similar problems. please let me know if you found a solution to this.

**Comment by jakubhava** [comment]
Closing this issue as without logs it's hard to reason about the real issue

**Comment by jakubhava** [comment]
Closing this issue as without logs it's hard to reason about the real issue
