### ISSUE TITLE
hc.as_h2o_frame(): water.ExternalFrameConfirmationException: Timeout for confirmation exceeded!

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#626]
Attempt to convert a Spark dsataframe to h2o frame leads to 
water.ExternalFrameConfirmationException: Timeout for confirmation exceeded!
exception 
when used with H2O "backend" mode.

Full stack in [1]

Is there is a way to increase this timeout?

Notice most of the tasks have completes, and only two couldn't complete, while getting h2o timeouts 

![image](https://user-images.githubusercontent.com/3013418/37578173-af5e6738-2afc-11e8-8646-23a9e9c238e4.png)

[1]

> An error occurred while calling o129.asH2OFrame.
> : org.apache.spark.SparkException: Job aborted due to stage failure: Task 342 in stage 8.0 failed 4 times, most recent failure: Lost task 342.3 in stage 8.0 (TID 7445, pc1udatahad13, executor 67): water.ExternalFrameConfirmationException: Timeout for confirmation exceeded!
> 	at water.ExternalFrameWriterClient.waitUntilAllWritten(ExternalFrameWriterClient.java:168)
> 	at org.apache.spark.h2o.backends.external.ExternalWriteConverterCtx.closeChunks(ExternalWriteConverterCtx.scala:42)
> 	at org.apache.spark.h2o.converters.SparkDataFrameConverter$.org$apache$spark$h2o$converters$SparkDataFrameConverter$$perSQLPartition(SparkDataFrameConverter.scala:117)
> 	at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$1.apply(SparkDataFrameConverter.scala:82)
> 	at org.apache.spark.h2o.converters.SparkDataFrameConverter$$anonfun$toH2OFrame$1$$anonfun$apply$1.apply(SparkDataFrameConverter.scala:82)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:108)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 
> Driver stacktrace:
> 	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1499)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1487)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1486)
> 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
> 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
> 	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1486)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
> 	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:814)
> 	at scala.Option.foreach(Option.scala:257)
> 	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:814)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1714)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1669)
> 	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1658)
>

**Comment by Tagar** [comment]
This is a small dataset of jsut 1mm records.

**Comment by jakubhava** [comment]
HI @Tagar yes, this timeout is configurable. Please see http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/configuration/configuration_properties.html#external-backend-configuration-properties

**Comment by Tagar** [comment]
Thanks @jakubhava  !

Any idea why it was taking so much time to write just 1m records to an h2o frame?
It was running for 20 minutes before that job failed with a timeout?
This is first time we try to run h2o outside of spark executors ("backend" mode), so it's possible we're missing something basic here.

**Comment by Tagar** [comment]
After I increased timeout, it doesn't fail in 20 minutes like it used to. (I set `.set_external_write_confirmation_timeout(240)`  )

But now I killed that job myself after 67 minutes. 
It should NOT take more than an hour to create a frame with just 1m records.. we have 160 h2o nodes for this task and can barely do anything. 
Is it because this is a wide dataset (6300 columns)?

**Comment by jakubhava** [comment]
https://0xdata.atlassian.net/browse/PUBDEV-6802 will avoid issues with the write confirmation timeouts

**Comment by Tagar** [comment]
thank you for the update @jakubhava
