### ISSUE TITLE
If h2o context creation failed, h2o still asks to restart spark session

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#628]
1st error - attempt to connect to a non-existent h2o cluster. Getting expextedly

> Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
> : org.apache.spark.h2o.backends.external.H2OClusterNotRunning: 
> External H2O cluster is not running or could not be connected to. Provided configuration:
>   cluster name            : H2O external cluster for svc_h2oprd
>   cluster representative  : 10.20.33.76:33099
>   cluster start timeout   : 120 seconds"
> 
> It is possible that in case you provided only the cluster name, h2o is not able to cloud up
> because multi-cast communication is limited in your network. In that case, please consider starting the
> external H2O cluster with flatfile and set the following configuration 'spark.ext.h2o.cloud.representative'

2nd attempt to run the same code to connect leads to 

> IllegalArgumentException: u'\nH2O context hasn\'t been started successfully in the previous attempt and H2O client with previous configuration is already running.\nBecause of the current H2O limitation that it can\'t be restarted within a running JVM,\nplease restart your job or spark session and create new H2O context with new configuration.")\n          '

It would be great if h2o wouldn't force to restart Spark session, if h2o session wasn't created correctly at 1st attempt.

**Comment by jakubhava** [comment]
This is all that we can do due to current limitations of H2O/SW. H2O can't be restarted inside Spark driver/executor at the moment since it has lots of static dependencies.
