### ISSUE TITLE
Link for documentation on DEVEL.md is broken (404 Page Not Found)

### ISSUE THREAD

**Issue by gbenatt92** [h2oai/sparkling-water#629]
Here is the following file containing the bug https://github.com/h2oai/sparkling-water/blob/master/DEVEL.md#TargetPlatforms

Here is the broken link https://github.com/h2oai/sparkling-water/blob/master/doc/DEVEL.rst

Solutions:

* Fix broken URL
* Add missing file DEVEL.rst

**Comment by jakubhava** [comment]
fixed, thanks

**Comment by parusss** [comment]
https://github.com/h2oai/sparkling-water/blob/master/doc/DEVEL.rst
Link is broken

**Comment by jakubhava** [comment]
Yes, removed on purpose. Please refer to our official documentation accessible from the links at the top of our README https://github.com/h2oai/sparkling-water
