### ISSUE TITLE
Sparkling Water doesn't release a frame lock if job was cancelled

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#630]
I tried to create a frame, then after it didn't complete in an hour (see https://github.com/h2oai/sparkling-water/issues/626 ), I cancelled the Spark job and then tried to create it again with fewer than 1m records but this time it gave error "Key frame_name already exists" :

![image](https://user-images.githubusercontent.com/3013418/37622802-56c8d00e-2b88-11e8-98a7-4ebb6fad75cb.png)

What I was expecting:
- if a Spark / SW job was cancelled, incomplete h2o frame had to be dropped and its lock released.

**Comment by jakubhava** [comment]
We could not trace the issue, but with the new REST API approach, such problems can't happen anymore.
