### ISSUE TITLE
Is there a way to make H2O use domain name instead of IP in Flow URL?

### ISSUE THREAD

**Issue by Dom-nik** [h2oai/sparkling-water#64]
Hello,
Sorry I'm writing here, but Flow and H2O-3 don't have their own Issues sections, it seems.

Can I make H2O print the domain name of the server instead of IP in the console log? 
I mean this part of the log:

```

  Open H2O Flow in browser: http://<IP>:54321 (CMD + click in Mac OSX)
```

I mean is there an h2o internal parameter for this?
It causes me some problems when I try to use an SSL/TLS certificate (it's based on domain name) and the user gets a message that points to the IP. Another related problem is that the address doesn't take into account using SSL (prints 'http' instead of 'https').

I know it's a minor inconvenience, but it may be confusing the users.

**Comment by mmalohlava** [comment]
Hi Dominik, 

right now, there is no way how to override default behavior. But I can imagine a small modification which would do hostname lookup.

**Comment by mmalohlava** [comment]
Regarding flow, h2o-3 issue management - we are using primarily JIRA: see it here: http://jira.h2o.ai

**Comment by jakubhava** [comment]
Hi @Dom-nik, recently we added support for `SPARK_PUBLIC_DNS` option.

If you set this option to public name such as `export SPARK_PUBLIC_DNS=h2o.ai` this address will be shown for the flow ui which should fix your issue. 

I'm closing this issue for know, but please reopen in it if doesn't work for you.

Thanks you, Kuba

**Comment by Tagar** [comment]
@jakubhava Is there is an equivalent for such functionality for clusters 
started as h2o backend clusters? 

We'd like `-notify /some/path/cluster-info.txt` to use domain name instead of IP address.
The reason is, we use a valid (purchased) SSL certificate for h2o backend, so 
when user navigates to that address using IP address, browser gives a warning
that SSL cert doesn't cover IP address.

Thanks.

**Comment by jakubhava** [comment]
Hi @Tagar nope, this is currently not supported. Please file a JIRA for this feature request in H2O-3 project and the team will decide on the priority & impact.

**Comment by Tagar** [comment]
Filed https://0xdata.atlassian.net/browse/PUBDEV-6354 
thanks
