### ISSUE TITLE
ERROR: Unknown argument (-stacktrace_collector_interval)

### ISSUE THREAD

**Issue by thomashan** [h2oai/sparkling-water#644]
## Steps to reproduce
* download spark 2.2.1
* follow Spark Package instructions on http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/10/index.html

## Result
ERROR: Unknown argument (-stacktrace_collector_interval)

This happens for many versions of sparkling-water. I haven't done a exhaustive testing but I've tried 
* ai.h2o:sparkling-water-package_2.11:2.2.10 
* ai.h2o:sparkling-water-package_2.11:2.2.9
* ai.h2o:sparkling-water-package_2.11:2.2.8

and it happens for all the versions I've tried.

**Comment by schwannden** [comment]
This is a known issue in the 2.2.10 release: https://0xdata.atlassian.net/browse/SW-776
I am using sparkling water 2.2.9 and it works fine though

**Comment by thomashan** [comment]
@schwannden You're right. I'll close this issue since it's resolved in 2.2.11.

**Comment by jakubhava** [comment]
In the meanwhile, you can use 2.2.10, but the binary distribution downloadable from our page instead of the maven packages.
