### ISSUE TITLE
problem in starting h2o.init()

### ISSUE THREAD

**Issue by Dipanjan17** [h2oai/sparkling-water#649]
to be noted
1: My java/JDK is up to date, and also path is set in the environment variable
2: Latest Version of R installed i.e 3.4.4 and h2o is also currently
how do I solve this problem?

> h2o.init(ip="localhost",port = 54321)

H2O is not running yet, starting it now...

Note:  In case of errors look at the following log files:
    C:\Users\DIPANJ~1\AppData\Local\Temp\RtmpANqzPw/h2o_Dipanjan_Chowdhury_started_from_r.out
    C:\Users\DIPANJ~1\AppData\Local\Temp\RtmpANqzPw/h2o_Dipanjan_Chowdhury_started_from_r.err

java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

............................................................
ERROR: Unknown argument (Chowdhury_xkj246)

- show quoted text -

- show quoted text -

- show quoted text -

- show quoted text -

- show quoted text -

- show quoted text -

- show quoted text -

- show quoted text -

- show quoted text -

    -flow_dir <server side directory or hdfs directory>

          The directory where H2O stores saved flows.
          (The default is 'C:\Users\Dipanjan Chowdhury\h2oflows'.)

    -nthreads <#threads>
          Maximum number of threads in the low priority batch-work queue.
          (The default is 99.)

    -client
          Launch H2O node in client mode.

Cloud formation behavior:

    New H2O nodes join together to form a cloud at startup time.
    Once a cloud is given work to perform, it locks out new members
    from joining.

Examples:

    Start an H2O node with 4GB of memory and a default cloud name:
        $ java -Xmx4g -jar h2o.jar

    Start an H2O node with 6GB of memory and a specify the cloud name:
        $ java -Xmx6g -jar h2o.jar -name MyCloud

    Start an H2O cloud with three 2GB nodes and a default cloud name:
        $ java -Xmx2g -jar h2o.jar &
        $ java -Xmx2g -jar h2o.jar &
        $ java -Xmx2g -jar h2o.jar &
 
[1] "localhost"

[1] 54321
[1] TRUE
[1] -1
[1] "Failed to connect to localhost port 54321: Connection refused"
[1] 127
Error in h2o.init(ip = "localhost", port = 54321) :
  H2O failed to start, stopping execution.
In addition: Warning message:
running command 'curl 'http://localhost:54321'' had status 127

**Comment by Dipanjan17** [comment]
How do I remove the Unknown Argument

**Comment by jakubhava** [comment]
Hi @Dipanjan17 , can you share full reproducible code?

Also are you using Sparkling Water or just H2O, what are the versions?

**Comment by jakubhava** [comment]
Hi @Dipanjan17 I will go ahead and close this issue as there is no response. If you wold like to continue, please help us with sharing the info above and feel free to reopen the issue
