### ISSUE TITLE
Relation between `spark.ext.h2o.hadoop.memory` and `mapperXmx`

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#650]
If I launch a SW backend cluster with `-mapperXmx` parameter set to let's say `21G`, 
then what `spark.ext.h2o.hadoop.memory` should be recommended to be set to? (it defaults to 6G according to [documentation  ](http://docs.h2o.ai/sparkling-water/2.3/latest-stable/doc/configuration/configuration_properties.html#external-backend-configuration-properties)) .

I guess I don't understand how `spark.ext.h2o.hadoop.memory` relates to `mapperXmx` ?

**Comment by jakubhava** [comment]
`spark.ext.h2o.hadoop.memory` is wrapper for `-mapperXmx`. In Sparkling Water, external backend, auto mode we start the external cluster automatically and whatever is set to `spark.ext.h2o.hadoop.memory` is passed later to `-mapperXmx`

**Comment by Tagar** [comment]
Thanks @jakubhava
