### ISSUE TITLE
SW backend mode broken in 2.2.11? java.lang.NoSuchMethodError: ml.dmlc.xgboost4j.java.NativeLibLoader.getLoader()Lml/dmlc/xgboost4j/java/INativeLibLoader

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#651]
Trying to connect to a 2.2.11 backend cluster (extended jar ) leads to
`java.lang.NoSuchMethodError: ml.dmlc.xgboost4j.java.NativeLibLoader.getLoader()Lml/dmlc/xgboost4j/java/INativeLibLoader`

Full exception stack

> Py4JJavaError: An error occurred while calling z:org.apache.spark.h2o.JavaH2OContext.getOrCreate.
> : java.lang.NoSuchMethodError: ml.dmlc.xgboost4j.java.NativeLibLoader.getLoader()Lml/dmlc/xgboost4j/java/INativeLibLoader;
> 	at hex.tree.xgboost.XGBoostExtension.initXgboost(XGBoostExtension.java:58)
> 	at hex.tree.xgboost.XGBoostExtension.isEnabled(XGBoostExtension.java:48)
> 	at water.ExtensionManager.isEnabled(ExtensionManager.java:145)
> 	at water.ExtensionManager.registerCoreExtensions(ExtensionManager.java:63)
> 	at water.H2O.main(H2O.java:1860)
> 	at water.H2OStarter.start(H2OStarter.java:21)
> 	at water.H2OStarter.start(H2OStarter.java:46)
> 	at org.apache.spark.h2o.backends.external.ExternalH2OBackend.init(ExternalH2OBackend.scala:166)
> 	at org.apache.spark.h2o.H2OContext.init(H2OContext.scala:127)
> 	at org.apache.spark.h2o.H2OContext$.getOrCreate(H2OContext.scala:379)
> 	at org.apache.spark.h2o.H2OContext.getOrCreate(H2OContext.scala)
> 	at org.apache.spark.h2o.JavaH2OContext.getOrCreate(JavaH2OContext.java:252)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.zeppelin.py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
> 	at org.apache.zeppelin.py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
> 	at org.apache.zeppelin.py4j.Gateway.invoke(Gateway.java:290)
> 	at org.apache.zeppelin.py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
> 	at org.apache.zeppelin.py4j.commands.CallCommand.execute(CallCommand.java:79)
> 	at org.apache.zeppelin.py4j.GatewayConnection.run(GatewayConnection.java:209)
> 	at java.lang.Thread.run(Thread.java:748)
>

**Comment by Tagar** [comment]
I realized there was `h2o-genmodel.jar` passed as `--jars` to spark-submit that caused this.

**Comment by Tagar** [comment]
It seems we would still need to add `h2o-genmodel.jar` into classpath to do scoring in Spark directly.. 
So reopening this now. 
Would it be possible to have `h2o-genmodel.jar` in classpath and still use Sparkling Water?

**Comment by jakubhava** [comment]
Hi @Tagar can you please tell us whether you are experiencing this issue on the latest Sparkling Water?

Also it is not necessary to pass h2o-genmodel explicitly as we bundle it inside the sparkling water jar already. Thank you!

**Comment by Tagar** [comment]
We have moved this to a different architecture - we employ hadoop streaming with a custom java + h2o mojo code there. This was workaround as it wasn't working at the time. I know h2o has resolved those conflicts' dependencies in one of the later versions. We never had time to rewrite our scoring processes since then. But we can give this a try sometime in the future. Thank you
