### ISSUE TITLE
PySpark equivalent for genmodel.easy.EasyPredictModelWrapper ?

### ISSUE THREAD

**Issue by Tagar** [h2oai/sparkling-water#654]
We were trying to score records using mojo (`genmodel.easy.EasyPredictModelWrapper` ) -- see the code prototype on https://github.com/Tagar/ML/blob/master/mojo_pyspark_scorer.py 

The idea was to use `map()` or `mapPartitions()` in Spark and call `genmodel.easy.EasyPredictModelWrapper` through py4j, but ran into issues described in [SPARK-23842](https://issues.apache.org/jira/browse/SPARK-23842).

Is there is a better approach to score records directly in PySpark? We would like to avoid persisting whole dataset we'd like to score in memory (due to different OOM issues as its a quite big daataset). That's why we want to have this record-by-record approach and scale it out by calling scoring through a lambda function in Spark's `map()` or `mapPartitions()` .

Any better ideas?

**Comment by Tagar** [comment]
cc @mmalohlava @jakubhava @michalkurka can you please let me know if it's possible? 

We were also trying to call java scoring through py4j in Spark executors but ran into issues described here https://github.com/bartdag/py4j/issues/311

**Comment by jakubhava** [comment]
@Tagar you can use our mojo wrappers in pysparkling. They are internally using easy predict model wrapper, but provide a spark api, hiding the internals.

The code looks like:
```
mojo = H2OMOJOModel.create_from_mojo("path_to_mojo")
prostate_frame = spark.read.csv("patj_to_data,header=True)
# Now run predictions
mojo.predict(prostate_frame)
```

**Comment by Tagar** [comment]
Thank you for letting me know @jakubhava - that's very helpful. As I just mentioned in https://github.com/h2oai/sparkling-water/issues/651#issuecomment-431513999 , we will give this a try later.
