### ISSUE TITLE
add flow context_path to configuration options

### ISSUE THREAD

**Issue by aadu** [h2oai/sparkling-water#655]
Sorry if this is already exposed, but couldn't find it anywhere.

**Comment by jakubhava** [comment]
Hi @aadu, 
 thanks for the report! It's not exposed at this moment, I will work on this change.

Thanks!

Kuba

**Comment by jakubhava** [comment]
Hi @aadu, the change is implemented in this PR and should go to master soon https://github.com/h2oai/sparkling-water/pull/658

**Comment by jakubhava** [comment]
@aadu merged to master, will be in the next release
