### ISSUE TITLE
Use SharedH2OTestContext in tests

### ISSUE THREAD

**Issue by hangelwen** [h2oai/sparkling-water#700]
It would be pretty useful if Sparking-Water client code can use `SharedH2OTestContext` and other test related utils. Is there a way to do this now?

**Comment by jakubhava** [comment]
Hi @hangelwen, can you please elaborate a little bit more what do you mean by this proposal?

**Comment by hangelwen** [comment]
Sure @jakubhava .

`SharedH2OTestContext` is a utility class in the `test` environment that sets up a H2O cluster for unit tests. Since it's in test, I think it can not be accessed by H2O lib users. But it would be pretty useful for H2O lib users to write unit test since this automatically set up a H2O Context for tests.  Then if one needs to write unit test for their project and need to have H2O, what they need to do is just simply reuse the trait:
```
 class MyTest
  extends SharedH2OTestContext {
   ...
  }
```

What I request is similar to https://github.com/holdenk/spark-testing-base, which exposes a lot of useful constructs that can be used for Spark related tests.

**Comment by hangelwen** [comment]
@jakubhava 
`SharedH2OTestContext ` is just an example. Maybe all the stuff in https://github.com/h2oai/sparkling-water/tree/master/core/src/test/scala/org/apache/spark/h2o/utils can be reused by clients.

**Comment by jakubhava** [comment]
If I understand correctly, you would like the testing features to be exposed to maven so you can use those as a dependency? Thanks!

**Comment by hangelwen** [comment]
@jakubhava 
That's right. Since there are a few utilities in the tests which are useful for clients. Maybe you can provide another artifact just with tests.

**Comment by jakubhava** [comment]
Hi @hangelwen sorry for not being able to work on this. Feel free to contribute, would be happy to review!

I'm closing this issue as the priorities for Sparkling Water are not a little different
