### ISSUE TITLE
pySparkling build fail

### ISSUE THREAD

**Issue by ai-monkey** [h2oai/sparkling-water#705]
$ git clone http://github.com/h2oai/sparkling-water
$ cd sparkling-water
$ sudo ./gradlew build -x check

FAILURE: Build failed with an exception.

* Where:
Build file '/home/omega/Downloads/sparkling-water/py/build.gradle' line: 69

* What went wrong:
A problem occurred evaluating project ':sparkling-water-py'.
> Could not resolve all files for configuration ':sparkling-water-py:mojopipeline'.
   > Could not resolve ai.h2o:mojo2-runtime:0.9.6.
     Required by:
         project :sparkling-water-py
      > Could not resolve ai.h2o:mojo2-runtime:0.9.6.
         > Could not get resource 'http://nexus:8081/nexus/repository/releases/ai/h2o/mojo2-runtime/0.9.6/mojo2-runtime-0.9.6.pom'.
            > Could not GET 'http://nexus:8081/nexus/repository/releases/ai/h2o/mojo2-runtime/0.9.6/mojo2-runtime-0.9.6.pom'.
               > nexus

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s

**Comment by dshurick** [comment]
I've gotten the same issue.

**Comment by jakubhava** [comment]
Hi @ai-monkey @dshurick thanks, this is a known thing. Currently, building Sparkling Water requires internal artifacts which are not yet published. We are working on making sure Sparkling Water can be build by anybody in the future again.

Thanks!

Kuba

**Comment by simonvdk** [comment]
Any update on this issue ?

**Comment by jakubhava** [comment]
@simonvdk it's our top priority and it's work in progress. We should enable custom builds of Sparkling Water soon, sorry for the inconvenience

**Comment by jakubhava** [comment]
@LehakDharmani You can always download Sparkling Water from https://www.h2o.ai/download/. The latest version for Spark 2.2 is available here https://s3.amazonaws.com/h2o-release/sparkling-water/rel-2.2/22/index.html

This issue affects only the build outside of our internal infrastructure, however it is always highly suggested to use the official builds

**Comment by hakangurel** [comment]
I have the same issue. I cannot make it running on zeppelin 0.8.0 as documented here:
http://docs.h2o.ai/sparkling-water/2.3/latest-stable/doc/deployment/use_on_zeppelin.html?highlight=zeppelin

We are very eager to try sparkling water on zeppelin so that would be very much appreciated if you can fix this dependency issue or provide mojo2-runtime if possible.

**Comment by jakubhava** [comment]
The fix is out. The current Sparkling Water master can be build again

**Comment by hakangurel** [comment]
Thanks a lot 👍

**Comment by eduardo4jesus** [comment]
I just got this problem when custom building [pysparkling](http://docs.h2o.ai/sparkling-water/2.2/latest-stable/doc/pysparkling.html).

If the problem was fixed, I am not sure what to do.

My output is:

```Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/eduardoj/.local/lib/sparkling-water/r/build.gradle' line: 131

* What went wrong:
A problem occurred evaluating project ':sparkling-water-r'.
> Cannot run program "R" (in directory "/Users/eduardoj/.local/lib/sparkling-water/r"): error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 8s```
