### ISSUE TITLE
Spark-Shell vs Spark Submit

### ISSUE THREAD

**Issue by NkululekoThangelane** [h2oai/sparkling-water#724]
Good Day.

Im currently running sparking water using an internal backed via the pysparking api.
I am able to run Sparkling Water with H2O in a Juptyter NoteBook, However when I want to run the same code with the same cluster setting using spark-submit in yarn client mode I seem to be getting a whole host of new errors that I did not get when running in the note book. Such error normally revolve around memory. The data frame I am training with is around 3GB in size and all my executors and driver have around 15 gigs of memory. My question is do I need to make certain changes to my pyspark code to ensure it right smoothly over a spark-submit in a yarn cluster.
Your help with this will be highly appreciated.

**Comment by jakubhava** [comment]
Hi @NkululekoThangelane, in order to be able to reason about the issue we need to have:

 - full YARN logs
 - Spark & Sparkling Water version
 - full command line you use to start your spark application
 - if possible, the minimal application code

Thank you!

Kuba

**Comment by jakubhava** [comment]
Ho @NkululekoThangelane, any update?

**Comment by NkululekoThangelane** [comment]
Hi @jakubhava  i will try upload all Logs. We are currently using spark 2.1 and h2o (3.18.0.11)
h2o-pysparkling-2.1 (2.1.30).  When I train a model using the Pyspark-shell on jupyter notebook everything goes well. However when i train the model using spark2-submit I get memory errors and containers killed by YARN for memory issues. We are currently using Java 8 and don't know where else to change that the configs. We have increases the size of driver and executor memory way above the jupyter notebook settings and we still get H2o being killed.  @jakubhava  Please let me know some of the things to look out for when doing a spark2-submit with sparkling water as it seems theres a huge difference.
The Data is is around 50 millions with 70 columns.

**Comment by jakubhava** [comment]
is your PySparkling shell running on YARN as well?

Regarding the memory issues -> YARN cluster needs to be configured correctly, this means for example that the containers need to have enough memory, there is enough memory in the physical node, there are also some YARN extra memory configurations. I would suggest contacting your YARN cluster administrator and check with him/her.

**Comment by jakubhava** [comment]
Closing this issue as there is not update, feel free to re-open
