### ISSUE TITLE
Prediction using AutoML

### ISSUE THREAD

**Issue by sharmmoh1983** [h2oai/sparkling-water#730]
Hi 
I am using AutoML to create model and do prediction
I have used following code to create the model but not able to us any method to do prediction and get the score

```
 import h2oContext.implicits._
  val h2oFrame = h2oContext.asH2OFrame(train, "my-frame-name")
    
  //h2oFrame.
 
 val autoMLBuildSpec = new AutoMLBuildSpec()
autoMLBuildSpec.input_spec.training_frame = h2oFrame
autoMLBuildSpec.input_spec.response_column = "SnowIn";
autoMLBuildSpec.build_control.loss = "AUTO"
autoMLBuildSpec.build_control.stopping_criteria.set_max_runtime_secs(5)
import java.util.Date;
val aml = AutoML.makeAutoML(Key.make(), new Date(), autoMLBuildSpec)
AutoML.startAutoML(aml)

var model=AutoML.startAutoML(autoMLBuildSpec).get();

    //save the leader model
    var modelSavePath = "data/";
  //  aml.leader().getMojo().writeTo(new FileOutputStream(new File(modelSavePath + "/" + aml.leader()._key + ".zip")));

    //print the leaderboard
    println(aml.leaderboard());

    //details of the leader model
println(aml.leader());
```
I want to do classification and I am using weather data having one of the response columns as Snow value 

Is this right way to do it?

**Comment by sharmmoh1983** [comment]
Any comment on the issue? I am struggling to get it through

**Comment by jakubhava** [comment]
Please see https://github.com/h2oai/sparkling-water/blob/3940c723be075502da9596fbf77f811fef3dcf13/examples/pipelines/hamOrSpamMultiAlgo.script.scala#L97, this is the official way how to use AutoML in Sparkling Water
