### ISSUE TITLE
Load a model without starting a H2O cluster

### ISSUE THREAD

**Issue by hangelwen** [h2oai/sparkling-water#767]
Is that possible to load a model without starting a H2O cluster?

The following code throws NPE if a H2O cluster is not avail.
```
val loadedModel = ModelSerializationSupport.loadH2OModel[GBMModel](new URI("mymodel.h2o"))
```

The use case here is that I want to retrieve model stats such as feature importance,  training/validation accuracy, etc in a service. Seems the information is only not avail in MOJO models.

**Comment by jakubhava** [comment]
Hi @hangelwen POJOs and MOJOs are designed to work without needing to have H2O available at run-time. You are trying to load a binary model which actually always need to have H2O cluster available. 

I would suggest exploring deployment of H2O models using MOJO.

**Comment by hangelwen** [comment]
@jakubhava thanks. Yes for model deployment I'm using MOJO and it works. However, it does not provide model properties as I mentioned.  What I'm thinking to have is a service to have all models and their properties exposed so ppl can get those info by hitting an API.  It seems heavy to have a H2O cluster started for this kind of use case.

**Comment by jakubhava** [comment]
Can you maybe list all the properties you would like to have exposes as part of MOJO? Maybe core H2O has them already exposed and we just need to create wrapper calls on Sparkling Water side.

Thanks for the feedback!

**Comment by hangelwen** [comment]
@jakubhava 

Something that I think are useful:
1. feature importance.
2. metrics(AUC, logloss, etc) on training & testing data set when the model is built.
3. model parameters.

**Comment by hangelwen** [comment]
@jakubhava 
Seems these info are not exposed by the genModel(MOJO) API so I guess we can not add wrappers on SW side.

**Comment by jakubhava** [comment]
Yup, I just checked as well. Let me ask folks behind H2O about those. Thanks for opening this issue!

**Comment by hangelwen** [comment]
@jakubhava great! looking forward to hearing from you.

**Comment by hangelwen** [comment]
@jakubhava another choice is to allow loading of a  binary H2O model without a H2O cluster and accessing all model related information, and only fails when operations that requires a H2O cluster suc has `score` is invoked...

**Comment by lppsuixn** [comment]
How is it going.
I also want to get some metrics from mojo.

**Comment by jakubhava** [comment]
Hello, just wanted to provide an update - we had several discussions and this is the way the mojo format will evolve, thanks!

In the meantime, you can read the metrics and the model information from the experimental json file located insite the mojo ( you need to extract it)

**Comment by jakubhava** [comment]
The details from model train are now exposed via `getModelDetails()` method on `H2OMOJOModel`

**Comment by kmullapudi-11** [comment]
@jakubhava Is there a helper function in Sparkling Water I can use to load data returned by `getModelDetails()` as a `DataFrame` in Spark or will I have to write a custom method? For instance, say I want to read the `variable_importances` data returned by `getModelDetails()`. Also, is there a way to get the data directly as a json or get parts of the data as keys like a `getVariableImportances()` method? Could you point me to any relevant docs? Thanks.

**Comment by jakubhava** [comment]
@kmullapudi-11 Currently, only `getModelDetails()` returning JSON with all info is available. At this moment we don't expose variable importances
