### ISSUE TITLE
Issue with "pip3 install h2o_pysparkling_2.3"?

### ISSUE THREAD

**Issue by vishalbahirwani** [h2oai/sparkling-water#768]
This was working few days ago.

Command used:
`pip3 install h2o_pysparkling_2.3 -v`

Stuck here:
`Running setup.py (path:/mnt/tmp/pip-install-wem4f9ho/pyspark/setup.py) egg_info for package pyspark`
`    Running command python setup.py egg_info`

**Comment by jakubhava** [comment]
PySparkling now requires dependency on `pyspark`

Can you try installing `pyspark` as `pip3 install pyspark`?

**Comment by vishalbahirwani** [comment]
Thanks for quick reply. However, execution is stuck at the same spot as before. For some reason, Pyspark install command never returns back cursor.

**Comment by jakubhava** [comment]
Can you please share what `python` are you using?

**Comment by vishalbahirwani** [comment]
Python 3.4.8

**Comment by vishalbahirwani** [comment]
Pyspark is already installed. I'm not sure why h2o_pysparkling_2.3 is installing Pyspark again?

**Comment by vishalbahirwani** [comment]
Issue resolved. Had to install `pip3 install pypandoc` and then install Sparkling water.

**Comment by jakubhava** [comment]
thanks!
