### ISSUE TITLE
spark_connect argument is of length zero

### ISSUE THREAD

**Issue by CuddleFish18** [h2oai/sparkling-water#792]
I'm very new to Spark/Sparklingwater and AWS. First I created an Spark Cluster on AWS EMR got it running and used sparklyr to do some data preparation in R combined with Spark.
(spark_connect worked perfectly)

We created a model in H2O before and now we want to use Sparkling water for this.
I installed in following these steps:
http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.3/8/index.html

Now I'm trying to connect to spark again in R and it is not working.
I did the following:

#Install RSparkling dependency, SparklyR:

install.packages("sparklyr")

#Install Spark:

library(sparklyr)
spark_install(version = "2.3.0")

#Install H2O of correct version:
#The following two commands remove any previously installed H2O packages for R.
if ("package:h2o" %in% search()) { detach("package:h2o", unload=TRUE) }
if ("h2o" %in% rownames(installed.packages())) { remove.packages("h2o") }

#Next, we download packages that H2O depends on.
pkgs <- c("methods","statmod","stats","graphics","RCurl","jsonlite","tools","utils")
for (pkg in pkgs) {
  if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
}

#Now we download, install, and initialize the H2O package for R. 
#In this case we are using rel-wolpert 11 (3.20.0.2).
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-wright/2/R")

require(h2o)

#Finally, install RSparkling
#Install latest version from CRAN:

install.packages("rsparkling")

#Set Sparkling Water version to be used with RSparkling
options(rsparkling.sparklingwater.version = "2.3.8")
library(rsparkling)

#Connect to Spark
sc <- spark_connect(master = "yarn-client", version = "2.3.0")

Running the last function spark_connect gives the following error:
> sc <- spark_connect(master = "yarn-client", version = "2.3.0")
Error in if (current_h2o_version != h2o_version) { : 
  argument is of length zero

Searched the entire internet and did not find any help.

Thank you!

**Comment by jakubhava** [comment]
Hi @CuddleFish18. I was able to reproduce and provided a fix in the main RSparkling branch.

Please install RSparkling as:

```
library(devtools)
devtools::install_github("h2oai/rsparkling", ref = "master")
```

This will install the latest RSparkling with the provided fix. Thank you for the report!

**Comment by CuddleFish18** [comment]
Thanks @jakubhava! I will have a look at it :)

**Comment by mmalohlava** [comment]
btw: for the future we moved the rsparkling into sparkling-water repo - that means correct github-based installation is:

```R
devtools::install_github("h2oai/sparkling-water", ref="master", subdir="r/src")
```

**Comment by Kreitzberg** [comment]
Hello, I am coming across the same issue. I am working in an Amazon AWS cluster which I used the bootstrapping action from here

https://aws.amazon.com/blogs/big-data/running-sparklyr-rstudios-r-interface-to-spark-on-amazon-emr/

Then I installed rsparkling and h2o as written below


```
#install sparklyr rsparkling and h2o

install.packages("rsparkling")

pkgs <- c("methods", "statmod", "stats", "graphics", "RCurl", "jsonlite", "tools", "utils")
for (pkg in pkgs) {
    if (! (pkg %in% rownames(installed.packages()))) { install.packages(pkg) }
}

install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-xia/1/R")

```

```{r}
options(rsparkling.sparklingwater.version = "2.2.29")
```

```{r}
Sys.setenv(SPARK_HOME_VERSION ="2.2.0")

sparklyr:::spark_version_from_home("/usr/hdp/current/spark-client")
```

```{r}
library(sparklyr)
library(dplyr)
library(rsparkling)

Sys.setenv(SPARK_HOME="/usr/lib/spark/")
Sys.setenv(SPARK_CONF_DIR="/usr/lib/spark/conf")

Sys.setenv(HADOOP_CONF_DIR = '/etc/hadoop/conf')
Sys.setenv(YARN_CONF_DIR = '/etc/hadoop/conf')

conf <- spark_config()

conf$spark.dynamicAllocation.enabled <- "false"
conf$spark.executor.cores <- 2
conf$spark.executor.instances <- 6
conf$spark.executor.memory <- "2G"

sc <- spark_connect(master = "yarn-client",
                    version = "2.2.0",
                    config = conf)
```

I tried the suggestions of installing rsparkling with 

`devtools::install_github("h2oai/sparkling-water", ref="master", subdir="r/src")
`

but I had no luck. Any help would be awesome.

**Comment by jakubhava** [comment]
@Kreitzberg The last version or available on CRAN RSparkling does not support latest Sparkling Water of 2.2.29. Also, I see that you are installing H2O from install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-xia/1/R") -> which is actually `3.22.0.1` and 2.2.29 requires `3.22.0.2`

I can suggest two options:

Either, you can try to use the RSparkling available in CRAN and Sparkling Water version of `2.2.28`.
The whole code is: 
```
install.packages("rsparkling")
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-xia/2/R")
options(rsparkling.sparklingwater.version = "2.2.28")
library(sparklyr)
library(rsparkling)
sc <- spark_connect(master = "local", version = "2.2.0")
```
Or, to use the latest one, please install RSparkling using `devtools::install_github("h2oai/sparkling-water", ref="master", subdir="r/src") ` and install H2O of version `3.22.0.2`. You will be warned how to install h2o during `spark_connect`. The whole code is:

```
devtools::install_github("h2oai/sparkling-water", ref="master", subdir="r/src") 
install.packages("h2o", type = "source", repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-xia/2/R")
options(rsparkling.sparklingwater.version = "2.2.29")
library(sparklyr)
library(rsparkling)
sc <- spark_connect(master = "local", version = "2.2.0")
```

You can also read this readme -> https://github.com/h2oai/sparkling-water/tree/master/r

**Comment by Kreitzberg** [comment]
Thank you Jakub! I was focusing on matching the rsparkling and spark versions! Thanks for the detailed response.
