### ISSUE TITLE
unresolved dependencies for 2.3.9

### ISSUE THREAD

**Issue by salivian** [h2oai/sparkling-water#857]
Fail to start sparkling water as 

spark-shell  --packages ai.h2o:sparkling-water-package_2.11:2.3.9

Missing modules biz.k11i#xgboost-predictor;0.3.0 and ai.h2o#mojo2-runtime;0.10.7

xgboost-predictor may be resolved to specifying additional repo
yet
mojo2-runtime is really unavailable

```
:: problems summary ::
:::: WARNINGS
		module not found: biz.k11i#xgboost-predictor;0.3.0

	==== local-m2-cache: tried

	  file:/home/ipcy/.m2/repository/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.pom

	  -- artifact biz.k11i#xgboost-predictor;0.3.0!xgboost-predictor.jar:

	  file:/home/ipcy/.m2/repository/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.jar

	==== local-ivy-cache: tried

	  /home/ipcy/.ivy2/local/biz.k11i/xgboost-predictor/0.3.0/ivys/ivy.xml

	  -- artifact biz.k11i#xgboost-predictor;0.3.0!xgboost-predictor.jar:

	  /home/ipcy/.ivy2/local/biz.k11i/xgboost-predictor/0.3.0/jars/xgboost-predictor.jar

	==== central: tried

	  https://repo1.maven.org/maven2/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.pom

	  -- artifact biz.k11i#xgboost-predictor;0.3.0!xgboost-predictor.jar:

	  https://repo1.maven.org/maven2/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.pom

	  -- artifact biz.k11i#xgboost-predictor;0.3.0!xgboost-predictor.jar:

	  http://dl.bintray.com/spark-packages/maven/biz/k11i/xgboost-predictor/0.3.0/xgboost-predictor-0.3.0.jar

		module not found: ai.h2o#mojo2-runtime;0.10.7

	==== local-m2-cache: tried

	  file:/home/ipcy/.m2/repository/ai/h2o/mojo2-runtime/0.10.7/mojo2-runtime-0.10.7.pom

	  -- artifact ai.h2o#mojo2-runtime;0.10.7!mojo2-runtime.jar:

	  file:/home/ipcy/.m2/repository/ai/h2o/mojo2-runtime/0.10.7/mojo2-runtime-0.10.7.jar

	==== local-ivy-cache: tried

	  /home/ipcy/.ivy2/local/ai.h2o/mojo2-runtime/0.10.7/ivys/ivy.xml

	  -- artifact ai.h2o#mojo2-runtime;0.10.7!mojo2-runtime.jar:

	  /home/ipcy/.ivy2/local/ai.h2o/mojo2-runtime/0.10.7/jars/mojo2-runtime.jar

	==== central: tried

	  https://repo1.maven.org/maven2/ai/h2o/mojo2-runtime/0.10.7/mojo2-runtime-0.10.7.pom

	  -- artifact ai.h2o#mojo2-runtime;0.10.7!mojo2-runtime.jar:

	  https://repo1.maven.org/maven2/ai/h2o/mojo2-runtime/0.10.7/mojo2-runtime-0.10.7.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/mojo2-runtime/0.10.7/mojo2-runtime-0.10.7.pom

	  -- artifact ai.h2o#mojo2-runtime;0.10.7!mojo2-runtime.jar:

	  http://dl.bintray.com/spark-packages/maven/ai/h2o/mojo2-runtime/0.10.7/mojo2-runtime-0.10.7.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: biz.k11i#xgboost-predictor;0.3.0: not found

		:: ai.h2o#mojo2-runtime;0.10.7: not found

		::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by jakubhava** [comment]
@salivian regarding `xgboost` library, you need to run Sparkling water with additional repository as:

$SPARK_HOME/bin/spark-submit --repositories http://dl.bintray.com/komiya-atsushi/maven --packages ai.h2o:sparkling-water-package_2.11:2.3.9

Regarding the mojo2 library, please see https://github.com/h2oai/sparkling-water/issues/705. We plan to address the issue ASAP, all the moving pieces are ready already. Thank you for your patience!

**Comment by Akhilesh491431** [comment]
I found the xgboost jar file, manually downloaded and placed in the location , but I am not able to find the mojo2-runtime jar Any fix for this?

**Comment by myloginid** [comment]
Same issue - 

`
library(rsparkling)
library(sparklyr)
library(h2o)
library(dplyr)

config <- spark_config()
config$spark.driver.cores   <- 1
config$spark.executor.cores <- 2
config$spark.executor.memory <- "2G"
config$spark.jars.repositories <- "http://dl.bintray.com/komiya-atsushi/mavenm,http://maven.corp.factual.com/nexus/content/repositories/snapshots/"
config$spark.ext.h2o.topology.change.listener.enabled <- FALSE
config$sparklyr.gateway.start.timeout <- 900
config$sparklyr.log.console <- TRUE
config$spark.jars.packages <- "ai.h2o:sparkling-water-package_2.11:2.3.12"
sc <- spark_connect(master = "yarn-client", app_name = "sparklyrm",config = config)
`

Error - 
`		::::::::::::::::::::::::::::::::::::::::::::::
		::          UNRESOLVED DEPENDENCIES         ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: biz.k11i#xgboost-predictor;0.3.0: not found
		:: ai.h2o#mojo2-runtime;0.10.7: not found
		::::::::::::::::::::::::::::::::::::::::::::::
`

Any timeline on fixing this?

**Comment by jakubhava** [comment]
We are working on it, sorry for delays, please see https://github.com/h2oai/sparkling-water/issues/705
