### ISSUE TITLE
Correct way to stop h2o cluster/context

### ISSUE THREAD

**Issue by simonvdk** [h2oai/sparkling-water#861]
Hi there,

I am using h2o-pysparkling-2.2==2.2.20 and am searching for the correct way to stop an h2o cluster/context.
I need this because in my use case I sequentially spawn and stop spark sessions (one for each task) and want to be able to follow this logic with h2o contexts (sequentially spawn/stop spark sessions with if needed the creation/stop of an h2o context)

I tried H2OContext.stop(), which returns:
```
/home/svandekerckhove/smart-sending/.smart-sending/lib/python3.4/site-packages/pysparkling/context.py:181: UserWarning: Stopping H2OContext from PySparkling is not fully supported. Please restart your PySpark session and create a new H2OContext.
```
Then when I start the second spark session and try to create a new h2o context, it creates one that links to the previous h2o cluster (I can see that thanks to the cluster uptime), which now has the status `locked, healthy`. Nothing is done, and I have to key interrupt the script to exit.

I also tried h2o.cluster().shutdown(prompt=False), but this returns errors saying the the executors `exited because of a YARN event (e.g. pre-emption) and not because of an error in the running job`. This exits the script and my second task can not be done.

What is the correct way to stop an h2o context/cluster, so that in the same script one can sequentially use different clusters for different tasks ?

Thank you for your help

**Comment by jakubhava** [comment]
@simonvdk currently, in order to stop the H2OContext, you need to stop the full Spark application. It is a current limitation of Sparkling Water/H2O that H2O can't be restarted inside one single JVM.
