### ISSUE TITLE
Rsparkling h2o_context water.fvec.frame Error 

### ISSUE THREAD

**Issue by munsheet** [h2oai/sparkling-water#916]
Hi, I'm trying to set up my R environment to run h2o algorithms on a YARN cluster. 
(have no access to the internet due to security reasons - running on R Server) 

Here are my current environment settings:

- spark version: 2.2.0.2.6.3.0-235 (2.2) 
- master: YARN client
- _rsparkling_ version: 0.2.5
- sparkling water: 2.2.16 
- _h2o_ version: 3.18.0.10 
- _sparklyr_ version: 0.7.0 

I checked the h2o_version table for all the version mappings, but still get this error when I run the code: 
```
options(rsparkling.sparklingwater.version = "2.2.16")
options(rsparkling.sparklingwater.location = "path to my sparkling water.jar") 

Sys.setenv(SPARK_HOME = "path to my spark") 
Sys.setenv(SPARK_VERSION = "2.2.0") 
Sys.setenv(HADOOP_CONF_DIR = "...") 
Sys.setenv(MASTER = "yarn-client") 

library(sparklyr) 
library(h2o) 
library(rsparkling) 

sc = spark_connect(master = Sys.getenv("SPARK_MASTER"), spark_home = Sys.getenv("SPARK_HOME"), version = Sys.getenv("SPARK_VERSION")) 
h2o_context(sc) 

**R Server ERROR output: 
Error: java.lang.ClassNotFoundExecption: water.fvec.Frame 
       at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
...** 
```

Things I've tried: 
- Follow the instructions [here](https://github.com/h2oai/rsparkling/blob/master/inst/examples/using-sparkling-water-in-YARN.Rmd) 
- Reinstalling the h2o package and multiple retries 
- Trying different versions of h2o and sparkling water (3.18.0.5 and 2.2.11 respectively) 
I am sure it would not be a version error since I've been matching them according to h2o_release_table() as shown. Please help or guide me to a solution.

**Comment by laurendiperna** [comment]
to help keep track of the locations this question, it is also posted here: https://stackoverflow.com/questions/52053444/rsparkling-spark-error-on-yarn-java-lang-classnotfoundexception-water-fvec-fra
