### ISSUE TITLE
can H2OMOJOModel prediction  give the result directly?

### ISSUE THREAD

**Issue by lppsuixn** [h2oai/sparkling-water#918]
As title.I use 
```scala
val mojo = H2OMOJOModel.createFromMojo("file:///data1/mojo")
val predictions =  mojo.transform(df)
```
and the predictions has  a  column named prediction_output  like
|-- prediction_output: struct (nullable = true)
 |    |-- p0: double (nullable = false)
 |    |-- p1: double (nullable = false)
or
 |-- prediction_output: struct (nullable = true)
 |    |-- value: double (nullable = false)
or
 |-- prediction_output: struct (nullable = true)
 |    |-- probabilities: array (nullable = true)
 |    |    |-- element: double (containsNull = false)

I should write a udf to add a result column.so is there any solution to give the result directly?
Thanks.

**Comment by laurendiperna** [comment]
to help keep track of the locations this question, it is also posted here: https://groups.google.com/forum/#!topic/h2ostream/7oyk8X_DvRg

**Comment by jakubhava** [comment]
Hi @lppsuixn, what do you mean to be able to get the result directly? The resulted frame `predictions` contains both the original columns and the response column. 

There is not much to do on our side, you need to use regular Spark approaches how to get the data from a column? 

You can for example do `predictions.select("prediction_output").take(10)`

**Comment by jakubhava** [comment]
Please open the issue if you have any questions!

**Comment by lppsuixn** [comment]
I want to get the label directly in Classification problem. As In binomial prediction,the  "prediction_output" column just give the probability of clsass.
And in the source code,they really only give these .
```scala
def getModelUdf() = {
    val modelUdf = {
      getOrCreateEasyModelWrapper().getModelCategory match {
        case ModelCategory.Binomial => udf[BinomialPrediction, Row] { r: Row =>
          getOrCreateEasyModelWrapper().predict(rowToRowData(r))
        }
        case ModelCategory.Regression => udf[RegressionPrediction, Row] { r: Row =>
          getOrCreateEasyModelWrapper().predict(rowToRowData(r))
        }
        case ModelCategory.Multinomial => udf[MultinomialPrediction, Row] { r: Row =>
          getOrCreateEasyModelWrapper().predict(rowToRowData(r))
        }
        case ModelCategory.Clustering => udf[ClusteringPrediction, Row] { r: Row =>
          getOrCreateEasyModelWrapper().predict(rowToRowData(r))
        }
        case ModelCategory.AutoEncoder => udf[AutoEncoderPrediction, Row] { r: Row =>
          getOrCreateEasyModelWrapper().predict(rowToRowData(r))
        }
        case ModelCategory.DimReduction => udf[DimReductionPrediction, Row] { r: Row =>
          getOrCreateEasyModelWrapper().predict(rowToRowData(r))
        }
        case ModelCategory.WordEmbedding => udf[WordEmbeddingPrediction, Row] { r: Row =>
          getOrCreateEasyModelWrapper().predict(rowToRowData(r))
        }
        case _ => throw new RuntimeException("Unknown model category")
      }
    }
    modelUdf
  }

  case class BinomialPrediction(p0: Double, p1: Double)

  case class RegressionPrediction(value: Double)

  case class MultinomialPrediction(probabilities: Array[Double])

  case class ClusteringPrediction(cluster: Integer)

  case class AutoEncoderPrediction(original: Array[Double], reconstructed: Array[Double])

  case class DimReductionPrediction(dimensions: Array[Double])

  case class WordEmbeddingPrediction(wordEmbeddings: util.HashMap[String, Array[Float]])
```
But In BinomialModelPrediction function，It can give what I want.
```scala
  public BinomialModelPrediction predictBinomial(RowData data) throws PredictException {
    double[] preds = preamble(ModelCategory.Binomial, data);

    BinomialModelPrediction p = new BinomialModelPrediction();
    double d = preds[0];
    p.labelIndex = (int) d;
    String[] domainValues = m.getDomainValues(m.getResponseIdx());
    p.label = domainValues[p.labelIndex];
    p.classProbabilities = new double[m.getNumResponseClasses()];
    System.arraycopy(preds, 1, p.classProbabilities, 0, p.classProbabilities.length);
    if (m.calibrateClassProbabilities(preds)) {
      p.calibratedClassProbabilities = new double[m.getNumResponseClasses()];
      System.arraycopy(preds, 1, p.calibratedClassProbabilities, 0, p.calibratedClassProbabilities.length);
    }
    return p;
  }
```
So,What can I do If I want to get the label Of Classification problem directly.

**Comment by jakubhava** [comment]
@mn-mikke I think this is related to our discussion about classification/regression problems

**Comment by jakubhava** [comment]
Starting from the next release, the predicted label will be stored in the column set by `setPredictionCol` and all the other details from predictions, such as probabilities will be available on the column set by `setDetailedPredictionCol`. The generation of the detailed prediction column is disabled by default and can be enabled as `withDetailedPredictionCol`

**Comment by jakubhava** [comment]
Starting from the next major release, the `prediction` column will contain directly the predicted label thanks to this PR https://github.com/h2oai/sparkling-water/pull/1508
