### ISSUE TITLE
sparklingWater - local class incompatible / cloud size under ###

### ISSUE THREAD

**Issue by hugoJuhel** [h2oai/sparkling-water#920]
Set up
----------

I'm running into troubles setupping sparkling-water on a standalone spark-cluster.  
I have a two-nodes and one master Spark cluster deployed on the top of a kubernetes cluster.  
I have been able to connect Python / R to my remote Spark cluster and perform several Spark operations.
So I'm pretty sure that my spark cluster is properly working. 

    Alive Workers: 2
    Cores in use: 8 Total, 8 Used
    Memory in use: 29.3 GB Total, 28.0 GB Used

I'm using the following Spark / H20 configuration with Sparkpling Water 2.1.35

    Spark master (MASTER)     : spark://spark-master:7077
    Spark home   (SPARK_HOME) : C:\spark-2.1.3-bin-hadoop2.6
    H2O build version         : 3.20.0.4 (wright)
    Spark build version       : 2.1.3
    Scala version             : 2.11

According to [this table][1], all versions should be compatible. 

Problem
----------
I have followed [this][2] tutorial, to set up pysparkling. However, none of the two provided ways to deploy sparkling-water work for me.

### Using `bin/pysparkling` ###
If i use the `bin/pysparkling` shell, I run into `java.lang.RuntimeException: Cloud size under xxx` error.

I have followed [this thread][3], and tried to twick the pysparkling command in several ways. I have also disabled the dynamic allocation in spark.
    
    bin/pysparkling --master spark://spark-master:70177 
    --conf "spark.dynamicAllocation.enabled=false" 
    --num-executors 1 --executor-cores 1 --executor-memory 8G 
    --driver-memory 4G --conf "spark.sql.autoBroadcastJoinThreshold=-1" 
    --conf "spark.scheduler.minRegisteredResourcesRatio=1" 
    --conf "spark.ext.h2o.client.log.dir=C:/Users/<username>/logs" 
    --conf "spark.ext.h2o.fail.on.unsupported.spark.param=false" 
    --conf "spark.ext.h2o.topology.change.listener.enabled=false"

Even with the above command, I get the `java.lang.RuntimeException: Cloud size under xxx`.

### Using PySparkling installed from PyPi repository (2.1) ###
If I launch Python fron a shell and directly create a Spark session using this code snippet, 

    from pyspark.sql import SparkSession
    spark = SparkSession.builder.appName("SparklingWaterApp").getOrCreate()
    from pysparkling import *
    hc = H2OContext.getOrCreate(spark)

When python try to execute `hc = H2OContext.getOrCreate(spark)`, I get an error message about `java.io.InvalidClassException: org.apache.spark.h2o.backends.internal.InternalBackendUtils$; local class incompatible: stream classdesc serialVersionUID = -9254888608862`.

The detailled error message is [here][4].

I have tried both of the procedure on my local computer, and directly from a worker in the kubernetes cluster, to check for potential connectivty issues. But the outcome is the same.

Does anyone get an idea about how i can troubleshoot my problem ?

Thanks in advance, jugo.

  [1]: https://github.com/h2oai/sparkling-water/tree/master/r
  [2]: https://s3.amazonaws.com/h2o-release/sparkling-water/rel-2.1/35/index.html
  [3]: https://github.com/h2oai/sparkling-water/issues/433
  [4]: https://pastebin.com/33251KUH

**Comment by jakubhava** [comment]
Thank you for the report!

I see that you are using Standalone Spark cluster mode, at this moment we are not testing on this deployment scenario, but I will have a look on it. 

Thank you!

Kuba

**Comment by hugoJuhel** [comment]
Hi @jakubhava 

Thanks a lot for your help ! I do appreciate it. Tell me if there anything you want me to try on my cluster to help you. 

jugo.

**Comment by jakubhava** [comment]
Hi @hugoJuhel, I just tried to run spark in standalone mode and my experiments worked.

What I did was 

`./bin/launch-spark-cloud` this helper script starts spark cloud in standalone mode. Feel free to modify the script or use it as template for starting your cluster

then `export MASTER=spark://Jakubs-MBP:7077` and
`./bin/pysparkling`

```
from pysparkling import *
hc = H2OContext.getOrCreate(spark)
```

Are you trying to modify class-path of the worker nodes?

**Comment by jakubhava** [comment]
@hugoJuhel I'm closing this issue as I wasn't able to reproduce. Please feel free to re-open or comment if you still have the issue

**Comment by worldofprasanna** [comment]
Hi @jakubhava I see this is very old thread. But I am still getting a similar error when trying to run h2o Internal mode in Kubernetes. Herewith given my version details,

sparkling water - `3.32.0.3-1-2.4`
spark - 2.4.1

This is the error I am getting,

`java.io.InvalidClassException: org.apache.spark.h2o.backends.internal.SpreadRDDBuilder; local class incompatible: stream classdesc serialVersionUID = -3638485938120636492, local class serialVersionUID = 7228232951407947741`

Is there any reason why we haven't added `serialVersionUID` to the class SpreadRDDBuilder ?

**Comment by jakubhava** [comment]
Hello hello @worldofprasanna -> I'm happy to help, but if that is ok for both you and @mn-mikke, can I point you to @mn-mikke? He's the current owner of the codebase and has a great overview of the project & I would like to keep him in the loop. I've been transferred to a different project.

Thanks for understanding :)

**Comment by mn-mikke** [comment]
Hi @worldofprasanna,
may I ask you to create a new issue and describe how you deploy your Spark cluster with SW library to K8s? Can you also share a docker file of your docker images? What version of Java do you use?

**Comment by worldofprasanna** [comment]
@mn-mikke Sure will do that. Thank you
