### ISSUE TITLE
rsparkling error with spark 2.2.1

### ISSUE THREAD

**Issue by rajkumarraibis** [h2oai/sparkling-water#949]
We are trying to run rsparkling on AWS EMR 5.11.1 , spark 2.2.1
Following is the code
> library(sparklyr)
> options(rsparkling.sparklingwater.version = "2.2.19")
> library(rsparkling)
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Amazon Linux AMI 2017.09
other attached packages:
rsparkling_0.2.9 sparklyr_0.8.4  
#EMR already has spark 2.2.1 , no need to install
> Sys.setenv(SPARK_HOME = "/usr/lib/spark")
> Sys.setenv(SPARK_DIST_CLASSPATH = "/usr/lib/hadoop:/usr/lib/hadoop/lib")
 
> conf <- spark_config()
> conf$`spark.ext.h2o.cloud.representative`="<CoreNodeIP>"
> conf$`spark.ext.h2o.node.port.base`=54323
> spark.ext.h2o.client.ip="<CoreNodeIP>"
> conf$`spark.ext.h2o.node.port.base`=54323
> conf$`spark.ext.h2o.client.port.base`=54323
> conf$`spark.ext.h2o.external.start.mode`="manual"
> conf$`spark.ext.h2o.backend.cluster.mode`="external"
> conf$`spark.ext.h2o.cloud.name`="h2osparklingcloud"
> conf$`spark.ext.h2o.spark.version.check.enabled`="false"
> conf$`spark.ext.h2o.internal_security_conf`="/mnt/opt/h2o-sparkling/security.properties"
> conf$`spark.ext.h2o.context.path`="h2o-sparkling"
> sc <- spark_connect(master = "yarn-client", config = conf , version = "2.2.1")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (1749): Gateway in port (8880) did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'ai.h2o:sparkling-water-core_2.11:2.2.19','ai.h2o:sparkling-water-ml_2.11:2.2.19','ai.h2o:sparkling-water-repl_2.11:2.2.19','no.priv.garshol.duke:duke:1.2', 
	'/mnt/usr/lib64/R/library/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 1749
    Log: /tmp/RtmpLDfEkG/file2ed9221cc4b7_spark.log

**Getting following error**
:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: ai.h2o#sparkling-water-core_2.11;2.2.19: not found, unresolved dependency: ai.h2o#sparkling-water-ml_2.11;2.2.19: not found, unresolved dependency: 
ai.h2o#sparkling-water-repl_2.11;2.2.19: not found, unresolved dependency: no.priv.garshol.duke#duke;1.2: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1197)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:304)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

Similar code is running fine in EMR 5.15 , Spark  2.3.0 .

Any help would be appreciated.

**Comment by jakubhava** [comment]
HI @rajkumarraibis can you please try running it with the latest released Sparkling Water for Spark 2.2? Thank you!

`options(rsparkling.sparklingwater.version = "2.2.25")`

Kuba

**Comment by rajkumarraibis** [comment]
Hi @jakubhava 

For spark 2.2.1 , Correct Sparkling water is http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/19/index.html
I am able to connect by adding following option
options(rsparkling.sparklingwater.location = "~/sparkling-water-2.2.19/assembly/build/libs/sparkling-water-assembly_2.11-2.2.19-all.jar")

Big Thanks for the quick help... :+1:

**Comment by jakubhava** [comment]
@rajkumarraibis even latest Sparkling Water is fine for Spark 2.2.1. The spark minor version is not important for us. I would suggest using the latest Sparkling Water on the link I provided. 

Could you please test that as well?

Thank you!

**Comment by rajkumarraibis** [comment]
That's not working..
actually I tested with http://h2o-release.s3.amazonaws.com/sparkling-water/rel-2.2/25/index.html. in first place. It was giving h2o version error . It said to that it detects h2o H2O version: 3.20.0.8 and need to downgrade to H2O version: 3.18..

**Comment by rajkumarraibis** [comment]
Now i am stuck at the next step. connection is happening but h2o_context is not getting created.
Please look...Following is the code and error

> library("sparklyr")
> options(rsparkling.sparklingwater.location = "/mnt/opt/h2o-sparkling/assembly/build/libs/sparkling-water-assembly_2.11-2.2.19-all.jar")
> library("rsparkling")
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
other attached packages:
[1] rsparkling_0.2.9 sparklyr_0.8.4  
> Sys.setenv(SPARK_HOME = "/usr/lib/spark")
> Sys.setenv(SPARK_DIST_CLASSPATH = "/usr/lib/hadoop:/usr/lib/hadoop/lib")
> Sys.setenv(HTTP_PROXY = "")
> Sys.setenv(HTTPS_PROXY = "")
> Sys.setenv(http_proxy = "")
> Sys.setenv(https_proxy = "")
> conf <- spark_config()
> conf$`spark.ext.h2o.cloud.representative`="corenodeip"
> conf$`spark.ext.h2o.node.port.base`=54323
> conf$`spark.ext.h2o.client.port.base`=54323
> conf$`spark.ext.h2o.external.start.mode`="manual"
> conf$`spark.ext.h2o.backend.cluster.mode`="external"
> conf$`spark.ext.h2o.cloud.name`="h2osparklingcloud"
> conf$`spark.ext.h2o.spark.version.check.enabled`="false"
> conf$`spark.ext.h2o.internal_security_conf`="/mnt/opt/h2o-sparkling/security.properties"
> conf$`spark.ext.h2o.context.path`="h2o-sparkling"
> 
> sc <- spark_connect(master = "yarn-client", config = conf , version = "2.2.1") 
> connection_is_open(sc)
[1] TRUE
> h2o_context(sc)
Error: org.apache.spark.h2o.backends.external.H2OClusterNotRunning: 
External H2O cluster is not running or could not be connected to. Provided configuration:
  cluster name            : h2osparklingcloud
  cluster representative  : corenodeip
  cluster start timeout   : 120 seconds"

It is possible that in case you provided only the cluster name, h2o is not able to cloud up
because multi-cast communication is limited in your network. In that case, please consider starting the
external H2O cluster with flatfile and set the following configuration 'spark.ext.h2o.cloud.representative'

**Comment by rajkumarraibis** [comment]
@jakubhava ,

Following are all the errors\warning from spark connection logs using `spark_log(sc, n = 100)`

18/09/27 20:34:06 WARN Utils: Service 'SparkUI (HTTPS)' could not bind on port 4440. Attempting port 4441.
18/09/27 20:34:06 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
18/09/27 20:34:09 WARN Token: Cannot find class for token kind HIVE_DELEGATION_TOKEN
18/09/27 20:34:09 WARN Client: Neither spark.yarn.jars nor spark.yarn.archive is set, falling back to uploading libraries under SPARK_HOME.
18/09/27 20:34:19 WARN SparkContext: Using an existing SparkContext; some configuration may not take effect.
18/09/27 20:34:33 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:42 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:42 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:43 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:43 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:43 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:43 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:43 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:49 WARN SparkSession$Builder: Using an existing SparkSession; some configuration may not take effect.
18/09/27 20:34:49 WARN H2OContext: Method H2OContext.getOrCreate with an argument of type SparkContext is deprecated and parameter of type SparkSession is preferred.
18/09/27 20:34:49 WARN ExternalH2OBackend: Increasing 'spark.locality.wait' to value 30000
18/09/27 20:34:49 WARN ExternalH2OBackend: Due to non-deterministic behavior of Spark broadcast-based joins
18/09/27 20:34:56 ERROR sparklyr: Backend (34753) failed calling getOrCreate on org.apache.spark.h2o.H2OContext

**Comment by jakubhava** [comment]
I see you are using External back end with automatic start mode of external H2O cluster. Do you have H2O cluster running? Also, this external cluster needs to use the extended jars as they are containing additional sparkling water classes.

Just to make sure, is the `corenodeip` ip address of one of the nodes of the H2O cluster? Could you please share also the logs of the external H2O cluster? Those will be the most important.

Also this configuration might help - `spark.ext.h2o.client.ip` It is used to force ip address of the H2O client(here running on the RSparkling side). Both H2O client and rest of the cluster needs to be located on the same network and in case of multiple network available, the H2O client and cluster might choose different networks and are not able to connect.

**Comment by rajkumarraibis** [comment]
@jakubhava ,

> I see you are using External back end with automatic start mode of external H2O cluster. 
**Ans**. No. external h2o cluster start mode is manual.
`conf$spark.ext.h2o.external.start.mode="manual"`

>Do you have H2O cluster running? Also, this external cluster needs to use the extended jars as they are containing additional sparkling water classes.
 **Ans**. Yes , External h2o cluster is running fine.
i can access h2o flow. All nodes on the cluster are able to talk to each other on port 54323
above is cluster details from h2o flow.

> Just to make sure, is the `corenodeip` ip address of one of the nodes of the H2O cluster?
**Ans** Yes

> Could you please share also the logs of the external H2O cluster? Those will be the most important.
[external H2O cluster logs.txt](https://github.com/h2oai/sparkling-water/files/2428468/external.H2O.cluster.logs.txt)

> Also this configuration might help - `spark.ext.h2o.client.ip` It is used to force ip address of the H2O client(here running on the RSparkling side). 
**Ans.**
Done and now getting below error
Error: Unexpected state in sparklyr backend, terminating connection: failed to invoke spark command
18/09/28 13:55:43 INFO NativeLibrary: Loaded library from lib/linux_64/libxgboost4j_gpu.so (/tmp/libxgboost4j_gpu6103375846834371606.so)
18/09/28 13:55:43 INFO SparkContext: Invoking stop() from shutdown hook
18/09/28 13:55:43 INFO SparkUI: Stopped Spark web UI at http://ip-255-255-255-255.ec2.exp.emr-lower.cdphp.com:4040
18/09/28 13:55:43 INFO YarnClientSchedulerBackend: Interrupting monitor thread
18/09/28 13:55:43 INFO YarnClientSchedulerBackend: Shutting down all executors
18/09/28 13:55:43 INFO YarnSchedulerBackend$YarnDriverEndpoint: Asking each executor to shut down
18/09/28 13:55:43 INFO SchedulerExtensionServices: Stopping SchedulerExtensionServices
18/09/28 13:55:43 INFO YarnClientSchedulerBackend: Stopped
18/09/28 13:55:43 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
18/09/28 13:55:43 INFO MemoryStore: MemoryStore cleared
18/09/28 13:55:43 INFO BlockManager: BlockManager stopped
18/09/28 13:55:43 INFO BlockManagerMaster: BlockManagerMaster stopped
18/09/28 13:55:43 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
18/09/28 13:55:43 INFO SparkContext: Successfully stopped SparkContext
18/09/28 13:55:43 INFO ShutdownHookManager: Shutdown hook called
18/09/28 13:55:43 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-ac518352-232b-40d5-8c56-3158e7d2e2b6

>Both H2O client and rest of the cluster needs to be located on the same network and in case of multiple network available, the H2O client and cluster might choose different networks and are not able to connect.
Ans. Yes both H2o client and H2o cluster are on same EMR and same network.
network is not an issue . at least for port 54323.

**Comment by jakubhava** [comment]
Hi @rajkumarraibis we know about this issue, however we have to prioritize the customer requests. When I have a free sec, will have another look.

Thanks for being patient!

Kuba
