### ISSUE TITLE
Support for lime in PySparkling

### ISSUE THREAD

**Issue by FavioVazquez** [h2oai/sparkling-water#970]
Hi everyone. Just a quick question. Is there support for lime and its API for models in PySpakling? Let's say I run something close to the examples here: https://github.com/h2oai/sparkling-water/blob/master/py/examples/pipelines/ham_or_spam_multi_algo.py can I use Lime afterwards? 

Thanks.

**Comment by FavioVazquez** [comment]
Oh ok thanks @jakubhava. But what about performance? Should I first sample the spark dataframe and then transform it?

**Comment by jakubhava** [comment]
It depends on your use-case. Most of the people prefer to clean their data in Spark ( here using Spark transformers) and after apply H2O Algos. As long your cluster has enough memory it's probably fine either way.

I will close this issue for now, feel free to comment if you have any other questions. Thanks!
